README.md, deploy/crds/build_kaniko_cr.yaml, deploy/crds/buildstrategy_kaniko_cr.yaml, pkg/controller/build/custombuild.go
- add kaniko sample
- acknowledge container.env[]
=> acknowledge container env / kaniko

pkg/controller/build/build_controller.go, pkg/controller/build/custombuild.go
```
apiVersion: build.dev/v1alpha1
kind: Build
metadata:
name: buildah-golang-build
spec:
source:
url: https://github.com/sbose78/taxi
secretRef:
name: my-git-secret  
strategy: "kaniko"
dockerfile: "Dockerfile" 
pathContext: "./"
outputImage: "image-registry.openshift-image-registry.svc:5000/sbose/taxi-app"
```
- reconcile `pipeline` service acount
- if build.generation changes, recreate Task & TaskRun
=> Support Private Git repo

deploy/crds/build.dev_builds_crd.yaml, pkg/apis/build/v1alpha1/build_types.go, pkg/controller/build/generate_tekton.go, pkg/controller/build/generate_tekton_test.go, samples/buildstrategy/buildstrategy_buildah_cr.yaml, samples/buildstrategy/buildstrategy_buildpacksv3_cr.yaml, samples/buildstrategy/buildstrategy_kaniko_cr.yaml, samples/buildstrategy/buildstrategy_source-to-image_cr.yaml, test/e2e/build_test.go
build.outputImage is now build.output.image
=> update buildstrategies based on api changes

openshift-ci/Dockerfile.tools
Ref. https://issues.redhat.com/browse/APPSVC-455
=> Add Dockerfile for OpenShift CI

README.md, hack/crd.sh, pkg/controller/build/generate_tekton.go, pkg/controller/build/generate_tekton_test.go
- support credentials for output images
- setup buildstrategies with `make local`
=> support credentials for output images

README.md, samples/buildstrategy/buildstrategy_buildpacks-v3_cr.yaml
Updating Build Strategy `buildpacks-v3`.
=> buildpacks-v3 Build Strategy

Makefile
These variables are either already used or it will be used soon.
=> Add commonly used variables

OWNERS
This file is required for OpenShift CI bot to merge PRs using Prow Tide plugin.
=> Add OWNERS file.  This is required for Prow Tide

Makefile
Refer - https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md#setting-flags-when-running-locally
=> Enable zap logr

.travis.yml, Makefile, hack/install-kind.sh, hack/install-operator-sdk.sh, hack/install-tekton.sh
Introducing Travis-CI and automation scripts to deploy operator testing infrastructure.
=> Travis-CI for unit tests

samples/buildstrategy/buildpacks-v3/README.md
Instructions to get credentials from Quay.io and then use them in a Buildpacks-v3 build
=> Steps to do a buildpacks-v3 build

OWNERS
.. Enrique, Sascha as reviewers.
=> Add Jordan as approver

OWNERS
* Removed folks who aren't actively contributing to the project from the approvers list only.
* Reviewers list is unchanged.
=> Update approvers list

hack/build-logs.sh
Script usage:
`build-logs <BUILD_RUN_NAME> [--follow]`
=> Add sample script to get logs of buildrun

OWNERS
Add @xiujuan95 as a reviewer. And @qu1queee as a approver.
=> Add a new reviewer

README.md
Getting to samples gave me a 404.
=> fix broken readme links

pkg/apis/build/v1alpha1/build_types.go, pkg/apis/build/v1alpha1/buildrun_types.go
Maintaining consistency by adding +optional for all omitempty json tags.
=> add +optional for omitempty json tags

README.md, docs/README.md, docs/build.md
=> Fix README.md files broken links

README.md
Resolves #168 
I added the supported versions to the `Try it!` section.
=> Add supported versions to README

test/e2e/validators.go
Add execution time for each build in e2e tests.
For issue: https://github.com/redhat-developer/build/issues/192
=> Add execution time for each build in e2e tests

hack/build-logs.sh
I am extending the `build-logs.sh` script to be able to pass in `--timestamps` that gets propagated to `kubectl logs --timestamps`. Is helpful to analyze where time is consumed during a build. Sample:
```bash
$ build-logs sascha-java-simple-1 --follow --timestamps
Build run: sascha-java-simple-1
Task run: sascha-java-simple-1-8nww8
Pod: sascha-java-simple-1-8nww8-pod-7jbj9
Logs of container step-create-dir-image-wf4sq:
Container terminated successfully.
Logs of container step-git-source-source-d7lkd:
2020-05-11T14:22:49.476648498Z {"level":"info","ts":1589206969.476032,"caller":"git/git.go:105","msg":"Successfully cloned https://github.com/SaschaSchwarze0/java-simple @ master in path /workspace/source"}
2020-05-11T14:22:49.476708549Z …
```
=> Add --timestamps argument to build-logs

docs/build.md, docs/buildrun.md
Changing the documentation based on the comments from @DhritiShikhar here:
- https://github.com/redhat-developer/build/pull/158#discussion_r424884869
- https://github.com/redhat-developer/build/pull/158#discussion_r424885074
=> Improve documentation related to timeout

test/e2e/validators.go
=> Check buildRun.Status.BuildSpec at the correct places

README.md, docs/buildstrategies.md
Fix some broken links in the main README.md and inside the docs/ folder.
=> Docs improvement

docs/buildrun.md
The BuildRun feature should be documented, adding
some lines into the existing BuildRun doc.
=> Document BuildRun snapshot feature

docs/proposals/build-execution-using-build-run.md
Inviting @zhangtbj to co-author this with me. 
Note,
I've played the role of @zhangtbj / Jordan's advocate to propose that the output image be supported in the `BuildRun` ;)
=> Propose decision making framework for BuildRun API changes

pkg/controller/buildrun/buildrun_controller.go
- In the origin controllor, there are some places that return 2 errors during reconciliation.
Where one of those errors could be `<nil>`, which is misleading while reading the error message.
- The func `handleError` only return multiple errors if each error is not nil.
- Also, it returns more descriptive error message.
=> Improve error handling in buildrun controllor

test/e2e/validators.go
I am wrapping the code in the e2e tests validators so that k8s client gets are retried in case of retryable errors (I chose servertimeout, timeout and toomanyrequests).
Specifically to not get failing builds like this: https://travis-ci.org/github/redhat-developer/build/builds/692674332#L2498
=> Handle retryable errors in from Client.Get

README.md
Build & BuildStrategy are the primary CRDs.
=> Fix Readme to mention primary CRDs

test/e2e/samples.go
Fixes #274 
See #274 for information.
=> Remove random test identifier suffix from image tag

test/e2e/validators.go
We are intermittently seeing this error in our e2e tests running on an IKS:
`2020-06-14T22:17:38Z 2 Error during client get is not retried: 'an error on the server ("Internal Server Error: \"/apis/build.dev/v1alpha1/namespaces/babb2a94-bcdd/buildruns/buildpacks-v3-f4bnq\": unable to retrieve token: Post https://iam.test.cloud.ibm.com/identity/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\n{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"buildruns.build.dev \\\"buildpacks-v3-f4bnq\\\" is forbidden: get buildruns is forbidden\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"buildpacks-v3-f4bnq\",\"group\":\"build.dev\",\"kind\":\"buildruns\"},\"code\":403}") has prevented the …
=> Retry net/http error in e2e tests

docs/proposals/buildstrategy-steps-resources.md
Add proposal on how to handle resource
assignments to strategy steps
=> Add proposal on how to handle resource assignments to strategy steps for issue #239

OWNERS
Including both as reviewer and approver sections (/cc @gabemontero, @adambkaplan, @sbose78)
=> Adding Adam and Gabe to OWNERS.

OWNERS
Update Owners so that we can get more help when reviewing or approving.
=> Owners update

Makefile, pkg/controller/build/build_controller.go, pkg/controller/buildrun/buildrun_controller.go, pkg/controller/buildrun/runtime_image_test.go, test/catalog.go, test/e2e/e2e_suite_test.go, test/e2e/ginkgo_operator-sdk.go, test/e2e/validators.go
- Add fixes based on running staticcheck, see https://staticcheck.io/ for more info
- Remove code that was commented out
- Remove duplicate flag from the Makefile
- Enhance text from a func in e2e to be more accurate to what the func is doing
=> Add some code enhancements

pkg/controller/buildrun/buildrun_controller.go, pkg/controller/buildrun/buildrun_controller_test.go
Fixes #338 
I am adding a condition to stop the reconciliation trying to work on an already completed BuildRun for the reason outlined in the issue.
=> Do not perform any logic for completed BuildRuns

pkg/controller/buildrun/buildrun_controller.go, pkg/controller/buildrun/buildrun_controller_test.go
Fixes #332 
When the buildrun controller finds a build that has an empty registered state, then the build controller has not yet (finished) validating it. In this case, I change the code to retry in five seconds.
=> Delay taskrun creation if build is not yet validated

pkg/controller/buildrun/buildrun_controller.go, pkg/controller/buildrun/buildrun_controller_test.go
Fixes #348 
As explained in the issue, I am changing the way the retry is done. I tested this through an instrumentation of the build controller where I added the following code after line 121 (and introduced a `var first = true` in that file globally):
```go
if first {
first = false
ctxlog.Debug(ctx, "Requeuing in 1s")
return reconcile.Result{
RequeueAfter: 1 * time.Second,
}, nil
}
```
I then ran: `kubectl apply -f build.yaml && kubectl apply -f buildrun.yaml`. The result is:
```
2020-08-19T16:19:52.227+0200    DEBUG   build.build-controller  start reconciling Build {"namespace": "build-test", "name": "sascha-docker-simple"}
2020-08-19T16:19:52.228+0200    DEBUG   build.build-controller  Requeuing in 1s
2020-08-19T16:19:52.739+0200    DEBUG   build.buildrun-controller       starting …
```
=> Change delay logic to use an error

docs/proposals/local-registry-image-specs.md
Fix text in local image registry proposal
=> docs: Fix text in local image registry proposal

README.md
link to heroku build strategy missing folder name
Signed-off-by: John Duimovich <jduimovich@gmail.com>
=> typo and link fixes

docs/proposals/build-execution-using-build-run.md
This is just a test commit that should not hurt. I think we have an issue
with the way merging is done and contributions.
=> Fix some markdown linters in proposals

README.md
Required for `master` branch to be up-to-date with the new release
=> Update the README with v0.1.1 docs reference

test/integration/utils/service_accounts.go
In the integration test suite, we should not raise an error if the
desired ServiceAccount already exists. The `pipeline` ServiceAccount in
particular can exist in some Tekton distributions (ex: OpenShift
Pipelines).
=> tests: Do not error if ServiceAccount exists

README.md
Add new tag v0.2.0 references
Add missing supported k8s version
=> Update README to be adhoc with the latest release

hack/build-logs.sh
In a k8s pod, the items in the `.status.containerStatuses` are not guaranteed to be in the same order as in `.spec.containers`. The build-logs script was making that incorrect assumption. Fixing this by correlating on the container name.
=> Correlate container by name

pkg/controller/buildrun/generate_taskrun.go, pkg/controller/buildrun/generate_taskrun_test.go, test/buildstrategy_samples.go, test/integration/buildstrategy_to_taskruns_test.go
I was not really aware that I already need vacation. :-(
=> Correct annotation propagation logic

test/integration/buildruns_to_taskruns_test.go
Validate for the existance of a pending and running condition from
a list of conditions. Do not assert for an exact list len. Look for
a pending and running condition inside the list via ContainElement,
instead of asserting against a particular list item.
=> Make conditions sequence test less strict

README.md
Updates references to docs, samples and release with v0.3.0
=> Reflect v0.3.0 in README.md

test/integration/build_to_buildruns_test.go
Fixing new issues that the sanity check reports. Probably due to a version update of the tool being used.
```release-note
NONE
```
=> Fix sanity check issues

OWNERS
This allow us to easily assign issues and PRs to more contributors. Add HeavyWombat as an approver
```release-note
NONE
```
=> Add more people to reviewers

docs/configuration.md
Wrong link of controller.yaml in configuration.md
-->
=> Correct the link of controller.yaml in configuration.md

pkg/reconciler/buildrun/resources/service_accounts.go
Ensure we dont mount the generated serviceAccount token secret. This happens when users make use of the following feature:
```yaml
---
apiVersion: shipwright.io/v1alpha1
kind: BuildRun
metadata:
name: kaniko-golang-buildrun
spec:
buildRef:
name: kaniko-golang-build
serviceAccount:
generate: true <--------------------- Here!
```
Avoid automounting this secret, while is not used for anything at the pod level.
The following is an example of the `pod` `spec.volumes` that ends-up generated as part of a BuildRun.
See how `kaniko-golang-buildrun-sa-token-x527v` is not longer part of the volumes when using a controller with this PR fix. The only secret we should mount is the one specified by users, in this example the `tekton-internal-secret-volume-build-xwxt6` which uses the secret `build`. …
=> Ensure we dont mount generated serviceAccount token secret in pods

docs/build.md, docs/buildstrategies.md, pkg/reconciler/build/build_test.go, pkg/reconciler/buildrun/resources/taskrun_test.go, samples/build/build_buildah_cr.yaml, samples/build/build_buildpacks-v3-heroku_cr.yaml, samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml, samples/build/build_buildpacks-v3_cr.yaml, samples/build/build_buildpacks-v3_namespaced_cr.yaml, samples/build/build_kaniko_cr.yaml, samples/build/build_source-to-image_cr.yaml, test/build_samples.go, test/catalog.go, test/data/build_buildah_cr_custom_context+dockerfile.yaml, test/data/build_buildpacks-v3_golang_cr.yaml, test/data/build_buildpacks-v3_java_cr.yaml, test/data/build_buildpacks-v3_nodejs_runtime-image_cr.yaml, test/data/build_buildpacks-v3_php_cr.yaml, test/data/build_buildpacks-v3_ruby_cr.yaml, test/data/build_kaniko_cr_advanced_dockerfile.yaml, test/data/build_kaniko_cr_custom_context+dockerfile.yaml, test/data/build_timeout.yaml, test/integration/build_to_buildruns_test.go, test/integration/build_to_git_test.go
_Note:  Im adding a WIP label for now, just to get first some feedback on these changes_.
This covers around 80% of #366
This PR does the following:
- Moves all runtimes (except Java) into the new shipwright repos, these are:
-  https://github.com/shipwright-io/sample-php
- https://github.com/shipwright-io/sample-ruby
- https://github.com/shipwright-io/sample-nodejs
- https://github.com/shipwright-io/sample-go
- https://github.com/shipwright-io/sample-java
- Now the sample codes are very minimal, this should provide better times when running e2e tests
- Fixes some failing unit tests.
Commits can be squashed, let me know.
for details on coding conventions, github and prow interactions, and the …
=> Refactor git samples

.github/workflows/nightly.yaml, .github/workflows/release.yaml
Nightly was failing because of an error on the job definition, where an
if conditional was made.
```release-note
NONE
```
=> Fix CI nightly/release yaml

README.md
=> Minor fixes to the readme

test/data/build_buildpacks-v3_private_github_cr.yaml, test/data/buildrun_buildpacks-v3_ruby_cr.yaml
It's a following PR to use git protocol in git url for the PR https://github.com/shipwright-io/build/pull/702
=> Change to use git protocol for git url

2021-roadmap.md
Copied from [hackmd](https://hackmd.io/J7-A7QpqSoGk3wmW-QYtdQ?both) after addressing/resolving comments -- **please leave comments on this PR!**
/kind documentation
```release-note
NONE
```
/assign @qu1queee 
/assign @sbose78 
/assign @adambkaplan
=> Add 2021 roadmap

docs/proposals/modifying-output-image.md
/kind feature
```release-note
NONE
```
=> Add EP: Modifying Output Image

README.md
Updates references to docs, samples and release with v0.4.0
```release-note
NONE
```
=> Reflect v0.4.0 in README.md

OWNERS
Add Jason as an approver. Move zhangtbj to only reviewers.
```release-note
Add ImJasonH as an approver for PRs
```
=> Add Jason as an approver

test/e2e/common_test.go
We sometimes have failing e2e tests where a build was not registered with reason BuildStrategyNotFound. Example:
```
[1] For a Kubernetes cluster with Tekton and build installed
[1] /home/runner/work/build/build/test/e2e/e2e_test.go:16
[1]   when a heroku Buildpacks build is defined using a namespaced strategy
[1]   /home/runner/work/build/build/test/e2e/e2e_test.go:107
[1]     successfully runs a build [BeforeEach]
[1]     /home/runner/work/build/build/test/e2e/e2e_test.go:127
[1] 
[1]     Expected
[1]         <v1alpha1.BuildReason>: BuildStrategyNotFound
[1]     to equal
[1]         <v1alpha1.BuildReason>: Succeeded
[1] 
[1]     /home/runner/work/build/build/test/e2e/common_test.go:48
```
The test case is creating the build strategy and right after that the build. When the failure …
=> Retry build creation if build controller did not find build strategy

README.md
Point to the Community repo, rather than the Build one.
```release-note
NONE
```
=> Update reference to community meetings

test/e2e/validators_test.go
There are setups, where the user cannot create a serviceaccount, but there is
already a system provided service account that could be used. Since the code
will always try to create a service account in order to also check if one is
already available, in those read-only situation the setup code will fail.
Look-up service account first  initiating a create call.
```release-note
NONE
```
=> Refactor E2E test service account setup

docs/build.md, docs/buildstrategies.md
Fixes #847 
Modified example in `build.md` that should illustrate the revision property and fixed relative paths to build and buildRun config for `buildstrategies.md`.
```release-note
Fixed documentation for build and buildStrategies
```
=> Improve Documentation for build and buildRun

OWNERS
Folks who've moved away to other projects.
=> remove inactive reviewers

docs/buildstrategies.md, samples/build/build_ko_cr.yaml, samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Now that we have paramerers, let's parameterize. Doing that for the ko build strategy.
```release-note
action required: the sample build strategy for ko now supports parameterization. If you previously used the contextDir to point to the main package, then you now must use the package-directory parameter instead.
```
=> Parameterize ko build strategy

docs/buildstrategies.md
Just notice that this did not look nice in our docs due to missing back-quotes.
```release-note
NONE
```
=> Add missing closing back-quote

cmd/mutate-image/README.md
Update main README of pkg.
```release-note
NONE
```
=> Minor fixes on spelling for mutate img binary pgk

HACK.md, docs/proposals/enable-local-source-code-support.md
Add link to SHIP.
Bump Go version in `HACK.md`.
```release-note
NONE
```
=> Update docs with regards to local source feature

docs/proposals/README.md, docs/proposals/build-execution-using-build-run.md, docs/proposals/buildstrategy-annotation-propagation.md, docs/proposals/buildstrategy-steps-resources.md, docs/proposals/buildstrategy.md, docs/proposals/cli.md, docs/proposals/dedicated-shipwright-operator.md, docs/proposals/enable-local-source-code-support.md, docs/proposals/local-registry-image-specs.md, docs/proposals/modifying-output-image.md, docs/proposals/parameterize-strategies.md, docs/proposals/remote-artifacts.md, docs/proposals/removal-tekton-resources.md, docs/proposals/runtime-image.md, docs/proposals/shipwright-website.md, docs/proposals/webhook-validation.md
Add a note on where the Enhancement Proposal's are currently hosted(_community repo_).
```release-note
NONE
```
=> Update docs/proposals to reflect community SHIPs

test/e2e/common_suite_test.go
Depending on the test infrastructure, it can take a bit of time until the
build resource is available in the cluster. If a buildrun starts too fast,
it can happend that it does not find the build yet.
Add look-up in `Create` to verify that the create operation is completed.
```release-note
NONE
```
=> Mitigate bundle E2E test build create issue

cmd/git/main.go
For older Git versions, the `git submodule update` command does not have
the `--depth` flag to create shallow clones, instead the usage of `--depth`
leads to errors trying to update submodules. Similar to `--no-tags`, this only
occurred in unit tests on systems with older Git versions.
Add check to verify that `--single-branch` is available in `update` as this is
a clear indication that shallow clones for submodules are available.
```release-note
NONE
```
=> Add check to verify `--depth` can be used

docs/buildstrategies.md, samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml, samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml, samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml, test/clusterbuildstrategy_samples.go
Updating Kaniko in our sample build strategies to the new release.
```release-note
Updated Kaniko in the sample build strategies to v1.7.0
```
=> Update Kaniko to v1.7.0

go.mod, go.sum, vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go, vendor/modules.txt
Update image spec to v1.0.2
```release-note
NONE
```
=> Update image spec to v1.0.2

samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
Updating Trivy to the latest release before we ship something.
```release-note
Update Trivy in the sample build strategy to 0.21.2
```
=> Update Trivy to 0.21.2

.github/workflows/release.yaml
Grant the release workflow permission to create pull requests. This will
allow the release workflow to submit the PR that updates our README
documentation.
/kind cleanup
```release-note
NONE
```
=> Grant release workflow permission to create PRs

cmd/waiter/waiter.go
I have seen some [flaky](https://github.com/shipwright-io/build/runs/5051787522?check_suite_focus=true#step:11:190) e2e tests related to this [section](https://github.com/shipwright-io/build/blob/main/test/e2e/e2e_local_source_upload_test.go#L99-L105). My understanding is that we are hitting the ginkgo timeout(90secs), however the `waiter` timeout(60secs) should have get triggered before, but it didn't happen.
After taking a look on the `waiter` timeout func, I decided to modify this in favor of a timeout with `channels` and `select`.
```release-note
Enhance waiter timeout processing.
```
=> Enhance timeout of waiter

.github/workflows/release.yaml, README.md
- Add `sed` to replace version on the sample strategies filename
- Add current latest stable version to the strategies file endpoint
```release-note
NONE
```
=> Enhance release action

docs/buildstrategies.md, samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml, samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml, samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml, test/clusterbuildstrategy_samples.go
Updating build strategy tools.
```release-note
Update sample build strategy tools: Kaniko to 1.8.0, Trivy to 0.24.4
```
=> Update Kaniko to 1.8.0, update Trivy to 0.24.4

pkg/reconciler/buildrun/buildrun_test.go, pkg/reconciler/buildrun/resources/build.go, pkg/reconciler/buildrun/resources/params.go, pkg/reconciler/buildrun/resources/sources/http.go
Use quote format specifier where possible.
```release-note
NONE
```
=> Use quote format specifier where possible

docs/build.md, docs/buildrun.md
Prep Shipwright docs for downstream
```release-note
NONE
```
=> RHDEVDOCS-3863 Prep Shipwright docs for downstream

cmd/git/main_test.go
Sets and unsets variables for controlling git configurations for the set of failure diagnostics tests.
Additionally, it introduces a new set of sequential tests that depend on git configurations. Side-effects such as mutating would break these tests in parallel. Concretely, failure diagnostics and git-lfs tests are not supposed to run in parallel.
Fixes #1031 
For pull requests with a release note:
```release-note
NONE
```
=> Ensures no external configuration influences tests for git failure diagnostics

samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
Updating the tools in the sample build strategies to the current stable releases before our shipment.
```release-note
NONE
```
=> Update build strategy tools

Makefile
Add `.PHONY` that do not target a file.
Use one `.PHONY` statement per target.
```release-note
NONE
```
=> Fix inconsistent use of `.PHONY` in `Makefile`

hack/check-latest-images.sh
The pull requests like https://github.com/shipwright-io/build/pull/1145/files only updates the docs.
The reason is that it iterates the directories (docs, samples, test), but within the update looks for the currently used tag globally. After having updated docs, the checks for samples and test therefore will find the current tag being the latest one in the docs directory.
I am also adding some logging and making the script a little more efficient.
```release-note
NONE
```
=> Fix build strategy image update

hack/check-latest-images.sh
Adressing two problems with the logic to read the CURRENT_TAG:
1. `grep` fails if it does not find anything. But that is normal as an image is not necessarily in all directories.
2. In the test case, the image name is in a string (`"<IMAGE>"`). The existing extraction code was not matching it there.
This time, I ran it locally with `act`. Let's see how many further PRs are needed. :-)
```release-note
NONE
```
=> Adjust CURRENT_TAG logic

OWNERS
Remove user `coreydaley` from OWNERS file
```release-note
NONE
```
=> Update OWNERS - Remove coreydaley

cmd/git/main.go, cmd/waiter/main.go, pkg/reconciler/buildlimitcleanup/controller.go, pkg/reconciler/buildrun/controller.go, pkg/reconciler/buildrunttlcleanup/controller.go, pkg/reconciler/buildstrategy/controller.go, pkg/reconciler/clusterbuildstrategy/controller.go
The new golangci-lint version came with new findings. Addressing them.
```release-note
NONE
```
=> Fix new golangci-lint findings

README.md
When using the OpenShift cluster it needed some extra configurations to adequate SCC. Added a section for the same.
```release-note
NONE
```
=> Add steps for running on OpenShift

docs/build.md, docs/buildstrategies.md, hack/release.sh
#1388 duplicated the build strategies. This requires some updates to the documentation and to the release script.
```release-note
NONE
```
=> Update references to build strategies to v1beta1

ROADMAP.md
Fixes #1449
```release-note
Add ROADMAP doc
```
=> Add ROADMAP doc

ADOPTERS.md, ROADMAP.md
Add missing copyright header to newly created files.
```release-note
NONE
```
=> Add missing copyright header

.github/workflows/release-branch.yml
Add release branch workflow from shared starter workflow template.
Part of #1555 
/kind cleanup
```release-note
NONE
```
=> Release Branch Workflow

go.mod, go.sum, vendor/github.com/docker/docker/AUTHORS, vendor/github.com/docker/docker/pkg/homedir/homedir.go, vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go, vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go, vendor/modules.txt
Ref: https://github.com/moby/moby/security/advisories/GHSA-x84c-p2g9-rqv9
Update to address vulnerability finding.
```release-note
NONE
```
=> Bump `github.com/docker/docker` dependencies

README.md
Related to https://github.com/shipwright-io/community/issues/240
Also added a footer on being a CNCF sandbox.
```release-note
NONE
```
=> Ensure Code of Conduct is visible in README

cmd/image-processing/main_test.go, pkg/image/vulnerability_scan_test.go
Use "Vulnerability Scanning" in all test cases covering vulnerability scanning, so that they can be picked up more easily in a focus or skip.
```release-note
NONE
```
=> Use common test description for Vulnerability Scanning

docs/tutorials/building_with_buildkit.md, docs/tutorials/building_with_buildpacks.md, docs/tutorials/building_with_kaniko.md
[Fixes issue#7](https://github.com/shipwright-io/build/issues/1744)
```release-note
NONE
```
=> Update tutorial add spec.source.type to the example build definitions

README.md
Update Calendar and Mailing List. Use CNCF provided service endpoints.
```release-note
Move Mailing List and Calendar to CNCF provided ones.
```
=> Update Calendar and Mailing List

README.md
Cherry-picking the v0.15.0 addition to the main branch.
```release-note
NONE
```
=> Update Readme with new Tag v0.15.0

README.md
Cherry-picking the readme updates into main branch.
```release-note
NONE
```
=> Add v0.15.x releases to main

go.mod, go.sum, vendor/golang.org/x/net/html/atom/table.go, vendor/golang.org/x/net/html/parse.go, vendor/golang.org/x/net/html/token.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/server.go, vendor/modules.txt
Fixes CVE-2025-22872
```release-note
NONE
```
=> Update golang.org/x/net to v0.38.0

README.md
Cherry-picking readme updates into main branch.
```release-note
NONE
```
=> Update Readme with new Tag v0.15.4 / v0.15.5 / v0.15.6 / v0.15.7 / v0.15.8

README.md
Update Readme with new Tag v0.15.9
```release-note
NONE
```
=> Update Readme with new Tag v0.15.9

README.md
Cherry-picking the v0.16 readme updates into main.
```release-note
NONE
```
=> Add v0.16 versions to main readme
