.travis.yml

Change the configuration:
```
service:
- docker
```
to
```
services:
- docker
```
If using the old configuration, the docker service won't be enabled and startup.
Then the kind create cluster command will report failure because the docker is not started up:
```
+kind create cluster
ERROR: failed to list clusters: command "docker ps -q -a --no-trunc --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 1
```
So fix to the correct format which follows by:
https://docs.travis-ci.com/user/database-setup/

Fix the services typo in .travis.yml

---

.gitignore
pkg/apis/build/v1alpha1/build_types.go
pkg/controller/build/credential_test.go
pkg/controller/build/generate_tekton.go
pkg/controller/build/generate_tekton_test.go

Hi,
There is no unit test for the `getCustomTaskRun` function in `controller/build/generate_tekton.go`
I added a unit test to make go coverage of this file to reach 100%:
1. ensure generated TaskRun's basic information are correct
2. ensure generated TaskRun's input and output resources are correct
3. ensure generated TaskRun's spec special input params are correct
Also did some refine:
1. Change the "source" and "url" in generate_tekton.go to the const
2. git ignore the JetBrains IDE config
3. fix the typo `containing`
4. Remove an additional newline
Please review

Add unit test for getCustomTaskRun

---

deploy/role.yaml

It works fine in default namespace without this role permission.
But when I build the controller images and deploy it in another namespaces, like `-n build-operator`, the controller reported some permission error in the log:
```
{"level":"info","ts":1583925582.230259,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1583925582.2307181,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"buildstrategy-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1583925582.2310143,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1583925582.231089,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="} …
```

Add tekton resource permissions for operator rbac role

---

cmd/manager/main.go
deploy/role.yaml
deploy/role_binding.yaml

- Change the operator to cluster scope follow by the operator user guide:
https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md
- Change to use `ClusterRole` and `ClusterRoleBinding`
- Add `serviceaccounts` permission for ClusterRole, because the controller still need to operate the serviceaccount during the build.
Please review, Thanks!

Change to cluster-scope operator

---

hack/crd.sh

This was breaking my local test of the controllers, when
following the "try it" README.md section.
The controller manager will fail to start if this is not added in
advance, when running `make local`

Add missing CRD file reference

---

cmd/manager/main.go

After we change to cluster scope operator, there are many error messages like:
```
...
E0315 10:58:13.324893       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E0315 10:58:14.331242       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E0315 10:58:15.455737       1 reflector.go:123] github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go:65: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E0315 10:58:16.461906       1 reflector.go:123] …
```

Solve the unstructured.Unstructured error message in controller log

---

Makefile

Hi all,
I provided this PR because I need to patch some configurations to build the controller image by using `operator-sdk build`. Please also let me know if there is any other good way.
First of all, the binary name which operator-sdk requires is `build-operator`:
https://github.com/redhat-developer/build/blob/master/Dockerfile#L8
So if I build by using `operator-sdk build` by default directly, it will report error:
```
✘-1 $ operator-sdk build us.icr.io/knative_jordan/build-controller
INFO[0036] Building OCI image us.icr.io/knative_jordan/build-controller 
Sending build context to Docker daemon  131.9MB
Step 1/7 : FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
---> 6ce38bb5210c
Step 2/7 : ENV OPERATOR=/usr/local/bin/build-operator     USER_UID=1001     USER_NAME=build-operator …
```

Refine the operator name in Makefile

---

Dockerfile

Hi all,
I just found there is another `Dockerfile` in the root path, I think it should be used by RedHat internally. (We use `operator-sdk build` command to build by using the build/Dockerfile` directly)
I forgot the rename this binary name and fix in this PR, please review.
BTW, are you still using this Dockerfile? And do we want to maintain two Dockerfiles in this repo? I think it is a little confusing.

Refine the Dockerfile in root folder

---

README.md

Refine the secret name in Build example yaml as a better name.
- First the `credentials` needs the `name` parameters
-  Change the secret names for builder and output to a better names

Refine the secret name in Build example yaml

---

README.md
deploy/crds/build.dev_buildruns_crd.yaml
deploy/crds/build.dev_builds_crd.yaml
pkg/apis/build/v1alpha1/build_types.go
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go
samples/build/build_buildpacks-v3_namespaced_cr.yaml
samples/build/build_kaniko_cr.yaml
samples/buildrun/buildrun_buildah_cr.yaml
samples/buildrun/buildrun_kaniko_cr.yaml
test/e2e/main_test.go
test/e2e/validators.go

Add resource limit support for this feature: https://github.com/redhat-developer/build/issues/91
- Add resource parameter for both Build and BuildRun. If the resource is defined in both Build and BuildRun, the BuildRun values will overwrite the values in Build
- Change the generateTaskRun method to merge and add resource limit into the `step.Resources`
- Add two more unit tests for generateTaskRun
- Add the resource limit to some of the e2e test Build or BuildRun CRs.
Please review. Thanks!

Add resource limit support

---

samples/buildrun/buildrun_buildah_cr.yaml
samples/buildrun/buildrun_kaniko_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml

Hi @sbose78 ,
I suggest we allow the requires Linux capabilities for each buildstrategy. We only fix the Buildpacks and Kaniko issues.
If we run the Build v2 on a project cluster env, all the Linux capabilities may disable by default. We should allow them for our build process. Without these permissions. the build process will report some error like:
**Kaniko:**
- Kaniko: without CHOWN reports error:
```
INFO[0008] Unpacking rootfs as cmd COPY . /go/build requires it.
error building image: error building stage: failed to get filesystem from image: chown /bin: operation not permitted
2020/04/03 05:46:10 Skipping step because a previous step failed
```
- Kaniko: without DAC_OVERRIDE reports error:
dac_override allows root to bypass file read, write, and execute permission checks. DAC is an …

Add detail capabilities in buildstrategy yamls

---

README.md
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go
samples/build/build_kaniko_cr.yaml
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
test/data/build_buildah_cr_custom_context+dockerfile.yaml
test/data/build_kaniko_cr_custom_context+dockerfile.yaml
test/data/build_kaniko_cr_private_github.yaml
test/data/build_kaniko_cr_private_gitlab.yaml
test/data/buildrun_buildah_cr_custom_context+dockerfile.yaml
test/data/buildrun_kaniko_cr_custom_context+dockerfile.yaml
test/e2e/main_test.go
test/e2e/validators.go

Changes for issue #98.
- I am removing pathContext from the README and the samples and replace it by source.contextDir which was already read in the code
- I am also updating the build strategy to read from build.source.contextDir for consistency and adopted the generate_taskrun accordingly

Consolidate context directory for Kaniko and BuildAh

---

deploy/crds/build.dev_builds_crd.yaml
pkg/apis/build/v1alpha1/build_types.go
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
test/catalog.go

From [issue 111](https://github.com/redhat-developer/build/issues/111)
Add missing Reason column for the Build CRD. This have two types of
reasons, either a "Succeed" message, or an error(from resources validations).
This also includes the related unit-tests
Examples:
```sh
$ k -n build-examples get Build
NAME                     REGISTERED   REASON                                              BUILDSTRATEGYKIND      BUILDSTRATEGYNAME   CREATIONTIME
buildpack-nodejs-build   False        secret output-registry-credentials does not exist   ClusterBuildStrategy   buildpacks-v3       8s
$ k -n build-examples get Build
NAME                     REGISTERED   REASON                                   BUILDSTRATEGYKIND       BUILDSTRATEGYNAME   CREATIONTIME
buildpack-nodejs-build   False …
```

Add missing Reason column to the Build controller 

---

samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
test/data/build_kaniko_cr_advanced_dockerfile.yaml
test/data/buildrun_kaniko_cr_advanced_dockerfile.yaml
test/e2e/main_test.go

We are currently testing how well builds work with restrictions through a pod security policy for the Tekton pods. The added test case is the result. The test case succeeds against a "normal" k8s cluster. It fails with a psp in place and we are checking which permissions it needs or if certain Dockerfile constructs (`RUN something` after `USER root`) can only work with privileged containers.

Add dependency on SETGID and SETUID for Kaniko

---

deploy/crds/build.dev_builds_crd.yaml
pkg/apis/build/v1alpha1/build_types.go

Some updates(e.g. `additionalPrinterColumns `) in `build.dev_builds_crd.yaml` will be overwritten using `operator-sdk generate crds`.
Therefore, we also need the comments using the `+kubebuilder`

Add +kubebuilder for build CRD

---

pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
test/catalog.go

Fix issue: https://github.com/redhat-developer/build/issues/146
I have verified this modification and e2e test is also passed. Now, when I apply a `build` with a nil `spec.strategy.kind`, then it will use the default  NamespacedBuildStrategyKind `BuildStrategy`. And also build process can come up  normally.
Below is the step of my verification:
- apply a `build` and `buildrun` with nil `spec.strategy.kind`
```
---
apiVersion: build.dev/v1alpha1
kind: Build
metadata:
name: kaniko-golang-build-zoe-spec
spec:
source:
url: https://github.com/sbose78/taxi
strategy:
name: kaniko
dockerfile: Dockerfile
resources:
limits:
cpu: "500m"
memory: "1Gi"
output:
image: us.icr.io/zoe_namespace/test-spec
credentials:
name: icr-knbuild
```
```
apiVersion: build.dev/v1alpha1
kind: BuildRun
metadata:
name: …
```

fix BuildStrategyKind is nil issue

---

hack/install-kind.sh

kind releases version 0.8.0 recently which changes the default k8s node version to 1.18. K8s v1.18 includes the managedFields field for server-side apply, see https://kubernetes.io/blog/2020/04/01/kubernetes-1.18-feature-server-side-apply-beta-2/. This breaks our build. See https://travis-ci.com/github/redhat-developer/build/builds/163723206.
The code change introduces an environment variable `KIND_CLUSTER_VERSION` in `install-kind.sh` with a default `v1.17.5`. Creating PR to see if this builds successfully.

Define k8s node version

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
test/catalog.go

For issue #108 
**Add unit-test for the BuildRun controller**
This commits includes the unit test implementation for the
different scenarios that can happen during the BuildRun Reconciliation. During the testing I found some bugs, therefore I introduced minor code changes on the `buildrun_controller.go`
This also includes new catalog functions to keep the unit tests very DRY.
**Adds unit-test for errors handling when setting owner reference objects fails**
For the above I introduce a new type func(), this allow us to mock errors for the function that sets the object owner references.
**Fix e2e breaking change**
The `buildrun_buildpacks-v3_namespaced_cr.yaml` example forces users to have a pipeline SA in their namespace. This is not documented anywhere, therefore add the `generate` flag to …

BuildRun controller unit tests

---

pkg/controller/buildstrategy/buildstrategy_controller.go
pkg/controller/buildstrategy/buildstrategy_controller_test.go
pkg/controller/buildstrategy/buildstrategy_suite_test.go
pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller_test.go
pkg/controller/clusterbuildstrategy/clusterbuildstrategy_suite_test.go

Although we don't have logic in buildstartegy and clusterbuildstrategy controller, but the controllers are generated and located in the `pkg` package.
We need to ensure our test coverage is enough for the production. So we have to add at least one unit test to test its basic function.
If we want to add more features in two controllers, let us continue enriching the test cases in the unit test logic.
What I added in this PR:
- Add one basic unit test for buildstrategy controller
- Add one basic unit test for clusterbuildstrategy controller

Add initial unit tests for buildstrategy for test coverage

---

Makefile
hack/install-tekton.sh

Fixes #144. After merging #166, we are able to use Tekton `v0.11.0` on CI.

Tekton Pipelines v0.11.0

---

.gitignore
.travis.yml
Makefile

Trying out a different solution for PR #177. Local output (ignore the long runtime, my machine is a little overwrought:
```sh
$ make test-unit
rm -rf build/coverage
mkdir build/coverage
GO111MODULE=on ginkgo \
-randomizeAllSpecs \
-randomizeSuites \
-failOnPending \
-nodes=4 \
-compilers=2 \
-slowSpecThreshold=240 \
-race \
-cover \
-coverprofile=coverprofile \
-outputdir=build/coverage \
-trace \
internal/... \
pkg/...
[1588842940] BuildRun Suite - 10 specs - 4 nodes •••••••••• SUCCESS! 570.1907ms 
[1588842940] Build Suite - 8 specs - 4 nodes •••••••• SUCCESS! 885.5793ms 
[1588842940] ClusterBuildStrategy Suite - 1 specs - 4 nodes • SUCCESS! 106.3964ms 
[1588842940] BuildStrategy Suite - 1 specs - 4 nodes • SUCCESS! 139.0276ms 
[1588842940] Controllers Suite - 0 specs - 4 nodes  SUCCESS! …
```

Report proper code coverage

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go

**Migrate the `generate_taskrun_test.go` to a ginkgo setup**
All test cases in `generate_taskrun_test.go` are rewritten into ginkgo.
All unit-tests under pkg are passing:
```
build chinchen$ GO111MODULE=on ginkgo pkg/...
[1588802605] Controllers Suite - 0/0 specs  SUCCESS! 220.4µs PASS
[1588802605] Build Suite - 8/8 specs •••••••• SUCCESS! 271.768µs PASS
[1588802605] BuildRun Suite - 21/21 specs ••••••••••••••••••••• SUCCESS! 1.386822ms PASS
```

Migrate taskrun tests to ginkgo

---

Makefile

fixes issue #198 
```
➜  build git:(fix-make-local) ✗ make local
hack/crd.sh uninstall
clusterrole.rbac.authorization.k8s.io "build-operator" deleted
clusterrolebinding.rbac.authorization.k8s.io "build-operator" deleted
serviceaccount "build-operator" deleted
deployment.apps "build-operator" deleted
customresourcedefinition.apiextensions.k8s.io "buildstrategies.build.dev" deleted
customresourcedefinition.apiextensions.k8s.io "clusterbuildstrategies.build.dev" deleted
customresourcedefinition.apiextensions.k8s.io "builds.build.dev" deleted
customresourcedefinition.apiextensions.k8s.io "buildruns.build.dev" deleted
Error from server (NotFound): error when deleting "samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml": the server could not find the requested resource …
```

Updates Makefile to fix make local target

---

HACK.md
Makefile
test/e2e/e2e_suite_test.go
test/e2e/ginkgo_operator-sdk.go
test/e2e/validators.go

Resolves https://github.com/redhat-developer/build/issues/194
I introduced a set of environment variables that are explained in the HACK.MD modification as well as in the above mentioned issue. The changes allow to run the e2e tests in an environment where the operator is already running, build strategies are already configured and where Tekton objects are not accessible for the user.

Make e2e tests configurable

---

samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml

While I was running the e2e tests, `heroku` failed for because of the undefined `--helpers` flag:
```
~ chinchen$ kubectl -n default logs buildpacks-v3-heroku-btc92-pod-w5gwc -c step-step-export
flag provided but not defined: -helpers
```
The flag probably was removed on the newer version of heroku image.
https://hub.docker.com/r/heroku/buildpacks/tags
Therefore, I removed the `--helpers` flag in yaml files respectively.

BUG: Fix the errors with heroku

---

Makefile
docs/build.md
go.mod
pkg/apis/build/v1alpha1/build_types.go
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
samples/build/build_buildpacks-v3_cr.yaml
samples/build/build_kaniko_cr.yaml
test/catalog.go
test/data/build_kaniko_cr_advanced_dockerfile.yaml
test/e2e/e2e_test.go
test/e2e/validators.go

- Add new `metadata.annotations[build.build.dev/buildRunDeletion]` 
- Add annotation check in Build Update check
- Add an ew finalizer in Build
- Remove the related BuildRun when deleting the Build
- Add test to verify the logic in build controller ut
- Add deletion verification in e2e tests
This PR is for the feature: https://github.com/redhat-developer/build/issues/94

Add BuildRun deletion when delete the Build

---

samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

Use kaniko to build s2i's Dockerfile instead of buildah.
This helps us avoid running a privileged container. Until we fix https://github.com/redhat-developer/build/issues/134, we should not be using `buildah`.
In case of kaniko, we are good with:
```
securityContext:
runAsUser: 0
allowPrivilegeEscalation: false
```
`runAsUser: 0` is needed primarily because the generated Dockerfile has a `User root` directive.
I've tested this on OpenShift 4.4

Use kaniko to build s2i's Dockerfile

---

docs/buildrun.md

Just for clarify image push `credential ` is not in the scope of override `output` field defined in build spec. Now, we just override output imageURL, don't include credential.

Enhance buildRun doc

---

samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

Change kaniko BuildStrategy from latest image to v0.19.0, because latest kaniko image has performance issue.

Change kaniko BuildStrategy from latest image to v0.19.0

---

cmd/manager/main.go

Fix issue: https://github.com/redhat-developer/build/issues/232
By investigating, I think we should use [`leader-for-lease`](https://docs.openshift.com/container-platform/4.2/operators/operator_sdk/osdk-leader-election.html#osdk-leader-with-lease-election_osdk-leader-election) operator-sdk controller HA solution instead of [`leader-for-life`](https://docs.openshift.com/container-platform/4.2/operators/operator_sdk/osdk-leader-election.html#osdk-leader-for-life-election_osdk-leader-election). More details, pls refer to:https://github.com/redhat-developer/build/issues/232
By default, `LeaseDuration` is 15s, `RenewDeadline` is 10s and `RetryPeriod` is 2s. We can [change the default value](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/manager#Options) in the future. But, …

Change controller HA to leader-for-lease mode

---

test/e2e/e2e_test.go
test/e2e/samples.go

Related issue: https://github.com/redhat-developer/build/issues/230
Currently, if our e2e test failed in travis, then it will only report below error:
```
Timed out after 550.000s.
BuildRun did not succeed
Expected
<v1.ConditionStatus>: False
to equal
<v1.ConditionStatus>: True
```
We can't get some useful information for debugging. And we also can't access the kind cluster to debug, this is inconvenient.
So this PR will print the log of builrRun when this buildRun failed. Then we can judge what's wrong with the buildRun.  
For example, if there is a failed case for `buildpacks-v3-heroku-namespaced` buildRun, then travis will output each container's log for the buildRun pod, like below:
```
For a Kubernetes cluster with Tekton and build installed when a heroku Buildpacks build is defined …
```

Print the log of failed buildRun pod for debugging

---

OWNERS

In this project, automatically two reviewers get assigned from the OWNERS file. In the two months that I am working on this project, I have not seen any review comments from the users `baijum` and `Avni-Sharma`. I am therefore proposing to remove them for the time being to get more meaningful auto-assigned reviewers.

Remove inactive users

---

docs/proposals/README.md
docs/proposals/guidelines/proposal-template.md

Port of the OKD enhancement proposal process [1] for the `build` project.
Notable adjustments made for `build`:
* References to "domain" removed.
* Updated directory tree structure.
* Added links to the README with links to the KEP and OKD enhancement processes.
[1] https://github.com/openshift/enhancements/blob/master/guidelines/README.md

Enhancement Proposal Process

---

test/e2e/e2e_test.go

Fix issue: https://github.com/redhat-developer/build/issues/256
Current ruby runtime for paketo looks like is in development and unstable, so we need to remove it first. Otherwise our travis alway failed because can't detect ruby buildpack.
```
{"level":"info","ts":1591328779.063402,"caller":"git/git.go:133","msg":"Successfully initialized and updated submodules in path /workspace/source"}
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
2020/06/05 03:46:20 Skipping step because a previous step failed
2020/06/05 03:46:21 Skipping step because a previous step failed
2020/06/05 03:46:21 Skipping step because a previous step failed
2020/06/05 03:46:22 Skipping step because a …
```

remove ruby e2e test

---

deploy/crds/build.dev_buildstrategies_crd.yaml
pkg/apis/build/v1alpha1/buildstrategy_types.go

Related to #228 
The namespaced BuildStrategy was defining a `VERSION` column
that the ClusterBuildStrategy didn´t have. Also, this `VERSION`
column didn´t display anything.
This commit removes the kubebuilder annotation from the
buildstrategy_types.go and regenerate the proper CRD for this resource.
This is how the strategies CRDs looked before:
```sh
$ k -n test-build get bs
NAME            VERSION
buildpacks-v3
$ k -n test-build get cbs
NAME                     AGE
buildah                  6m11s
buildpacks-v3            6m24s
buildpacks-v3-heroku     6m26s
kaniko                   6m8s
source-to-image          6m6s
source-to-image-redhat   6m3s
```
this is how they look with this PR:
```sh
$ k -n test-build get bs
NAME            AGE
buildpacks-v3   2m9s
$ k -n test-build get cbs
NAME …
```

Inline BuildStrategy CRDs with ClusterBuildStrategy

---

deploy/operator.yaml

- the liveness probes was added on the operator. It will help us to know when to restart the container by checking if the container is healthy or not. 
The setup args will be executed when the container starts, it is further be used for healthy check of the container.
- the readness probes will help us to know when the container is ready to receive the traffic as our definition(i.e. `initialDelaySeconds `, `periodSeconds `) in the probes.

Add liveness and readness probes on the operator

---

deploy/crds/build.dev_buildruns_crd.yaml

- Add missing spec.output declaration in the buildrun. I think
this was missing in https://github.com/redhat-developer/build/pull/233
- Add missing timeout in spec.status.buildSpec, I think this was missed
somehow after https://github.com/redhat-developer/build/pull/158 was merged.
Also, this can be reproduced by doing `operator-sdk generate crds`

Add missing changes in the generated buildRun CRD

---

HACK.md
Makefile
test/e2e/e2e_test.go
test/e2e/samples.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/modules.txt

Tests are supposed to be stable. We are not seeing this with our e2e tests. The problem is that we do not have everything under our control. We rely on external resources like the git repositories and the container registry. In addition, specifically in the Travis environment here, we are seeing instabilities that we do not see elsewhere.
I am therefore adding support for Ginkgo's `flakeAttempts` flag to the e2e tests. It was so far not possible to just set the flag because each test case creates a build and build run with a constant name. On a retry of a specific test case, the recreation of those artifacts failed because of the unique name constraint.

Support Ginkgo flakeAttempts flag

---

cmd/manager/main.go
pkg/config/config.go
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
pkg/controller/buildstrategy/buildstrategy_controller.go
pkg/controller/buildstrategy/buildstrategy_controller_test.go
pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller_test.go
pkg/controller/controller.go
pkg/ctxlog/context.go
pkg/ctxlog/log.go

Based on #247 
This PR have quite a lot of changes, none of them is a breaking change. Each commit have a good explanation, but here is a summary:
- Introduce a new package call `ctxlog`. This package will provide us with a logging implementation. This package is using the same logging as before, but it just defines common functions that can be accessed from all controllers by passing a context. Also, this package uses a proper go context implementation. We start with a parent context in `main.go` and inside each build controller we get a children context. With this context we can then pass a proper context to all the `client` calls we do to k8s during Reconciliation. Now all client calls to k8s goes with a context that have a timeout, this should ensure that calls that take too much are …

Improve logging and add proper go contexts

---

.travis.yml

Fix issue: https://github.com/redhat-developer/build/issues/241
We need to allow fast fail when a job failed in travis.
Related discussion on travis side: https://github.com/travis-ci/travis-ci/issues/1066
Look like, there is no a travis key can be used to set fast fail mode. So I refer to [this comment](https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-32415710) and [this one](https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-479594195) to make our travis can be exited right away once a travis job failed.

Allow fast fail when a travis job failed

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
pkg/controller/buildrun/credentials.go
pkg/controller/buildrun/credentials_test.go
test/catalog.go

Fixes #203 
The pull request changes the code in the BuildRun controller's `retrieveServiceAccount` function to do a `CreateOrUpdate` to create the service account. This fixes the issue of a reconciliation successfully creating the service account but failing to create the task run. The following reconciliation then tried to create the service account again and failed.
I added a temporary error into the buildrun controller to test my fix. The first buildrun reconcile leads to this log message:
```log
{"level":"info","ts":1591343891.9695,"logger":"controller_buildrun","msg":"Automatic generation of service account","ServiceAccount":"kaniko-timeout-sa","Operation":"created"}
```
Further reconciles look like this (note the operation returned by `CreateOrUpdate` is `unchanged`):
```log …
```

Reuse generated service account

---

samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml

Fixes #266
Let me explain what I am doing here. With kaniko 0.20, changes got introduced that I started to outline here: https://github.com/redhat-developer/build/issues/238#issue-628325976. Further details are that Ffom Kaniko 0.19 to 0.20 there was commit https://github.com/GoogleContainerTools/kaniko/commit/7b51aec5d955e9bc642943a4b8672575600782e7. It changes the dependency on github.com/google/go-containerregistry from v0.0.0-20191218175032-34fb8ff33bed to v0.0.0-20200313165449-955bf358a3d8.
In go-containerregistry, there is commit https://github.com/google/go-containerregistry/commit/a1fca010ae9cbeb2132652e304335b04f3368455. In this commit, the dependency on k8s.io/kubernetes (includes k8s.io/kubernetes/pkg/credentialprovider) v1.11.10 was removed. Instead a dependency on …

Upgrade to latest Kaniko version with workaround for AWS client delay

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
test/e2e/e2e_test.go
test/e2e/validators.go

Fixes #264
Adding logic to the build run controller that automatically deletes the generated services account on finish of the buildrun. I'd like to have feedback on https://github.com/SaschaSchwarze0/build/blob/sascha-264-delete-generated-sa/pkg/controller/buildrun/buildrun_controller.go#L174-L177 where I decided to ignore an error during the service account deletion.
The e2e test change looks massive, so let me explain it here: I added a function `validateServiceAccountDeletion` that runs after every test case and validates that the generated service account was deleted depending on the buildrun status. For this, I had to move the the declaration of the `br`and `err` variables. The rename from `testId` to `testID` is a go-lint suggestion.

Delete generated service account on end of the build run

---

deploy/operator.yaml

- The container’s status alive or failed can be detect by liveness probes, sending an HTTP reuqest to the server.
- And the readliness ensure us any request would not reach the container which is not ready for it.

Fix the issue of args and command for probes

---

cmd/manager/main.go
deploy/operator.yaml

When running in HA mode, the previous localhost:8383/metrics
endpoint was not available for pods that are not leaders. This
end-up in pods having a CrashLoopBackOff  STATUS.
In order to fix this, we are introducing a different approach on
how we check the Readiness/Liveness by using the operator-sdk ready
package.
Also, we test this manually, it should be working when HA is enabled.
Signed-off-by: EEE <encalada@de.ibm.com>

Fix readiness/liveness probe when HA is enable

---

docs/build.md
docs/buildstrategies.md

Because [previous PR](https://github.com/redhat-developer/build/pull/157) has hard code builder image in build spec for buildpack, so this PR updates the document about it.
Now, only `source-to-image` buildStrategy requires `builder.image` parameter in build spec.

Update documents because hard code builder image for buildpack

---

docs/build.md
docs/buildstrategies.md

While looking through https://github.com/redhat-developer/build/pull/277, I noticed a couple of incorrect things in our documentation.
- links from build.md to the build strategies were leading to 404
- the source-to-image strategy was changed to use Kaniko for the Docker build but the doc still mentioned buildah
- the source-to-image strategy was documented to _typically_ requires a builder image, correct is that it requires it always.
- some minor grammatical and formatting things

Correct documentation

---

vendor/github.com/operator-framework/operator-sdk/pkg/ready/ready.go
vendor/modules.txt

@routerhan and myself introduced the `ready` package for the readiness/liveness probes but we didnt update the vendor. This fix it, a small change.

Update vendor with ready pkg

---

samples/build/build_buildpacks-v3-heroku_cr.yaml
samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
samples/build/build_buildpacks-v3_cr.yaml
samples/build/build_buildpacks-v3_namespaced_cr.yaml
test/data/build_buildpacks-v3-heroku_cr_private_github.yaml
test/data/build_buildpacks-v3_cr_private_github.yaml
test/data/build_buildpacks-v3_golang_cr.yaml
test/data/build_buildpacks-v3_java_cr.yaml
test/data/build_buildpacks-v3_php_cr.yaml
test/data/build_buildpacks-v3_ruby_cr.yaml

I think mainly for buildpacks, where we have many containers, we might have not pay attention on the container resources implications.
Here are some facts:
- By not defining container limits/requests, containers are able to
use as much as they need for cpu and memory, leading to
OOM kill or CPU throttle
- Travis have by default what I think is, 4G RAM and 4.5MB memory, with
2 cores.
- Limits are fine to be 500m CPU, 1Gi memory. I dont think we can hit any
of the issues above with this limits. Maybe only slower tests.
Also, pls keep in mind that when setting limits without requests, k8s will
default the request to the limits.
I enjoy reading the following:
- https://sysdig.com/blog/kubernetes-limits-requests/
- https://medium.com/@betz.mark/understanding-resource-limits-in-kubernetes-cpu-ti …

This is aiming to help to mitigate performance issues in travis

---

pkg/controller/build/build_controller.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/credentials.go
pkg/controller/buildrun/credentials_test.go
pkg/controller/buildstrategy/buildstrategy_controller.go
pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
pkg/ctxlog/context.go
pkg/ctxlog/log.go

For #247 
Most of the log statements should contain a message, a namespace, an object name at least.
- For INFO level, we try to keep it on a minimum.
- For DEBUG level, we try to add those on specific places, e.g. beginning/end of a function(e.g. Reconcile one). Or places we know we would be helpful later for debugging.
_Note_: When we return an error, we are not logging that, the reason goes back to what is stated in https://dave.cheney.net/2015/11/05/lets-talk-about-logging, we basically just return the error to the parent call . The controller-runtime will send the error to STDOUT together with a stacktrace. This should be enough.
We also fix a bad practice implemented in the ctxlog logger package. We remove a pointer we use to have for the logger interface, it was basically not …

Adding some enhancements on the logging we define.

---

cmd/manager/main.go
docs/metrics.md
go.mod
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/buildrun_controller.go
pkg/metrics/metrics.go
pkg/metrics/metrics_suite_test.go
pkg/metrics/metrics_test.go
test/catalog.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
vendor/modules.txt

Based in our controller implementations, I add 6 basic custom metrics:
- controller up status
- build count
- buildrun count
- buildrun establish time
- buildrun execution time
- buildrun execution time histogram
I also verified after the controller is retarted and the metrics is cleaned up, the later metrics can still show correctly.
I also add ut for metrics.
Here is the example metrics show from Sysdig:

Add basic custom metrics support

---

samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

Fixing the camel-case capitalization on a couple places. In [core-v1/Container](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core) it species `workingDir` instead of `workingdir`.

Working Directory Attribute

---

samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml

Kaniko released [v0.24.0](https://github.com/GoogleContainerTools/kaniko/releases/tag/v0.24.0) last week. I am updating the cluster build strategy to use the new version. I am also changing the argument set to use `--snapshotMode=redo`. Kaniko v0.24.0 introduces two new performance-related command line flags that are described here: [Kaniko Performance Testing](https://github.com/GoogleContainerTools/kaniko/issues/1305#issue-634806071).
We assessed this internally, copying my assessment here:
> The problem that the enhancement address go directly against the biggest issue that Kaniko has: Kaniko works by extracting the `FROM` image specified in the Dockerfile into its (otherwise empty) root file system. Then it does through all the commands in the Dockerfile and performs them. Some of …

Update Kaniko to 0.24.0, use new snapshotMode

---

pkg/controller/buildrun/buildrun_controller.go

This is a bug which introduced by the new custom metric feature.
In some special cases, the build controller cannot get `buildRun.Status.StartTime.Time` then report **nil pointer** error:
**How to reproduce:**
- Start build controller
- Run some buildrun tests parallel
- Stop the build controller pod to stop service
- Some of the buildruns already create taskrun, but don't update the `buildRun.Status.StartTime.Time` correctly and the taskrun is running
- After several minutes, the taskrun is completed
- Start the build controller
- There is no StartTime in the buildrun status:
```
kubectl get br perf-br-project3712-1 -n 83ef14eb-10ad -oyaml
apiVersion: build.dev/v1alpha1
kind: BuildRun
metadata:
generation: 2
labels:
build.build.dev/generation: "1"
build.build.dev/name: …
```

Fix the nil pointer error when builder controller is restarted

---

test/e2e/e2e_test.go

Community has supported ruby buildpack, now. Pls refer to [here](https://github.com/paketo-community/ruby/issues/59#issuecomment-654869593). So we need to bring ruby e2e test back.
Also I have verified locally, ruby apps can be build successfully.
```
root@xxx-0:~/gopath/src/github.com/cf-acceptance-tests/assets# pack build us.icr.io/zoe_nmaespace/ruby-test  --builder gcr.io/paketo-buildpacks/builder:latest --path=dora/
latest: Pulling from paketo-buildpacks/builder
11f6db2e1cf8: Already exists 
5fc72bd1c95d: Already exists 
4c1a0023eeb2: Already exists 
efb025c4d658: Pulling fs layer 
... ...
... ....
89732bc75041: Pull complete 
Digest: sha256:e8416da7d2e1a8141af0768ca01a300b497d475d2d4843b5964443babd4b5362
Status: Downloaded newer image for gcr.io/paketo-buildpacks/builder:latest …
```

Bring ruby e2e test back

---

Makefile
docs/metrics.md
pkg/config/config.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

The `build_buildrun_establish_duration_seconds` histogram metric used the following buckets: 0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5.
Two issues exist with that:
1. Values with .5 cannot exist because k8s timestamps have no milliseconds. Those are therefore not of value.
2. Longer durations cannot be differentiated which makes it impossible to define reasonable alerts.
The new buckets for the metric are: 0, 1, 2, 3, 5, 7, 10, 15, 20, 30. The number of buckets is unchanged, but the longer durations can be better monitored.
In addition, I am changing the metrics implementation to get the buckets from the configuration and I allow environment variables to overwrite the defaults.
The downside of that is that the metrics package cannot anymore instantiate the histograms statically but requires …

Refine build_buildrun_establish_duration_seconds buckets and make buckets configurable

---

deploy/crds/build.dev_buildstrategies_crd.yaml
deploy/crds/build.dev_clusterbuildstrategies_crd.yaml

* Without this change, our CRDs won't work for kubernetes 1.18 , see https://github.com/redhat-developer/build/issues/284
* Till we find a better solution, we'll have to manually modify ( or have a `sed` script ) to make our CRDs work with kube 1.18 
Noticed that a lot of projects have done this.
Ref https://github.com/operator-framework/operator-sdk/issues/3235
```
$ oc apply -f deploy/crds/build.dev_buildstrategies_crd.yaml 
The CustomResourceDefinition "buildstrategies.build.dev" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[buildSteps].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```
```
oc apply -f …
```

Drop containers `protocol` from "required"

---

deploy/namespace.yaml
deploy/operator.yaml
deploy/service_account.yaml
docs/development/deploying.md
hack/crd.sh

Fix Build operator resources:
- The SA YAML was missing the namespace, same case for the Deployment YAML
Add docs around how to deploy a pod running the Build:
- I already struggle to explain this to two different people, I think
is always useful to allow users to get a pod running this operator,
therefore adding docs around it.

Minor fixes around our k8s resources

---

pkg/controller/buildrun/buildrun_controller.go

Fix for issue #320
A TaskRun can jump from having no Conditions into
a Condition with any Reason. Usually it will be alway
get a PENDING Reason, but is not always the case.
I tested this manually. We need to improve our test cases for the integration with Tekton TaskRun, but we would first need to do some work around it(#322). Therefore Im ok with this PR not having a related test case. Just for the record:
```sh
$ k -n test-build get tr -w
NAME                     SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME
kaniko-golang-buildrun
kaniko-golang-buildrun
kaniko-golang-buildrun   False       CouldntGetTask   0s
kaniko-golang-buildrun   False       CouldntGetTask   0s
$ k -n test-build get br -w
NAME                     SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME …
```

Fix for issue #320

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
test/catalog.go

Fixes #301 
- The buildrun controller is able to check the build's registered status.
If `build.Status.Registered` is false, it should stop working on further service account and taskrun.
- To avoid `Unexpected Error` of other unittest cases, the mocked `DefultBuild` has the `build.Registered` set to be True.
- Also, for testing the case that `build.Registered` is false, the mocked `DefaultBuildWithFalseRegistered` is created in catalog.go

Stop working on the buildrun if build.registered=false

---

docs/build.md

I am adding a sentence to the documentation about the `KANIKO_CONTAINER_IMAGE` environment variable that was added for the runtime image support, [Runtime Image Support #263](https://github.com/redhat-developer/build/pull/263).

Add documentation for KANIKO_CONTAINER_IMAGE env var

---

pkg/controller/build/build_controller.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go
test/catalog.go

Similar to how a Deployment resource generates names for pods, we
should stick to an auto-generated name for TaskRuns. This will
avoid issues like #315.
We use to have the auto-generated name before, but it was modified
with PR #313
With different names between BuildRuns and TaskRun, some code refactoring
on the buildrun controller was required to preserve the improvements done
in PR #313. Also, unit-tests were improved to deal with different Reconcile
request on the BuildRun controller, depending if they come from a BuildRun
object or a TaskRun object event.

Rollback to use a generated name for each TaskRun

---

cmd/manager/main.go

Fix issue: https://github.com/redhat-developer/build/issues/333
Now, we are using `leader-for-life` and `leader-for-lease`. But we just need `leader-for-lease` HA mode for operator. I have verified the situation when we delete below part:
```
err = leader.Become(ctx, "build-operator-lock")
if err != nil {
ctxlog.Error(ctx, err, "")
os.Exit(1)
}
```
Once the previous leader is not ready, such as `terminating` or something, other inactive pod will take over the leader.
I delete above part, build a new image `us.icr.io/coligo-serving/operator` and consume it. Everything works as my expected, below is the testing process:
- Check the leader 
```
root@jordan-0:/build# k get pod -n source-to-image -o wide
kubectl get pod -n source-to-image -o wide
NAME                              READY …
```

Remove leader-for-life HA mode

---

Makefile
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
test/catalog.go

Fixes #329 
I changed the buildrun controller to retrieve the build only when it is in the code path to create the task run. This code path is written to be idempotent = if anything in this code path fails, then another reconciliation will not fail if parts of it (setting the labels or the buildSpec in the status) is done already.
Imo the code is now also more accurate because the build labels and buildspec in the status are set to the values that match those that are used to create the taskrun. The old code potentially set the fields to values that were not used to create the taskrun.
There was a test case already that verifies that the buildrun would fail if the build is not there even if the task run was already created. I changed this to reflect the new behavior.
I also noticed that …

Retrieve build in buildrun controller only to create taskrun

---

HACK.md
Makefile
test/e2e/validators.go

When running the e2e tests on slow systems (like my machine) I sometimes get timeouts for some e2e test cases (specifically because it is taking longer to download container images as my internet connection is not rocket fast).
Beside that we run a few of the e2e tests also to continuously verify the availability of our service. And then those tests sometimes fail because the overall system load makes things slower.
I am adding an environment variable that allows to multiply the

Make timeouts within e2e tests configurable

---

docs/proposals/local-registry-image-specs.md

[KEP 1755](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry) provides an official convention for clusters to declare the presence of an internal image registry. This proposal aims to take advantage of declared local image registries, and let application developers simplify how they declare image pull specs. This may also help `Build` objects be portable across clusters.

Proposal: Local Registry Image Specs

---

README.md

Add new badges for license and go.dev reference
Fix Readme, while it included a reference to "jib" tool that we do not use.

Fix badge for travis and add new ones

---

samples/buildrun/buildrun_buildah_cr.yaml
samples/buildrun/buildrun_buildpacks-v3-heroku_cr.yaml
samples/buildrun/buildrun_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildrun/buildrun_buildpacks-v3_cr.yaml
samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
test/data/buildrun_buildpacks-v3_nodejs_runtime-image_cr.yaml

Having the `spec.serviceAccount.name` while `spec.serviceAccount.generate` is set to true
is confusing in the samples, while the name is not used anywhere. And a autogenerated name will be used for
a service account creation.

Remove reference to a service account on auto-generation

---

test/e2e/validators.go

We just had this error in our regular e2e test runs:
```
Error retrieving a buildRun
Unexpected error:
<*errors.StatusError | 0xc000813ea0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "rpc error: code = Unavailable desc = transport is closing",
Reason: "",
Details: nil,
Code: 500,
},
}
rpc error: code = Unavailable desc = transport is closing
occurred
/build/test/e2e/validators.go:233
Full Stack Trace
github.com/shipwright-io/build/test/e2e.validateBuildRunToSucceed.func4(0x0, 0x0)
/build/test/e2e/validators.go:233 +0x18e
```
I am marking this error retryable.

Retry RPC error

---

pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go
test/buildstrategy_samples.go

During the PR: https://github.com/shipwright-io/build/commit/10386f9c65e4689e2d34886b1926bc49e7ad64ad#diff-c8bae8bebf9ceb3609b947afd6c4af05
We switch the `pathContext` parameter to `contextDir`
But we still have some parameter names or a test code still using `pathContext` which makes people confusing.
Let us remove the old `pathContext` and make the code clear.

Fix PathContext to ContextDir

---

.travis.yml
Makefile
hack/release.sh

Creating an initial image release pipeline for the shipwright operator.
This makes use of the travis docker service to build the image and push
it to quay.io when release tags are made and PRs merge in the main
branch.
In the future we will want to dogfood our own operator and use
Shipwright to build and push the image.

Initial Release Pipeline

---

hack/generate-copyright.sh

The `find` calls require the usage of the "dot" to work, otherwise
macOS users will get the following error:
```
find: illegal option -- n
```
Also, I fixed some empty spaces added when embedding the
the license headers into the files.
No issue related, I found this while working in another PR. I also test this changes in an ubuntu env, they work fine.

Ensure the hack/generate-copyright.sh works in macOS envs

---

docs/metrics.md
pkg/config/config.go
pkg/controller/buildrun/buildrun_controller.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

When building, a couple of Kubernetes resources are created to run the
respective build strategy to compile the app. Depending on the system
load or utilisation, it may take more or less time to create the
resources to kick the run. The time to ramp-up a specific part of the
build can be useful for monitoring and alerting.
Add three ramp-up duration metrics to `build`:
- between buildrun creation and taskrun creation (buildrun ramp-up)
- between taskrun creation and taskrun pod creation (taskrun ramp-up)
- between pod creation and last init container completion (pod ramp-up)
Note: The ramp-up durations usually range between zero (not measurable)
and one second. Therefore, the default bucket range is simply counting
up from zero to ten seconds.

Add ramp-up duration metrics to build

---

docs/metrics.md
pkg/config/config.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

Fixes #367 
I am introducing an environment variable configuration to allow selective disabling of histogram labels.
I also noticed, that the recently added new metrics were not working and fixed the copy/paste mistake. Sample output of `/metrics` for a single buildrun with `PROMETHEUS_HISTOGRAM_DISABLED_LABELS=namespace`:
```
build_buildrun_completion_duration_seconds_bucket{buildstrategy="kaniko",le="50"} 1
build_buildrun_completion_duration_seconds_bucket{buildstrategy="kaniko",le="100"} 1
build_buildrun_completion_duration_seconds_bucket{buildstrategy="kaniko",le="150"} 1
build_buildrun_completion_duration_seconds_bucket{buildstrategy="kaniko",le="200"} 1
build_buildrun_completion_duration_seconds_bucket{buildstrategy="kaniko",le="250"} 1 …
```

Enable label customization for histograms

---

CONTRIBUTING.md
code-of-conduct.md
docs/development/local_development.md

Add code of conduct doc
- We reference to the Kubernetes community one, in the same way
as most of the Kubernetes existing project 
Add contributing doc
- Trying to add some initial words on future contributions. I think we
still need to generate more docs for this, but so far is good to have
this as an initial step.

Enhance docs by adding contributing and code-of-conduct files

---

README.md

The v0.1.0  was missing on the table. This follows the approach used by the Tekton folks, see https://github.com/tektoncd/pipeline/tree/v0.16.2#read-the-docs

Update docs version

---

.gitattributes

Based on https://docs.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github
this should be useful to keep certain files from displaying in diffs by default, or counting
toward the repository language.
This should help when PRs with vendor folders or generated clients are adding/removing changes.

Enable linguist for our build repo

---

pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go

While playing around, I noticed that the source secret is not validated. The code then showed me that only the output secret is validated. I added the validation for the source secret as well as the image builder secret.

Validate all referenced secrets

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
pkg/metrics/metrics.go
test/catalog.go

When generating the rampup metrics, we needed to validate for nil
pointers in order to avoid some panic() scenarios. Adding a test
case for this validation.
When metrics are not used, some variables are not initialized, leading
to panic() scenarios when using them later in the reconciliation of the
BuildRun controller. Adding some if conditionals to validate nils.

Validate nil pointer exceptions during BuildRun Reconcile

---

docs/proposals/shipwright-website.md

Proposal to run a Shipwright website via Hugo and GitHub Pages. This
will host project documentation, release notes, and blog entries.
Related to #388

Website Proposal

---

pkg/config/config.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml

Updating Kaniko to their 1.0.0 version. Also adding `--oci-layout-path` argument to the strategy. This causes Kaniko to write a JSON file with the image information which is picked up by the `step-image-digest-exporter` step of Tekton. See [--oci-layout-path](https://github.com/GoogleContainerTools/kaniko/blob/82f5ec961246bb1aca003f7b16089d96e3de758b/README.md#--oci-layout-path).
It will cause this warning no to appear anymore: `{"level":"info","ts":1600437444.6745567,"logger":"fallback-logger","caller":"imagedigestexporter/main.go:59","msg":"No index.json found for: image","commit":"20da4cf"}`
The image sha will then be in the taskrun status. We can pick that up at some point and put it into the buildrun status.

Update to Kaniko 1.0

---

test/e2e/e2e_test.go
test/e2e/samples.go
test/e2e/validators.go

I consolidated the `AfterEach` for the e2e tests. I re-implemented the method that is printing debug information in case of a test case failure to print the full build, buildrun, taskrun and pod.
We recently had a failure in our continuous tests where there was a containerd failure to get one container within a build run's pod up. The test case failed because the build run status was still Unknown. As the test framework cleans up the build run, it is hard to determine the root cause. There might be a problem on how Tekton translates the pod's status into its status and/or an issue how we interpret the task run's status.
While, I will still try to investigate this, I am adding more debug information when a test case fails.

Enhance debug information logging in case of an error

---

docs/buildstrategies.md
docs/proposals/buildstrategy-steps-resources.md
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

Fix #404 
Based on a discussion in [paketo buildpacks slack](https://paketobuildpacks.slack.com/archives/CULAS8ACD/p1600670275004100), it seems the Google Container Registry will not be used anymore some time in the near future. They recommend switching to DockerHub, where the same images are hosted.
Replace all occurrences of `gcr.io/paketo-buildpacks` with the DockerHub alternative `docker.io/paketobuildpacks`.
Update link to DockerHub images list.

Switch from GCR to DockerHub

---

docs/buildstrategies.md
pkg/controller/buildrun/runtime_image.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

We had a customer problem when build a source code repo from: https://github.com/nheidloff/code-with-quarkus/blob/master/src/main/docker/Dockerfile.multistage
This build fail at the step `microdnf update`:
It will fail at step-step-build-and-push step, and the final error is:
```
...
Cleanup: libgcc;8.3.1-4.5.el8;x86_64;installed
Updating: (null)
Updating: (null)
error: Error -1 running transaction
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```
Finally, I found the root cause. We didn't enable a Linux Capability `setfcap` in the Kaniko build strategy, without this permission, some system installations cannot work. I added it and test, the build works for me:
``` …
```

Add SETFCAP Linux capability for Kaniko buildstrategy

---

pkg/config/config.go
pkg/config/config_suite_test.go
pkg/config/config_test.go

Over time, there was some code duplication accumulated for overriding
configuration settings using an environment variable.
Introduce one common function to do the float slice override.
Combine `os.Getenv` and `if` case into one line, where possible.
Introduce basic Ginkgo test suite.
Add test cases for the currently possible environment overrides.

Refactor config environment variable override code

---

docs/buildstrategies.md
docs/proposals/buildstrategy-steps-resources.md
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

This is a follow up from https://github.com/shipwright-io/build/pull/406
I tested if the container images that we build with Paketo can be deployed
with the bionic stack via [test branch](https://github.com/qu1queee/build/commit/6ff4ece927e9d030fa57bcacff5a437c0aea14e5).
Moving from `builder:latest` to `builder:full` means that we are gonna stop
running on top of a cflinuxfs3 stack in favor of a bionic stack.
Paketo community mentioned that the bionic stack have parity with cflinuxfs3,
therefore this is a safe change, plus the deployment validations I did.

Move to Paketo `full` tag builder image

---

pkg/controller/buildrun/runtime_image.go
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

In my recent [Kaniko-related PR](https://github.com/shipwright-io/build/pull/401) where I upleveled it to v1.0.0, I forgot the s2i build strategy and also missed to add the `--oci-layout-path` argument to the runtime image support. Correcting this with this PR.

Bring Kaniko version and arguments in sync

---

cmd/manager/main.go
deploy/operator.yaml
docs/configuration.md
pkg/config/config.go
pkg/config/config_test.go

In case the build operator needs to be started with very specific leader
lease duration configuration, there is currently no way to configure it.
Introduce new section in build configuration that contains some of the
manager options to be configurable and passed through to the manager.
Pass new section values as-is into the manager options for the build
operator setup. Any `nil` value will result in the default value.
Add four new environment variables to override these settings:
- `BUILD_OPERATOR_LEADER_ELECTION_NAMESPACE`
- `BUILD_OPERATOR_LEASE_DURATION`
- `BUILD_OPERATOR_RENEW_DEADLINE`
- `BUILD_OPERATOR_RETRY_PERIOD`
_Please note:_ All duration based environment variables use the time duration
parse function, so they expect an input like `42s`.
This should fix #414.

Make build operator leader durations configurable 

---

docs/buildstrategies.md
pkg/config/config.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

Upgrade Kaniko builder image to v1.2.0 in all build strategies and document.

Upgrade Kaniko builder image to v1.2.0

---

test/data/build_buildpacks-v3_nodejs_runtime-image_cr.yaml

In buildpacks build strategy, we have removed the support for the builder image. I am removing the builder image from one test build definition where we forgot to remove it.

Remove unused builder image

---

test/e2e/e2e_suite_test.go
test/e2e/e2e_test.go
test/e2e/samples.go
test/e2e/validators.go

Files without the `_test.go` suffix are compiled as "normal" go code in
IDEs like VSCode. This can lead to spurious compile errors if the normal
code references variables in test code.
Updating the library code in `samples.go` and `validators.go` to accept
test variables as arguments in function calls. Wired test arguments
through to library functions.

Wire test variables through e2e lib code

---

pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
test/integration/build_to_buildruns_test.go

I am providing the error message list for our service.
I found most of the error messages start with a lower case letter, but few of them forget to correct the format, like:
`Updating predicated passed, the annotation was modified.`
So I format all related error messages in the controller as same message style: 
Change error messages start with a lower case letter

Change error messages start with a lower case letter

---

test/e2e/validators.go

In the e2e tests, we have an [Eventually block in validators.go](https://github.com/shipwright-io/build/blob/50419d764be4313abb8905dcf322cbc82cc2bd9e/test/e2e/validators.go#L193-L199) which waits for a build run to be succeeded (and another one waits for it to be failed). We at the moment have no early exit in there. This means that a failed build run will cause the full timeout duration to be taken. As this is quite long and can be made even longer using the timeout multiplier, test timeouts can occur. We are seeing a Ginkgo node timeout for time to time in our regular tests:
```
-------------------------------------------------------------------
|                                                                   |
|  Ginkgo timed out waiting for all parallel nodes to report back!  |
| …
```

Early exit Eventually block if target condition cannot be reached any more

---

docs/build.md
go.mod
pkg/apis/build/v1alpha1/build_types.go
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
test/catalog.go
test/e2e/e2e_test.go
test/e2e/validators.go
test/integration/build_to_buildruns_test.go
test/integration/utils/builds.go

Fixes #324 
This PR is the continuation of https://github.com/shipwright-io/build/pull/371 . I addressed all concerns there into this PR, and preserve @routerhan commits.
This PR replaces the finalizers approach we have in the Build -> BuildRun in favour of OwnerReferences for the same resources, aligning to the same approach as we have between BuildRuns -> TaskRuns. The PR have one commit for fixing go linters I found by using `staticcheck ./...`(I couldn´t avoid fixing this now)
@zhangtbj @HeavyWombat for your information:
_Note_: When dealing with OwnerReferences between the Build(owner) and BuildRun(owned), both controllers `Build` and `BuildRun` plays a role on ensuring that the BuildRun gets the Ownerreference or that the OwnerReference is removed. Following scenarios to consider:
> …

Set ownerReference to build->buildrun

---

Makefile
pkg/controller/fakes/client.go
pkg/controller/fakes/manager.go
pkg/controller/fakes/status_writer.go
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

Fix issue: https://github.com/shipwright-io/build/issues/450
Now, paketo builder image is consuming lifecycle `0.9.2` version. When switch to 0.9.2, restore step failed because exec as user 1000:1000: operation not permitted.
About this issue, I discuss with community and go through changes between lifecycle `0.9.1` and `0.9.2`. Role error has been [bubbled up](https://github.com/buildpacks/lifecycle/compare/v0.9.1...v0.9.2#diff-73763e61f2242eb741045f9665ef775d854ec4f0ed00d18d6ad6518d0833f6b3R45). Before this error indeed exists, but just doesn't been thrown out. So we should specify the group ID, otherwise, each step will fail because exec as user 1000:1000: operation not permitted.
I have verified and this solution works.
Besides, below change just a revert operation for this …

Add user group ID for each buildpack step

---

test/data/build_buildpacks-v3_ruby_cr.yaml
test/data/buildrun_buildpacks-v3_ruby_cr.yaml
test/e2e/e2e_test.go

Fix issue: https://github.com/shipwright-io/build/issues/458
The latest Paketo builder image has supported ruby buildpack, so we need to bring this test sample back.
This is [ruby buildpack repo](https://github.com/paketo-buildpacks/ruby), it has been moved to paketo-buildpack org from paketo-community org. 
Also in the website, they has announced supports ruby buildpack: https://paketo.io/docs/buildpacks/language-family-buildpacks/ruby/
Besides, in the slack channel, they also announced ruby buildpack has been added into paketo builder image: https://paketobuildpacks.slack.com/archives/CURGNPSTE/p1604001381008700

Bring ruby test sample back

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
pkg/metrics/metrics_test.go
test/catalog.go

Based on the suggestion by @SaschaSchwarze0, there is a gap in the metrics reporting. At the moment, the metrics are observed when the BuildRun is done. However, a metric like the BuildRun Establised Duration could be reported as soon as the BuildRun is available in the system. Furthermore, in case the BuildRun fails, the metrics for this execution are not reported at all.
_Idea for refactoring:_ Move metrics for `build-run-count`, `build-run-established`, and `build-run-rampup` to a section in `Reconcile` where the details are already available and where in theory the metrics should only be reported once.

Refactor metrics observe calls to report metrics as soon as possible

---

pkg/controller/build/build_controller.go
test/integration/build_to_buildruns_test.go
test/integration/utils/builds.go

I just noticed these output in the operator logs in a travis build https://travis-ci.org/github/shipwright-io/build/builds/740734332:
```
{"level":"info","ts":1604290243.6176696,"logger":"build.build-controller","msg":"the annotation build.build.dev/build-run-deletion was not properly defined, supported values are true or false","namespace":"default","name":"buildpacks-v3-ruby-x42q8"}
{"level":"info","ts":1604290243.617835,"logger":"build.build-controller","msg":"unexpected error during ownership reference validation","namespace":"default","name":"buildpacks-v3-ruby-x42q8","error":"the annotation build.build.dev/build-run-deletion was not properly defined, supported values are true or false"}
```
We forgot to handle the non-existing annotation in the same was as one with value `false`. I …

Handle non-existing annotation

---

pkg/apis/build/v1alpha1/build_types.go
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/apis/build/v1alpha1/buildstrategy.go
pkg/apis/build/v1alpha1/buildstrategy_types.go
pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go

When monitoring a system that uses https://github.com/shipwright-io/build, it would be helpful to make that the build work load can be identified very easy and correctly. At the moment, there is no direct way to differentiate between a buildrun that uses Kaniko or Buildpacks from a purely Kubernetes point of view by just looking at the actual task run pod.
Suggestion: Add more labels to the task run and therefore the task run pod to help to identify the respective work load.
```yaml
---
apiVersion: v1
kind: Pod
metadata:
annotations:
pipeline.tekton.dev/release: v0.17.1
creationTimestamp: "2020-11-03T15:23:07Z"
labels:
app.kubernetes.io/managed-by: tekton-pipelines
build.build.dev/generation: "1"
build.build.dev/name: test-kaniko-0
buildrun.build.dev/generation: "1" …
```

Add build strategy labels to task run

---

test/integration/buildruns_to_sa_test.go

Some Tekton distributions include a controller that adds the `pipeline`
ServiceAccount to every namespace. To facilitate integration testing,
tests should allow the `pipeline` ServiceAccount to be used if is
created outside of the integration test suite.

tests: Allow the pipeline SA to be used if it is pre-existing

---

deploy/crds/build.dev_buildstrategies_crd.yaml
deploy/crds/build.dev_clusterbuildstrategies_crd.yaml
hack/generate-fakes.sh

This is coming from me trying to cook a new PR around conditions, where I would need to update the BuildRun CRDs.
In a nutshell this PR:
- Align CRDs to be compliant with operator-sdk v0.17.0, there were some messages missing and also this PR avoids the removal of the "default: TCP" field, as requested in #299. The cmd to generate this was `$ operator-sdk generate crds --crd-version v1` . I opened https://github.com/shipwright-io/build/issues/472 as a follow up for this.
- Add fixes for fakes generation script. Ensure GO111MODULE is set to off

Fixes for CRDs and fakes generator

---

docs/metrics.md
pkg/controller/buildrun/buildrun_controller.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

For the current custom metric, we have two labels: `buildStrategy` and `namespace` and we can configure to the controller deployment choose which label we want to collect.
At the beginning, we just have two labels: `buildStrategy` and `namespace` because the metric limitation in Sysdig system, but it is not the limitation for other monitoring system and the `buildrunname` label is also important so that the end user can know more detail about each buildrun status.
By default the default label is still `buildStrategy`, but after this PR, the end user can have the capability to choose one more label in custom metric to show more detail.

Add buildrunname label for custom metric

---

test/integration/build_to_buildruns_test.go

When testing if a BuildRun is cleaned up by k8s garbage collection, we
need to get the BuildRun object before we delete the parent Build
object. Our test cluster in Travis probably didn't catch this because of
weak resource constraints. This test fails when run against a
production-grade cluster.

tests: Get BuildRun before parent Build is deleted

---

Makefile
test/e2e/validators.go

We often faced a failing travis build here which ended with:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
I am addressing this by two changes:
1. Adding a `Logf` to the `Eventually` blocks in the e2e tests to tell that something is still going on.
2. Adding the `travis_wait` for this long running command.
With that, I am getting a green build here. Unfortunately, `travis_wait` means that the log is only printed once the process is finished or times out.

Try to fix Travis timeout during e2e tests

---

test/integration/utils/environment.go

To help travis to get more time for polling for resources states. We are moving from 120s to 180s.

Increase integration test timeouts

---

test/integration/buildruns_to_taskruns_test.go
test/integration/utils/taskruns.go

Return the actual reason and then enhance the ginkgo assertions to display the actual reason in case of an error when calling this function. This is related with https://github.com/shipwright-io/build/pull/481
The above will provide users with the following insights in case of a failed assertion in ginkgo:

Enhance GetTRTillDesiredReason func

---

docs/buildstrategies.md
pkg/config/config.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

Update Kaniko builder image to the latest release `v1.3.0`: 
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.3.0

Update Kaniko builder image to v1.3.0

---

samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

FIxes #455 
The change updates the buildstrategies for Buildpacks, Heroku as well as Paketo, to use a single step for the four lifecycle phases. It is inspired by [the Tekton catalog entry for Buildpacks](https://github.com/tektoncd/catalog/blob/master/task/buildpacks/0.2/buildpacks.yaml). It uses the functionality introduced by [/cnb/lifecycle/creator](https://github.com/buildpacks/rfcs/blob/main/text/0026-lifecycle-all.md).
I am using the resources of one old step now for the merged step.
I did some performance tests. The old build strategy assigns different resources to the different steps: prepare, detect and restore got 0.1 CPU cores and 128 MiB memory; build and export received 0.5 CPU cores and 512 MiB memory. The new build strategy with just one step for the Buildpacks lifecycle …

Use single step for all four Buildpacks lifecycle phases

---

docs/buildstrategies.md
docs/proposals/buildstrategy-steps-resources.md
docs/proposals/runtime-image.md
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/buildstrategy_samples.go
test/clusterbuildstrategy_samples.go

For each Tetkon step, Tekon will add the `step-` prefix automatically. But in our all buildstrategies, we also add `step-` as prefix, so the step name has two duplicate `step-` which make end user confusing and it is hard to remember the correct step name for operation:
```
kubectl logs buildpack-nodejs-buildrun-vj4pr-pod-6h2b8
Error from server (BadRequest): 
a container name must be specified for pod buildpack-nodejs-buildrun-vj4pr-pod-6h2b8, 
choose one of: [
place-tools step-create-dir-image-slc4j 
step-git-source-source-wzfd4 
step-step-prepare 
step-step-detect 
step-step-restore 
step-step-build 
step-step-export 
step-image-digest-exporter-tt7b7
]
```
or
```
step-step-build-and-push:
Container ID:  containerd://4ed6198d1d9d776bcd50e5b4e546645c98983e7e7085a2486c24be2fa334bab7 …
```

Remove step prefix in all buildstrategy steps

---

samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml

For quay.io/buildah/stable:latest, the push cmd changed the arguments
behaviour. It now requires an IMAGE and a DESTINATION. The DESTINATION
can be ommited, and buildah would add that based on the IMAGE, by adding
a docker transport prefix (`docker://`).
Add IMAGE name to command explicitely and keep DESTINATION as-is.
Signed-off-by: Matthias Diester <matthias.diester@de.ibm.com>

Fix buildah ClusterBuildStrategy

---

docs/development/authentication.md
pkg/apis/build/v1alpha1/build_types.go
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
test/build_samples.go
test/catalog.go
test/integration/build_to_secrets_test.go
test/integration/utils/builds.go
test/integration/utils/secrets.go

Fixes #466
Worked on this together with @xiujuan95 .
This PR introduces a new Watcher on the Build Controller that watches for Secret Resources. Main things to consider:
- We have a two layer filtering before entering in the Build Controller Reconcile space, these are:
- We process events(CREATE,DELET,UPDATE) in Secrets that are only for Secrets that contain the `build.build.dev/referenced.secret: true` annotation.
- We only reconcile when the above secret is reference on any `Build` in the current namespace where the secret is.
This PR introduces an extended integration-test for this particular behaviour. 
This PR enhance the existing authentication docs, to include what users require to define in the secret and a brief explanation on why this is required.

Build watch secrets

---

test/e2e/e2e_suite_test.go
test/e2e/e2e_test.go
test/e2e/samples.go
test/e2e/validators.go

When running end to end test, in some failures, the error message clearly described what's wrong in the test case in expect clause, such as in https://github.com/shipwright-io/build/blob/master/test/e2e/validators.go#L109, but sometimes there is no error message description in expect clause, such as in https://github.com/shipwright-io/build/blob/master/test/e2e/e2e_test.go#L29. 
This PR is to fill in all missing error message description in expect clause in end to end test. Test result with this PR shows this line `BuildRun status doesn't move to Succeeded`. Without this PR, it only showed the below `Expect... ` lines.

Add detailed error message for e2e test

---

test/data/build_buildpacks-v3_ruby_cr.yaml

To workaround the ruby buildpack failure, I am changing to use the develop branch instead of main, as explained [here](https://github.com/shipwright-io/build/issues/532#issuecomment-758500156).

Temporarily use develop branch for dora

---

docs/proposals/buildstrategy-annotation-propagation.md

The enhancement proposal is about annotations that need to be set on a pod and to give the build strategy administrator control over them. Related to [Provide control over pod labels and annotations #520](https://github.com/shipwright-io/build/issues/520).
Here is the rendered version: [Propagating annotations from the build strategy to the pod](https://github.com/SaschaSchwarze0/build/blob/sascha-515-ep-annotations/docs/proposals/buildstrategy-annotation-propagation.md).

EP: Propagating annotations from the build strategy to the pod

---

test/data/build_buildpacks-v3_ruby_cr.yaml

Fixes #532
The new ruby buildpack has been released. This contains the lax version matching for bundler and is therefore supposed to work also with the main branch of cf-acceptance-test that references an older version of bundler.

Go back to main branch for dora

---

.github/workflows/ci.yml
Makefile
hack/install-operator-sdk.sh
test/integration/build_to_secrets_test.go

Picking up where #507 left off.
- Add more granular Makefile targets for test dependencies
- Add new Github Action job to run integration tests
- Update Makefile to install ginkgo and gocov via temporary
go modules. This ensures the binaries are installed via `go get`,
without having local vendor inconsistencies.
- Fix operator-sdk install script so it works via Github Actions.
- Work around integration test flake - reason message if no secrets
are present in the namespace.

GitHub Actions for unit and integration tests

---

.travis.yml

Ensure only e2e tests are executed, unit and integration should
be done via git actions

Refactor travis tests to only run e2e

---

Makefile
docs/build.md
docs/development/testing.md
docs/proposals/build-execution-using-build-run.md
docs/proposals/buildstrategy-steps-resources.md
docs/proposals/remote-artifacts.md
pkg/apis/core/v1alpha1/condition_types.go
pkg/controller/build/build_controller.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/controller.go
pkg/metrics/metrics.go
test/catalog.go
test/e2e/samples.go
test/integration/buildruns_to_taskruns_test.go
test/integration/utils/buildruns.go
test/integration/utils/taskruns.go
version/version.go

I went on the Go Report Card of `shipwright-io/build` by chance and saw some minor warnings there. So I decided to quickly fix all warnings that were easy to fix.
This includes:
- fixing spelling
- missing comments
- ineffective variable assignments

Fix some of the Go Report Card findings

---

pkg/ctxlog/log.go
test/integration/integration_suite_test.go
test/integration/utils/environment.go
test/integration/utils/operator.go

I was just fighting with a failing integration test and needed access to the logs of the operator. Had to do a quick hack. Proposing here a solution that dumps the logs in case a test case fails. Here is an example:
```bash
$ make test-integration
installing apis
customresourcedefinition.apiextensions.k8s.io/buildstrategies.build.dev unchanged
customresourcedefinition.apiextensions.k8s.io/clusterbuildstrategies.build.dev unchanged
customresourcedefinition.apiextensions.k8s.io/builds.build.dev unchanged
customresourcedefinition.apiextensions.k8s.io/buildruns.build.dev unchanged
GO111MODULE=on ginkgo \
-randomizeAllSpecs \
-randomizeSuites \
-failOnPending \
-slowSpecThreshold=240 \
-trace \
-focus=SASCHA \
test/integration/...
Running Suite: Integration Suite …
```

Print operator log for failed integration test case

---

docs/buildstrategies.md
docs/proposals/buildstrategy-annotation-propagation.md
pkg/apis/build/v1alpha1/build_types.go
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/apis/build/v1alpha1/buildstrategy.go
pkg/apis/build/v1alpha1/buildstrategy_types.go
pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
pkg/controller/buildrun/generate_taskrun.go
pkg/controller/buildrun/generate_taskrun_test.go
test/build_samples.go
test/buildstrategy_samples.go
test/clusterbuildstrategy_samples.go
test/integration/buildstrategy_to_taskruns_test.go
test/integration/clusterbuildstrategy_to_taskruns_test.go
test/integration/utils/buildstrategies.go

This is the implementation of the enhancement proposal [Propagating annotations from the build strategy to the pod](https://github.com/shipwright-io/build/blob/master/docs/proposals/buildstrategy-annotation-propagation.md).

Propagate annotations from BuildStrategy to TaskRun

---

.github/workflows/ci.yml

Integration tests don't need the operator-sdk binary to run.
Remove the install operator-sdk step to improve performance.

Remove operator-sdk install from integration tests

---

CONTRIBUTING.md
README.md
SECURITY.md
code-of-conduct.md

Add our email communication channels to relevant shipwright/build documentation.
- End user list - shipwright-users@lists.shipwright.io
- Dev topics list - shipwright-dev@lists.shipwright.io
- Admins - shipwright-admin@lists.shipwright.io
- Security - shipwright-security@lists.shipwright.io

Email communication channels

---

docs/metrics.md
pkg/config/config.go
pkg/config/config_test.go
pkg/controller/build/build_controller.go
pkg/controller/buildrun/buildrun_controller.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

Signed-off-by: xigxjn <xigxjn@cn.ibm.com>
We did some improvement for the current build and buildrun metrics:
- We just support `buildstrategy` label fro both `builds_registered_total` and `buildruns_completed_total` metrics: https://github.com/shipwright-io/build/blob/v0.2.0/pkg/metrics/metrics.go#L24-L36
- We don't have `build` label for the buildrun histogram related metrics: https://github.com/shipwright-io/build/blob/v0.2.0/pkg/metrics/metrics.go#L61-L72
The current metric looks good for the single-tenant user, but if we use Shipwright/build in a multiple-tenant environment, the tenant user cannot get correct build or buildrun total count by using the `namespace` or other labels, it is not a good usage
And it is also for histogram metric, we missed `build` label, such as the user …

Add more labels for Counter count metrics

---

README.md

Mailto links do not work well across some browser/OS combinations.
Replacing these with the admin lists page hyperlink, which includes a
Subscribe/Unsubscribe form that works for any modern web browser.

Replace mailto links for Shipwright email lists

---

deploy/crds/build.dev_builds_crd.yaml
docs/build.md
go.mod
pkg/apis/build/v1alpha1/build_types.go
pkg/controller/build/build_controller.go
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
pkg/validate/ownerreferences.go
pkg/validate/runtime.go
pkg/validate/secrets.go
pkg/validate/sourceurl.go
pkg/validate/strategies.go
pkg/validate/validate.go
test/catalog.go
test/integration/build_to_buildruns_test.go
test/integration/build_to_git_test.go
test/integration/build_to_secrets_test.go
test/integration/buildruns_to_taskruns_test.go
test/integration/utils/builds.go
vendor/modules.txt

This fixes #463 and #494
_Note_: this a follow-up based on the discussions in #463 , we are not longer introducing error codes, but rather an enhancement in the Build Status fields based on the feedback on that issue.
This should conclude a set of enhancements we have been doing in both Build/BuildRun Status fields. This PR proposes an enhancement on the Build Status fields. This will provide more clarity for users on why a validation happened and will also standardize the `Status.Reason` via the usage of a one-word camelCase constant. We also introduce a distinction on which type of referenced secret is missing, previously we were only highlighting if one or multiple secrets were missing, but we didn´t make any references to where in the Build definition was this secret used.
The …

Refactor Build Status fields

---

pkg/validate/secrets.go

We assert for a combination of secret names under Status.Message when
the secrets validation fails. Because the list of secrets comes from a
map and a map is an unordered collection of key-value pairs, this
commits adds a sort, to ensure an ordered list in Status.Message and for
avoiding the flakiness in the unit-test spec.
Flaky test was [when source secret and output secret are specified](https://github.com/shipwright-io/build/blob/master/pkg/controller/build/build_controller_test.go#L228-L229)

Fix flaky unit-test spec for Build

---

pkg/controller/buildrun/buildrun_controller.go
pkg/controller/buildrun/buildrun_controller_test.go
test/buildrun_samples.go
test/catalog.go
test/integration/build_to_buildruns_test.go
test/integration/buildruns_to_sa_test.go

The `Status.Conditions` under this [function](https://github.com/shipwright-io/build/blob/master/pkg/controller/buildrun/buildrun_controller.go#L676-L684) is not being populated, this PR enhances this.
- when validate failed during buildRun reconciles, this buildRun condition field will be set. The reason is `Failed` and status is `False`. Below is a buildRun example about the specified serviceAccount in buildRun doesn't exist:
```
apiVersion: v1
items:
- apiVersion: build.dev/v1alpha1
kind: BuildRun
metadata:
creationTimestamp: "2021-01-28T08:20:38Z"
generation: 1
labels:
build.build.dev/generation: "1"
build.build.dev/name: build-test-build-201
name: buildrun-test-build-201
namespace: test-build-201
resourceVersion: "79744925"
selfLink: …
```

Fix missing BuildRun Conditions updates on errors

---

go.mod
go.sum
vendor/github.com/gogo/protobuf/proto/text_parser.go
vendor/golang.org/x/tools/go/ast/astutil/util.go
vendor/golang.org/x/tools/imports/forward.go
vendor/golang.org/x/tools/internal/gocommand/version.go
vendor/golang.org/x/tools/internal/imports/mod.go
vendor/golang.org/x/tools/internal/imports/mod_cache.go
vendor/modules.txt

ased on https://nvd.nist.gov/vuln/detail/CVE-2021-3121, there is a
vulnerability in the Go module `gogo/protobuf`. This is an indirect
dependency of `shipwright/build`. Even though there seems to be only
one change from the CVE fix that ripples down into our code base, it
should be addressed by making sure we use the fixed version. Due to
the fact it is an indirect dependency of the Kubernetes packages, it
does not sound practical to bump the Kubernetes module versions.
Make sure that fixed version of `gogo/protobuf` is used.

CVE-2021-3121 (skippy peanut butter)

---

test/integration/build_to_buildruns_test.go

This reason can appear when TaskRun Pods are pending due to insufficient cluster resources, which seems to happen quite often in CI integration tests

Accept ExceededNodeResources as a valid Reason in integration tests

---

Makefile

I recently learned of the `-trimpath` flag for Go builds. It will remove build
system specific file paths from the created Go binary. This seems to be a best
practice for reproducible builds as a build from my local machine yields the
same binary as the build from Travis and any other future build infrastructure.
Add `-trimpath` to the default Go flags.

Add trimpath Go build flag

---

.travis.yml
Dockerfile
HACK.md
Makefile
go.mod
openshift-ci/Dockerfile.tools

There were different Go versions used in the Go module, Travis configuration,
GitHub Actions configuration, and the project Dockerfile. Also, the version
of the operator SDK was different in some places.
Sync Go version to be `1.15` everywhere.
Make operator SDK version `v0.18.2` consistently.

Sync Go and operator SDK versions used

---

Makefile

Flaky behavior can hurt real users, and ignoring it to appease CI tests only hides the problem, and can make CI tests take longer.
If this is too noisy, we can either spend effort fixing flakes, and/or make tests less strict, or re-enable flaky retries.
---
I've run this locally 10x with https://github.com/shipwright-io/build/pull/570 and didn't experience any failures. Let's see if CI agrees 😄

Don't retry flakes in integration tests

---

.github/workflows/release.yaml

This will allow us to construct a draft release with:
- Template for the release notes (based on previous releases)
- History of commits since latest release
- Automatic creation of new desired tag

Add release.yaml github action

---

.github/workflows/release.yaml

This fixes the existing release.yaml to fetch all history of commits.

Update release.yaml for github actions

---

Makefile

Run `make test-unit` via go test so that we do not need to download ginkgo on each run.
Some ginko flags have counterparts for `go test`.
The following flag modifications were made:
- -randomizeAllSpecs - removed, not available for go test. Randomizing the order specs run in has limited value for unit testing.
- -randomizeAllSuites - removed, not available for go test. Randomizing the order suites run in has limited value for unit testing.
- -failOnPending - removed, not available for go test. This prevents developers from checking in tests that are marked "Pending" in ginkgo.
- -slowSpecThreshold - removed, not available for go test. This displays a warning if a spec takes longer than the provided threshold. Not really relevant for unit tests, which should run quickly. There is a global …

Use go test to run unit tests

---

.travis.yml

Without this, `hack/release.sh` fails with:
```
hack/release.sh: line 10: ko: command not found
```
See https://travis-ci.org/github/shipwright-io/build/builds/758200833#L5665

Fix travis by installing ko

---

docs/proposals/dedicated-shipwright-operator.md

This is a proposal to create a separate operator that installs
Shipwright Builds on a Kubernetes cluster with Operator Lifecycle
Manager (OLM) enabled. It provides details on a configuration Custom
Resource that is applied to the Shipwright Builds deployment.
This replaces #514 because it provides the means for installing Shipwright projects via OLM.

Proposal: Dedicated Shipwright Operator

---

Makefile

There are linker flags that can make our build operator binary and therefore our container image smaller. For example, we can [omit the symbol table and debug information and the DWARF symbol table](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/). In case of the build operator this means we can save 20% of the regular size. The majority of the container image size is still the base image, but we could save a bit more than 14 MiB or so.

Tweak build operator build settings

---

Makefile
cmd/manager/main.go
docs/profiling.md
hack/release.sh
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/pprof.go

In preparation for production use cases, I realized that we have currently no means to diagnose memory usage of the controller during runtime in a cluster. I took a look and saw that other operators use `pprof` to optionally expose a profiling endpoint to be used, e.g. memory leak analysis.
The rough idea is:
- Enable `pprof` via change in the deployment.
- Set-up port-forwarding from local machine to current leader.
- Use `go tool pprof` to profile the operator during runtime.
Using [profiling in production seems to be safe](https://medium.com/google-cloud/continuous-profiling-of-go-programs-96d4416af77b), but -- of course -- it has performance implications.
Feedback on this would be highly appreciated.

Add pprof support to build operator

---

test/e2e/validators.go

There are cases, where the cluster API service can return an internal server
error with HTTP status code 502 when trying to receive an object, i.e. build.
Add the class of internal server errors `50X` to the list of retry-able errors.
/assign @qu1queee

Add 502 to list of retryable errors

---

.github/workflows/release.yaml

This uses `ko` to generate the release.yaml and add it as an asset to the GitHub Release.
It depends on the existence of GitHub Actions secrets named "REGISTRY_PASSWORD" and "REGISTRY_USERNAME".
cc @qu1queee

Generate release.yaml in GitHub Actions release

---

Makefile
hack/release.sh

It seems like quay.io doesn't support image refs that contain slashes, which runs afoul of hack/release.sh which tries to push to `quay.io/shipwright/shipwright-operator/github.com/shipwright-io/build/cmd/manager`
The error message is:
```
2021/02/09 17:50:12 error processing import paths in "deploy/operator.yaml": error resolving image references: GET https://quay.io/v2/auth?scope=repository%3Ashipwright%2Fshipwright-operator%2Fgithub.com%2Fshipwright-io%2Fbuild%2Fcmd%2Fmanager%3Apush%2Cpull&service=quay.io: NAME_INVALID: Nested repositories are not supported. Found: shipwright/shipwright-operator/github.com/shipwright-io/build/cmd/manager; map[]
```
~~With this change, `ko` will instead push to `quay.io/shipwright/shipwright-operator/manager` (🚨 which is still invalid 🚨 ).~~
Our options …

Publish images without full import path

---

.github/pull_request_template.md

To mimic upstream tekton on how they curate release notes on a per PR basis using the prow release-note plugin
Related PR:  https://github.com/openshift/release/pull/15770
/assign @adambkaplan 
/assign @qu1queee 
@sbose78 FYI
ultimately what happens is a `release-note` or `release-note-none` label is required for PR merge, and which label is applied is triggered by what is placed in the `release-note` description of the PR.

add pull request template to integrate with prow release-note plugin

---

docs/build.md
docs/buildstrategies.md
pkg/controller/build/build_controller_test.go
pkg/controller/buildrun/generate_taskrun_test.go
samples/build/build_buildah_cr.yaml
samples/build/build_kaniko_cr.yaml
test/build_samples.go
test/catalog.go
test/integration/build_to_buildruns_test.go
test/integration/build_to_git_test.go

The existing one have an issue on the go.mod definition, leading
to build failures when using the latest golang image.
This PR changes the repo to use, which have the fixes in place. This
is a fix PR, the end-goal is to tackle issue #366 which should avoid
problems like this in the future.
```release-note
NONE
```

This replaces the taxi go app repo

---

.github/workflows/sanity-checks.yaml
pkg/metrics/metrics.go

Add GitHub Action workflow configuration to run sanity checks on the Go source. It should run by default only on the current default branch and in PRs against that branch.
Fixes #552
```release-note
NONE
```

Add GitHub Action for Sanity Checks

---

Makefile

The `find` command for the `misspell` Makefile target included a lot of files
that should not be included, ie. `.git` directory.
Add exceptions to the find command to filter for only relevant files.
```release-note
NONE
```

Improve find for misspell check

---

README.md

- Instruct users to clone the repo at the v0.3.0 tag.
- Add note that install via kubectl is coming soon.
- Fix whitespace/format for code blocks.
```release-note
NONE
```

Work around current make-install state

---

README.md

The software that Shipwright installs is mainly a "controller" to watch and reconcile CRD resources. This is distinct from an "operator", which installs and manages other software installations (e.g., a database, other controllers).
Relying on operator-sdk as an implementation detail also obscures this distinction, but I hope we can disentangle that in the future as well. For now, we can at least clearly describing what Shipwright installs for users.
This isn't the only place where Shipwright's software is referred to as an "operator", but it's the most prominent at least.
- [y] Includes docs if changes are user-facing
See [the contributor …

Remove references to the term "Operator" from README.md

---

pkg/reconciler/build/build.go
pkg/reconciler/build/controller.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/controller.go
pkg/reconciler/buildrun/resources/build.go
pkg/reconciler/buildrun/resources/build_test.go
pkg/reconciler/buildrun/resources/conditions.go
pkg/reconciler/buildrun/resources/conditions_test.go
pkg/reconciler/buildrun/resources/errors.go
pkg/reconciler/buildrun/resources/errors_test.go
pkg/reconciler/buildrun/resources/resources_suite_test.go
pkg/reconciler/buildrun/resources/service_accounts.go
pkg/reconciler/buildrun/resources/service_accounts_test.go
pkg/reconciler/buildrun/resources/strategies.go
pkg/reconciler/buildrun/resources/strategies_test.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildstrategy/buildstrategy.go
pkg/reconciler/buildstrategy/controller.go
pkg/reconciler/clusterbuildstrategy/clusterbuildstrategy.go
pkg/reconciler/clusterbuildstrategy/controller.go
test/catalog.go

This is a rebase on top of #593 . This PR is doing the following:
- [1] Separate controller/reconcile logic. This ensures that between controller definition and reconcile logic, we have a clear separation.
- [2] Refactor buildRun reconciler class. Move some functions into new or existing classes under the internal resource package. This class was one of the most hardest files to read. So the goal here is to make it easier for future contributors.
- [3] Ensure proper code coverage. Because I externalize a lot of the functions in [2], into the internal `resource` pkg, I´m adding a bunch of new unit-tests to increase the coverage of those functions.
```release-note
Restructure BuildRun reconcile code into separate classes.
```

Restructure buildrun code into separate resources 

---

.github/workflows/ci.yml
.travis.yml
Makefile
hack/install-tekton.sh
test/data/registry.yaml

Changing the e2e tests to run as a GitHub action instead of in Travis. I am also changing both the integration as well as e2e test to run with Kubernetes 1.17, 1.18, 1.19 and 1.20.
```release-note
NONE
```

Use GitHub action for e2e test

---

.github/workflows/ci.yml
.travis.yml
test/clusterbuildstrategy_samples.go
test/e2e/samples.go
test/integration/build_to_buildruns_test.go
test/integration/buildruns_to_sa_test.go
test/integration/buildruns_to_taskruns_test.go
test/integration/buildstrategy_to_taskruns_test.go
test/integration/clusterbuildstrategy_to_taskruns_test.go
test/integration/utils/buildruns.go
test/integration/utils/namespaces.go

PR [Use GitHub action for e2e test #611](https://github.com/shipwright-io/build/pull/611) should not have been merged by the robot. It had an approval, but the tests were not successful.
Basically, after having added the fourth Kubernetes version to the test matrix, the actions became unstable. Statements in the documentation like [this](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) leave room for interpretation, but I assume there is some resource limit and CPU is becoming the bottleneck.
I am therefore trying to limit the parallelism.
In addition, I am making changes to remove race conditions:
* in e2e, I am waiting for the Build to be registered before creating a BuildRun
* in integration, I am waiting for the Build to …

Improve test stability

---

docs/build.md
docs/buildstrategies.md
docs/configuration.md
pkg/config/config.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go

I am updating the Kaniko dependency to v1.5.1. I am also leveraging the new [--push-retry](https://github.com/GoogleContainerTools/kaniko#--push-retry) flag to circumvent network hickups during the push that we have seen intermittently in our downstream tests.
Fixes #557
```release-note
Update Kaniko to v1.5.1 including better retry support for the image push to the container registry
```

Update Kaniko to v1.5.1, leverage --push-retry

---

.github/pull_request_template.md

Per recent dev list discussion, we will start requiring a kind label on PRs, and per suggestion from @adambkaplan 
the PR template is updated with this PR to facilitate the new requirement.
- [ n/a ] Includes tests if functionality changed/was added
- [ n/a ] Includes docs if changes are user-facing
- [ y ] Release notes block has been filled in, or marked NONE
```release-note
NONE
```
/kind dependency-change

update PR template for setting kind label

---

.github/workflows/ci.yml

I just saw this in a PR log where an e2e test failed:
```
Run echo "# Pods:"
NAME                                                      READY   STATUS      RESTARTS   AGE
build-operator-55f9bbbcfd-rc8sz                           1/1     Running     1          17m
buildah-75xqq-vsfbv-pod-srpmw                             0/5     Completed   0          4m6s
buildah-custom-context-dockerfile-76w89-r7pkx-pod-rh5tt   0/5     Completed   0          4m53s
buildpacks-v3-fxh7r-5z6vr-pod-8s4gp                       0/5     Completed   0          14m
buildpacks-v3-golang-c9g8d-mgqgk-pod-pvdvl                0/5     Completed   0          11m
buildpacks-v3-heroku-namespaced-k9p2d-jnqpk-pod-ht28k     0/5     Completed   0          14m
buildpacks-v3-namespaced-vpdbq-tfs7f-pod-m4jht            0/5 …
```

Ignore previous logs failure

---

pkg/reconciler/build/controller.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/controller.go
test/integration/buildruns_to_taskruns_test.go
test/integration/utils/taskruns.go

While testing something, I noticed that deleting a build caused a reconciliation on the build:
```
Feb 24 13:55:02 build-operator-dbbb6b95-272vf build-operator debug {"level":"debug","ts":1614171301.8459392,"logger":"build.build-controller","msg":"start reconciling Build","namespace":"default","name":"test-kaniko-xlarge-97"}
Feb 24 13:55:02 build-operator-dbbb6b95-272vf build-operator debug {"level":"debug","ts":1614171301.8459957,"logger":"build.build-controller","msg":"finish reconciling build. build was not found","namespace":"default","name":"test-kaniko-xlarge-97"}
```
That caused me to look into the reconciliations on delete. For Builds, I simply always return false in the predicate function because there is nothing we need to do when a Build is deleted since we do not have any …

Correct and optimize reconciliation on deletion

---

.github/workflows/ci.yml
DEVELOPMENT.md
HACK.md
Makefile
build/Dockerfile
build/bin/entrypoint
cmd/manager/main.go
deploy/100-namespace.yaml
deploy/200-role.yaml
deploy/300-rolebinding.yaml
deploy/400-serviceaccount.yaml
deploy/500-controller.yaml
deploy/service_account.yaml
docs/build.md
docs/buildstrategies.md
docs/configuration.md
docs/development/authentication.md
docs/development/local_development.md
docs/development/testing.md
docs/metrics.md
docs/profiling.md
hack/install-tekton.sh
pkg/config/config.go
pkg/config/config_test.go
test/e2e/e2e_suite_test.go

This change renames installed components to avoid the misnomer "operator". See #607 for full motivation and an outline of the changes.
Fixes #607
This change will require installations to uninstall any previous version of Shipwright before installing this new version -- naively `kubectl apply`ing this new config with a previous installation of Shipwright installed would result in two competing installations, which would probably not be fun. …

Rename Shipwright components away from "operator"

---

README.md
docs/build.md
docs/buildstrategies.md
samples/build/build_ko_cr.yaml
samples/buildrun/buildrun_ko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
test/e2e/e2e_test.go

Based on [this inquiry](https://kubernetes.slack.com/archives/C019ZRGUEJC/p1613685285101400?thread_ts=1613404922.076800&cid=C019ZRGUEJC), I am adding the ko sample build strategy that I recently created. I added a big note to the documentation about the creative interpretation of the `contextDir` property.
```release-note
- Adding a sample build strategy for [ko](https://github.com/google/ko)
```

Add ko build strategy sample

---

samples/build/build_ko_cr.yaml
samples/buildrun/buildrun_ko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

@sbose78 merged my [ko PR](https://github.com/shipwright-io/build/pull/603) after the [API rename](https://github.com/shipwright-io/build/pull/609). The sample files therefore contain an incorrect API version. That's why our master build is currently red.
```release-note
NONE
```

Fix API version of ko objects

---

.github/workflows/ci.yml
samples/build/build_ko_cr.yaml

Fixes a reference to the old namespace inside the CI definition.
Fixes an old reference to the build-operator in a sample file.
```release-note
NONE
```

Add missing rename for new ns syntax

---

docs/build.md
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go

The behaviour for a git repo revision was being hardcoded to `master`,
which is incorrect, while github is already creating the default branch
to `main` and also because the default Tekton behaviour was not taking
place if the revision parameter is not specified.
Tekton defaults behaviour triggers a git symbolic-link to HEAD, which
we should allow to happen if the user does not specify a revision in the
Build source.
Fixes #518
Tekton introduced the default behaviour in https://github.com/tektoncd/pipeline/commit/9aff0a076f70c7bf32a6e275762e6097f8f3cb2d
- [x ] Includes tests if functionality changed/was added
- [x ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x ] Release notes block has been filled in, or marked NONE
See [the contributor …

Modify default branch behaviour for git repos

---

.github/workflows/nightly.yaml

This builds on #600 and, instead of creating a new release each night, simply appends release assets to an existing release, the newest release named like "Nightly Releases *" -- this release would have to be created manually, once. This also allows us to periodically, manually archive a batch of nightly releases and create a new umbrella release.
Every night at midnight EST, the release would build and push images to quay.io and produce two YAMLs, `nightly-${date}.yaml` and `nightly-${date}-debug.yaml`, where `${date}` is `YYYY-MM-DD-SSSSSSSSSSS` in case we want to produce multiple nightly releases in a day.
You can see an example of this in action at https://github.com/ImJasonH/build-1/releases/tag/nightly
Installing from a nightly release:
```
$ kubectl apply -f …
```

Take 2: Publish nightly release assets

---

.github/workflows/ci.yml

When test fails, avoid trying to retrieve pod logs if we know the pod
is not longer there.
```release-note
NONE
```

Enhance CI e2e test on logs retrieval

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml

Add condition to ensure nightly and regular release jobs only run on the
shipwright-io/build repository. This ensures the nightly and official release jobs
do not run on forks.
/kind bug
```release-note
Github actions: ensure nightly and release jobs are not run on contributor forks.
```

Release jobs - only run on shipwright-io/build

---

DEVELOPMENT.md
Makefile
hack/install-controller-gen.sh

This PR is for changing to use [controller-gen tool](https://github.com/kubernetes-sigs/controller-tools) from kubebuilder to generate CRDs 
Fixes https://github.com/shipwright-io/build/issues/579
-->
Added a script and make target to install controller-gen tool and generate CRDs with this tool

Add make target for generating crds through controller-gen

---

.github/workflows/ci.yml

The name `ci/github` is a bit generic.
Set it to `Unit, Integration, and E2E Tests` to reflect that this part of the
automation runs the unit tests, integration tests and E2E tests together.
/kind enhancement
```release-note
NONE
```

Change GitHub Action name to be more readable

---

docs/buildstrategies.md
pkg/reconciler/buildrun/resources/runtime_image.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go

For a `RUN something` command, Kaniko triggers a process for `something`. In case `something` triggers a daemon process, Kaniko must kill this once the main process is terminated. The reason is that the daemon could otherwise continue to make changes to the file system that will fail the layer creation. See [`RUN <process>` can leave processes running in the background #247](https://github.com/GoogleContainerTools/kaniko/issues/247) for more information.
Kaniko is running as root. If the daemon process runs as a different user, for example because thee is a `USER nonroot` statement in the Dockerfile before the `RUN` command, then the `KILL` capability is necessary.
The Kaniko kill logic is here: [run.go](https://github.com/GoogleContainerTools/kaniko/blob/v1.5.1/pkg/commands/run.go#L130). …

Add KILL capability for Kaniko executor to allow it to kill non-root processes

---

Makefile
build/Dockerfile
build/bin/entrypoint
cmd/manager/main.go
docs/buildstrategies.md
docs/proposals/dedicated-shipwright-operator.md
hack/release.sh
pkg/config/config.go
pkg/config/config_test.go
pkg/reconciler/buildrun/resources/runtime_image.go
test/integration/integration_suite_test.go
test/utils/controllers.go
test/utils/environment.go
version/version.go

After the PR `Rename Shipwright components away from "operator"`: https://github.com/shipwright-io/build/pull/610
There are still some codes and comments which uses `operator` which may make end user or new developer confusion.
If we decide to swtich `build operator` to `Shipwright build controller`, we should review all codes and switch them all.
- Still keep `operator-sdk` related words as before
- Modify the code and related properties, etc ...
- Modify in the documents
- Modify in the test codes
- Update the version of the Shipwright build controller from `0.0.1` to `0.3.0`
/kind cleanup
- [ n ] Includes tests if functionality changed/was added
- [ n ] Includes docs if changes are user-facing
- [ y ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ y ] …

Refine the other operator related names

---

docs/build.md
pkg/reconciler/build/build_test.go
pkg/validate/sourceurl.go
test/build_samples.go
test/integration/build_to_git_test.go

Fix issue: https://github.com/shipwright-io/build/issues/659
Default, build controller won't check sourceURL unless `build.shipwright.io/verify.repository` annotation is true.
- Switch to don't validate sourceURL by default.
- Update related unit tests and integration tests.
- Update related docs.
- Git validation behaviour changes
```release-note
sourceURL validation is disabled by default.
```

Git validation is disabled by default

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
deploy/crds/shipwright.io_buildstrategies.yaml
deploy/crds/shipwright.io_clusterbuildstrategies.yaml

This is a fix PR for the PR: https://github.com/shipwright-io/build/pull/667
I also asked Matt and Zoe to verify, they also generate normally WITH line-breaking, but I tried several ways, all didn't work..... Finally, I gave up, I don't know why there is no `line-breaking` when I ran the `make generate-crds` in my local Mac.
**Maybe because my Mac is more powerful than other ones. :(**
Below is what I tried:
- Ask Matt and Zoe help, they can generate with line-breaking normally on the Mac
- I tried on Ubuntu, can also generate with line-breaking
- Then I tried to upgrade my Golang to 1.15, upgrade/downgrade, my controller-gen, change GOPATH, etc... they all didn't work
Because it is ONLY my Mac problem, so I provide this PR to change to the NORMAL format with line-breaking in this PR.
And …

Re-generate the crds by using line breaking

---

.github/workflows/ci.yml
README.md
deploy/crds/shipwright.io_buildstrategies.yaml
deploy/crds/shipwright.io_clusterbuildstrategies.yaml
hack/install-kind.sh

With the recent Tekton and Kube API update, we now have the 1.19 versions of Kubernetes. But, it seems the CRDs were not regenerated as the new seccompProfile field in the securityContext is not yet there. I ran `make generate-crds` to get the changes.
I am also changing our tests to run with Kubernetes 1.19 and the README to mention this version. Also removing old versions that as far as I remember do not work (not remembering the detail though) when I tried to run multiple versions in our CI tests.
Setting release note none because the original change and this fix will go in the same release.
```release-note
NONE
```

Update generated CRDs

---

pkg/apis/build/v1alpha1/buildrun_types.go
pkg/reconciler/buildrun/buildrun.go

A step toward https://github.com/shipwright-io/build/issues/517 -- if people are okay with this we can remove it in the next release (v0.5.0)
Marks `.status.succeeded` and `.status.reason` as `Deprecated`, updates some doc comments I noticed while I was in the area.
/kind cleanup
```release-note
BuildRun .status.succeeded and .status.reason are marked as …
```

Deprecate .status.succeeded and .status.reason

---

docs/build.md
pkg/apis/build/v1alpha1/build_types.go
pkg/reconciler/build/build_test.go
pkg/validate/secrets.go
test/integration/build_to_secrets_test.go

The status seems to be misnamed, since it only applies when the `builder` image's secretRef isn't found, and isn't related to the runtime-image feature as far as I can tell.
This was mainly a scripted change:
```
git grep -l "SpecRuntimeSecretRefNotFound" | xargs sed -i '' -e 's/SpecRuntimeSecretRefNotFound/SpecBuilderSecretRefNotFound/g'
```
... with one manual change in a doc comment.
/kind cleanup
- [y] Includes tests if functionality changed/was added
- [y] Includes docs if changes are user-facing
for details on coding conventions, github and prow …

Rename `SpecRuntimeSecretRefNotFound` -> `SpecBuilderSecretRefNotFound`

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
pkg/apis/build/v1alpha1/gitsource.go

Fixes https://github.com/shipwright-io/build/issues/682
Remove `HTTPProxy`, `HTTPSProxy`, `NoProxy` and `Flavor`. No other code referenced them, so if users set these fields they wouldn't have any effect.
/kind cleanup
/kind api-change
```release-notes
Remove unused fields from GitSource
```
/assign @sbose78

Remove unused fields from GitSource

---

.github/workflows/nightly.yaml

Update nightly release workflow to add a tag to images it produces, like `:nightly-{date}-{seconds}`
Quay.io aggressively garbage collects untagged manifests, so our nightly release images are no longer available after a few days, for example [`@sha256:a930c8`](https://quay.io/repository/shipwright/shipwright-operator/manifest/sha256:a930c8b8b04f856ce505209aee87d0d938b3f761081ae4811c95ad03881ea491) from our [2021-03-18 nightly release](https://github.com/shipwright-io/build/releases/download/nightly/nightly-2021-03-18-1616044224.yaml).
Applying tags to these images should keep them from getting GCed.
/kind bug
- …

Tag nightly releases to avoid quay GC

---

docs/proposals/webhook-validation.md

Adds a proposal as `provisional` to gather feedback.
See also #596 
/kind feature
```release-note
NONE
```

Add EP for synchronous webhook validation

---

hack/install-kind.sh

Update KinD version to the same v0.10.0
Sync the `KinD` version with GitHub Action config: https://github.com/shipwright-io/build/blob/master/.github/workflows/ci.yml#L53
Update to the same version
/kind cleanup
- [ n ] Includes tests if functionality changed/was added
- [ n ] Includes docs if changes are user-facing
- [ y ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ n ] Release notes block has been filled in, or marked NONE
```release-note
NONE
```

Update KinD version to the same v0.10.0

---

pkg/apis/build/v1alpha1/build_types.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/buildrun_test.go

There were cases in which the Build had a `nil` Strategy, which is copied into
the BuildRun `Status.BuildSpec` and later used internally, for example the
metrics code is using the `Strategy` field. In case it is `nil`, the function
call for the metrics failed with a nil-pointer dereference.
Introduce `BuildSpec` convenience function called `StrategyName` to return the
name of the strategy, which includes a `nil` safety check.
Replace all occurrences of `BuildSpec.Strategy.Name` with the newly introduced
function to avoid panics.
```release-note
Fix nil-pointer dereference with panic in case Build spec …
```

Fix nil-pointer dereference of BuildSpec Strategy

---

docs/build.md
docs/buildstrategies.md
docs/configuration.md
pkg/config/config.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go

Kaniko v1.5.2 does not contain any new features beside that its image is now signed. So, should not be breaking anything.
```release-note
The Kaniko build strategy is updated to use v1.5.2 of Kaniko
```

Update Kaniko to v1.5.2

---

pkg/validate/sourceurl.go
pkg/validate/strategies.go

While looking at some logs of our controller, I noticed that some labels were missing on the `the annotation build.shipwright.io/verify.repository is set to , nothing to do`. Adding them, also checked other build-related validation code.
```release-note
NONE
```

Add missing log labels

---

README.md
docs/buildstrategies.md
docs/tutorials/README.md
docs/tutorials/building_with_buildkit.md
samples/build/build_buildkit_cr.yaml
samples/buildrun/buildrun_buildkit_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
test/data/build_buildkit_cr_insecure_registry.yaml
test/e2e/e2e_test.go

Fixes #407 
This adds support for rootless buildkit.
Some of the key things from using buildkit are:
- The cache on subsequent pushes to the same image in a registry, also known as export_cache and import_cache makes the building experience incredible fast.
- It runs as rootless, without any privileges.
- It have a better way to handle where the source code is located and where is the dockerfile located (_e.g. compared to Kaniko_), however we will need to extend our strategy params to support a new one. At the moment, some of the configs for running it are not configurable, but with the upcoming params support, this will change. I documented this limitations in the related document.
- Latest Docker versions come with the option to opt-in for a backend Buildkit, therefore its very popular …

Add support for Buildkit

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml
Makefile
README.md
docs/buildstrategies.md
hack/release.sh
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

This enables our build to produce multi-platform images. Details:
* I am switching to `ko` 0.8.1, 0.8.0 probably also works, but I locally worked with the latest version.
* In the Makefile, I rename the global environment variables `GOOS` and `GOARCH` to `GO_OS` and `GO_ARCH`. I need to do this to prevent those variable to be present anywhere, especially in the `release` target where `ko` is now ran with the `--platform=all` argument to produce the multi-platform image. In that case, the `GOOS` and `GOARCH` environment variables must not be set. For other targets that are invoking `ko`, I am setting those two environment variables specifically to make sure the image is built for the platform of the user's machine. Otherwise, `ko` would always be building `linux/amd64`
* The README adds a …

Multi-platform support

---

pkg/apis/build/v1alpha1/build_types.go

We observed a panic over the weekend:
```
Apr 11 15:10:02 shipwright-build-controller-69c6b88498-mc4l9 shipwright-build error E0411 13:10:02.395440       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Apr 11 15:10:02 shipwright-build-controller-69c6b88498-mc4l9 shipwright-build goroutine 504 [running]:
Apr 11 15:10:02 shipwright-build-controller-69c6b88498-mc4l9 shipwright-build k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1809a00, 0x26b2a90)
k8s.io/apimachinery@v0.19.7/pkg/util/runtime/runtime.go:74 +0x95
Apr 11 15:10:02 shipwright-build-controller-69c6b88498-mc4l9 shipwright-build k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) …
```

Handle nil buildSpec

---

docs/proposals/parameterize-strategies.md

Provides an EP on how to manage parameters in Strategies, by providing more flexibility to Shipwright users and strategy administrators.
```release-note
Add EP on Parameterize Build Strategies
```

Add EP on Build Strategies Parametrization

---

docs/proposals/removal-tekton-resources.md

Related to [Remove usage of Tekton resources #696](https://github.com/shipwright-io/build/issues/696).
This is still provisional, but looking for some feedback on some aspects.
It was honestly ~~complicated~~ impossible at some places to keep this EP isolated. I know this makes it complex, but the design implications of getting rid of the resources at many places brought up topics that are in other EPs/issues/pull requests (listed in the risks section). I decided to touch those topics then. Otherwise, it would have imo been incomplete.
For those interested to see code, here are two PoCs related to this work:
1. [remove_image_resource](https://github.com/shipwright-io/build/compare/master...zhangtbj:remove_image_resource) from @zhangtbj removes the image output resource. It does not follow …

Proposal to remove Tekton resources

---

Makefile

At the moment the only supported OS for building the image of the
controller is "linux". When running targets like "make install-controller",
in a macOS, GO_OS is set to "darwin" which fails building the image.
This PR ensures that if GO_OS is not set, we default to "linux". This
flexibility is not needed, but might be needed in the future. I added
the usage of the origin function on purpose, to make the logic very clear.
```release-note
NONE
```

Ensure GO_OS does not us an OS that isn´t supported

---

docs/buildstrategies.md
docs/proposals/removal-tekton-resources.md
pkg/reconciler/buildrun/resources/remote_artifacts.go
pkg/reconciler/buildrun/resources/runtime_image.go
pkg/reconciler/buildrun/resources/runtime_image_test.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/buildstrategy_samples.go
test/clusterbuildstrategy_samples.go

First part for the [Tekton parameter replacement](https://github.com/shipwright-io/build/blob/master/docs/proposals/removal-tekton-resources.md#risks-and-mitigations) / [Remove usage of Tekton resources #696](https://github.com/shipwright-io/build/issues/696): introducing our own parameters for the output image and source directory. From the longer list in the referenced EP, this is 3 and a part of 1.
Notes:
* for runtime images, there was actually a bug as the rendered runtime image always used the build's output image. This would have failed if the BuildRun specified a different one.
* also related to runtime images, in the `runtimeBuildAndPushStep` function, I intentionally removed the `--context` argument because the generated Dockerfile.runtime does not contain any `COPY` or `ADD` …

Provide well-documented parameters for source and image for the build strategy author

---

.github/workflows/ci.yml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
docs/build.md
docs/buildstrategies.md
docs/configuration.md
pkg/config/config.go
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go

Just dependency updates. Updating Kaniko to [v1.6.0](https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.6.0) and ko to [v0.8.2](https://github.com/google/ko/releases/tag/v0.8.2).
Did not see anything relevant for us in the release notes.
```release-note
Updating build tool versions: Kaniko to v1.6.0 and ko to v0.8.2
```

Update Kaniko to 1.6.0, update ko to 0.8.2

---

Makefile

We recently changed to using `go test` to run the unit tests to not be required to install Ginkgo in prow I think as this sometimes failed and takes some time.
For local tests, I still prefer Ginkgo as its output is having a better readability. Adding a target that does this.
```release-note
NONE
```

Add make target to run unit tests with ginkgo

---

docs/build.md

In the build documentation, we named the reason `SpecSourceSecretNotFound`, but actually is `SpecSourceSecretRefNotFound`. Also fixing the strategy table on that page where the ko link was broken and buildkit missing.
```release-note
Correcting the SpecSourceSecretNotFound reason in the build documentation to SpecSourceSecretRefNotFound
```

Fix typo in reason, fix links

---

docs/buildstrategies.md
pkg/reconciler/buildrun/resources/taskrun_test.go
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
test/buildstrategy_samples.go
test/clusterbuildstrategy_samples.go

Our builds started failing during e2e with this failure in the buildah BuildRun:
```
Logs of container step-buildah-bud:
STEP 1: FROM golang:1.16 AS build
STEP 2: FROM scratch
error creating build container: short-name resolution enforced but cannot prompt without a TTY
```
Using v1.20.1 seems to work, though I have not found some commit in buildah yet that is problematic.
```release-note
Use buildah v1.20.1 in the sample build strategies
```

Pin buildah version

---

.github/pull_request_template.md

Having this in the template consumes a lot of time when opening the pr,
mainly because one needs to manually remove this.
The current instruction on the three flavors of release notes ( none,
notes or notes with action ) are already very clear.
```release-note
NONE
```

Removing PR template block on notes verification

---

.github/workflows/ci.yml
.github/workflows/nightly.yaml
.github/workflows/release.yaml

See https://github.com/imjasonh/setup-ko
This action installs the latest `ko` release, so we don't need to bump
the version ourselves every time there's a release.
We can also pin to a ko release if we want to, to avoid a breakage or
bad version.
/kind cleanup
```release-note
NONE
```

Use imjasonh/setup-ko GitHub Action

---

docs/buildrun.md
pkg/reconciler/buildrun/resources/credentials.go
pkg/reconciler/buildrun/resources/credentials_test.go
pkg/reconciler/buildrun/resources/service_accounts.go

Until now, buildrun is allowed to override output image, but not the secret, making this impossible to work with private repos in buildrun overrides.
This commit fixes that behavior, secret setup by buildrun, is also added to the serviceaccount.
Fixes #684 

Let buildrun override output secret

---

docs/build.md
samples/build/build_source-to-image_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

Fixes https://github.com/shipwright-io/build/issues/638
S2I strategies should make use of $(params.shp-source-context) to
retrieve the path to source code. This param will also use a default value
when users do not specify the spec.contextDir.
The changes on the strategy are also inlined with how Tekton Catalog
does it upstread, see:
https://github.com/tektoncd/catalog/blob/main/task/s2i/0.2/s2i.yaml#L49
```release-note
Ensure contexDir is supported in S2I strategies
```

Add support for contextDir in S2I strategy

---

test/integration/build_to_buildruns_test.go

On a BuildRun with an `Unknown` status, ensure different Reasons are contemplated. The current test case
only includes _Pending_ and _ExceededNodeResources_, but _Running_ is another Reason that could pop.
See flaky test example in [here](https://github.com/shipwright-io/build/runs/2501877220#step:8:104)
_Note_: We could also remove this test case. It is in place to ensure the state of an existing BuildRun that is **running** is not affected when the referenced Build is deleted.
```release-note
NONE
```

Enhance integration flaky test case

---

.github/workflows/base-images.yaml

When I recently introduced the build for the base images, I had not considered that this would run in forks as well. Adding therefore the same `if` condition as in the nightly build.
```release-note
NONE
```

Run daily base images build only in main repository

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml

Fixes https://github.com/shipwright-io/build/issues/718
Instruct the release process to tag images with the release name (e.g., `v0.5.0`)
/kind bug
@adambkaplan @qu1queee 
```release-note
Released container images are automatically tagged with the release version.
```

Tag release images with release version

---

test/integration/integration_suite_test.go
test/utils/environment.go
test/utils/namespaces.go

In the integration tests, we sometimes observe pods that cannot be scheduled because of limited node resources. This happens because we collect namespaces and delete them at the end of the suite. Within those namespaces, there are sometimes pods in Terminating state that still claim resources that pods in a different namespace cannot yet use.
I am changing this to delete the namespace after each test.
```release-note
NONE
```

Cleanup namespace after test case

---

.ko.yaml
Makefile
cmd/git/README.md
cmd/git/main.go
cmd/git/main_suite_test.go
cmd/git/main_test.go

In order to replace Tekton Git resource, a replacement container image
is required that performs a Git clone.
Add Git step command which wraps `git` CLI to clone user repositories
with different authentication options.
```release-note
Added Git command as a replacement for the Tekton Git Resource.
```

Introduce Git step command

---

pkg/reconciler/buildrun/resources/credentials_test.go

Recently, our credentials handling was extended to support the BuildRun to specify a credential for the output image. For this the test cases were also extended. Depending on in which order the test cases in credentials_test run, the buildrun might be nil which is causing a npe:
```
Test Panicked
runtime error: invalid memory address or nil pointer dereference
/home/travis/.gimme/versions/go1.15.11.linux.amd64/src/runtime/panic.go:212
Full Stack Trace
github.com/shipwright-io/build/pkg/reconciler/buildrun/resources.ApplyCredentials(0x234b000, 0xc000122018, 0xc0001808c0, 0x0, 0xc0002d4580, 0x292)
/home/travis/gopath/src/github.ibm.com/coligo/source-to-image/src/build/pkg/reconciler/buildrun/resources/credentials.go:36 +0xa3
github.com/shipwright-io/build/pkg/reconciler/buildrun/resources_te …
```

Ensure buildrun is not nil

---

.github/workflows/release-notes-linter.yaml

Fixes https://github.com/shipwright-io/build/issues/752
```release-note
Add sanity check on release notes content
```

Add sanity check on release notes content

---

test/e2e/common_test.go

Arg, when I reviewed [Retry build creation if build controller did not find build strategy #764](https://github.com/shipwright-io/build/pull/764) with @HeavyWombat, we actually considered if it would make sense to build a fresh Build object for the retry, but then did not do so. But, we have to ... :-( Otherwise it fails like this:
```
[1]     Unable to create build buildpacks-v3-namespaced-2m2qf
[1]     Unexpected error:
[1]         <*errors.StatusError | 0xc0002f9860>: {
[1]             ErrStatus: {
[1]                 TypeMeta: {Kind: "", APIVersion: ""},
[1]                 ListMeta: {
[1]                     SelfLink: "",
[1]                     ResourceVersion: "",
[1]                     Continue: "",
[1]                     RemainingItemCount: nil,
[1]                 },
[1] …
```

Rebuild build object on retry

---

cmd/git/main.go
cmd/git/main_test.go

In the first version of `cmd/git`, it was assumed that Git LFS is installed and
used in the unit tests. As not all environments might have Git LFS, it would
lead to unnecessary unit test failures.
Refactor entry code to only run environment check when executed as the tool.
Add skip code to unit tests to omit tests in case Git LFS is not installed.
```release-note
NONE
```

Skip Git LFS tests in case there is no Git LFS

---

cmd/git/main.go

There seem to be cases where depending on the system and configuration
the Git CLI prompts for username and password. We do not want the
wrapper tool to ever prompt the user as this is breaking the process.
Add `BatchMode` to SSH options to disable prompts.
Set `GIT_TERMINAL_PROMPT` environment variable to disable prompts.
Connect `/dev/null` to Git command (via `nil`) to disable prompts.
Since we control the base image, these issues _should_ only surface in
the context of unit tests.
```release-note
NONE
```

Add settings to disable user prompts

---

deploy/200-role.yaml
deploy/300-rolebinding.yaml

Fixes https://github.com/shipwright-io/build/issues/724
This removes ClusterRole permissions granted to the controller SA, and removes anything it doesn't need (I think). It turns out what we were requesting before was _vastly_ more permissions than we actually needed!
What's left is:
- full read/write/create/delete on all Secrets and SAs (I believe we won't need these after we excise creds-init 🤞)
- list/get Pods
- full read/write/create/delete on shipwright.io/*
- create/get/list/watch on tekton.dev TaskRun only -- no delete or update
- create/get/update on ConfigMaps in the `shipwright-build` namespace only -- this is necessary for leader election
/kind cleanup
- [y] [Set a kind label …

Reduce requested RBAC permissions

---

pkg/git/git.go
pkg/git/git_test.go
pkg/validate/sourceurl.go

With the default implementation of `repo.List`, the timeout seems to be rather
short and there are intermittent context deadline exceeded errors when running
the unit tests under load, or when repeating them over and over again.
Mitigate the error by switching to the list function that accepts a context. It
was added recently and privides the possibility to define a different timeout.
Refactor related code to make it more compact by removing superfluous returns.
In order to be able to test and reproduce it, I used Ginkgo with the `-untilItFails`
and it started to be flaky after about 20 to 25 repetitions. With the code updates,
I was able to run it without issues for over 100 times, before canceling the test run.
See [the contributor …

Mitigate context deadline exceeded issue

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml

That repo is unmaintained and archived.
Instead, use the GitHub CLI that's pre-installed in the GitHub Actions
execution environment and has simple CLI for uploading release assets to
existing releases.
/kind cleanup
Builds on https://github.com/shipwright-io/build/pull/766
cc @SaschaSchwarze0 
```release-note
NONE
```

Don't rely on actions/upload-release-asset

---

.github/pull_request_template.md
.github/workflows/ci.yml
.github/workflows/sanity-checks.yaml
docs/development/testing.md

As we discussed in the issue: https://github.com/shipwright-io/build/issues/666
We plan to switch the default branch from `master` to `main` branch.
I already provide PR (https://github.com/shipwright-io/build/pull/667) to change the external link to main branch.
This PR is used to change the branch in the internal flow and document:
- Change to use main branch in github action flow
- Change the internal documents to use the link of main instead of master
I have not created the `main` branch now (To avoid the new PR merge problem).
**We should do some preparation actions BEFORE merge this PR!!!**
- Create a `main` branch
- Switch all PRs to main branch: https://github.com/shipwright-io/build/pulls
- Switch the default branch from `master` to `main` in the repo settings
So please the …

Change to main branch in the internal flow

---

hack/release.sh

Adding the SHA that trigger the build of https://quay.io/repository/shipwright/shipwright-operator as a label. This is mainly to have a clear mapping to the commit on this same repository.
_Note_: Wondering if we should use `quay.expires-after` label, for the nightly images, we can set a max lifetime for those ones, so that we keep pruning them. 
```release-note
Add SHA label to SHP controller img
```

Add commit SHA label to SHP image

---

docs/buildstrategies.md
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml

Add `securityContext` to BuildKit cluster build strategy samples, which includes `allowPrivilegeEscalation` for `/usr/bin/new{u,g}idmap` binaries used by `rootlesskit` as well as explicit `runAs...` settings.
Simplify `prepare` step command.
Unify flag usage to have the same style for all arguments.
```release-note
NONE
```

Add security context to BuildKit strategy sample

---

test/e2e/common_test.go

With the new git command, we changed the behavior from warning to error if a http source URL is referencing an SSH secret. I am adopting the e2e test code accordingly to only assign the source secret when necessary. This was uncovered before because the private repo tests are not yet enabled for the CI-driven e2e test run.
```release-note
NONE
```

Only add secret to build for private repos

---

.github/workflows/ci.yml
hack/install-kind.sh
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

Two small dependency updates:
1. Using ko v0.8.3 in the build strategy
2. Using the newer 1.20.7 kind kubernetes image in integration and e2e tests
```release-note
Update sample build strategy to latest ko version
```

Update ko and tested Kubernetes version

---

docs/proposals/enable-local-source-code-support.md

Fixes #716 
Provide the enhancement proposal document around the local source code feature.
A prototype example is documented in [here](https://github.com/qu1queee/cli/tree/qu1queee/crud_cmd#readme). This should allow you to run a BuildRun using local source code feature via the Shipwright/CLI.
```release-note
Add EP on enabling local source code feature
```

Add EP on enabling local source code support

---

cmd/git/main.go

The credential look-up routine only set up the Git command line flags for the
Git `clone` command, but not for the subsequent `submodule` command. When a
user tried to use a repository with a submodule that required authentication as
well, the Git step failed.
Change code to store the respective credential command line arguments into a
separate slice so that it can be used for different Git commands.
```release-note
Fixed issue with the source step failing for Git repositories that contain submodules that require authentication.
```

Fix Git submodule update issue with SSH creds

---

pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml

When defining a build strategy, the author defines which images are to be used. For certain tools, beside immutable image tags for specific versions, there are also nightly or latest-like tags available that are not using `latest` themselves. In such a a case, [Kubernetes sets the image pull policy implicitly to `IfNotPresent` and does never reload these images](https://kubernetes.io/docs/concepts/configuration/overview/#container-images) so that they get outdated. Examples in our context are:
* [moby/buildkit:nightly-rootless](https://hub.docker.com/r/moby/buildkit/tags)
* [paketobuildpacks/builder:full](https://hub.docker.com/r/paketobuildpacks/builder/tags)
In case of `latest`, Kubernetes would always contact the registry to check if there is a newer version. To enforce the very same …

Map ImagePullPolicy from build strategy step to TaskRun step

---

docs/proposals/removal-tekton-resources.md
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml

There were some build strategies remaining where the image digest result has not yet been provided. Doing this here:
- For BuildKit, I am using the brand-new `--metadata-file` field. Thanks @qu1queee for pointing me to [Add --metadata-file flag to output build metadata #2095](https://github.com/moby/buildkit/pull/2095). Also switching from master-rootless to nightly-rootless which is the same image without the `master` term.
- For Buildah, I use the `buildah images` command with the [`--format` option to access the `.Digest` property](https://github.com/containers/buildah/blob/v1.20.1/docs/buildah-images.md#options). I spent some time to see if I can also get the image size here. Unfortunately, the `.Size` property of the same command is [always …

Add image digest result to remaining sample build strategies

---

README.md

When a user tries to copy a code block using the "copy" button, the preceding '$' gets copied too and defeats the purpose of the shortcut button. Hence proposing the removal of the preceding '$' from code blocks.
```release-note
NONE
```

Removing preceding '$' from code blocks

---

.gitignore
2021-roadmap.md
cmd/git/README.md
deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
deploy/crds/shipwright.io_buildstrategies.yaml
deploy/crds/shipwright.io_clusterbuildstrategies.yaml
docs/tutorials/README.md
docs/tutorials/building_with_buildkit.md
docs/tutorials/building_with_buildpacks.md
docs/tutorials/building_with_kaniko.md
hack/install-controller-gen.sh
images/git/Dockerfile

It seems like the repo has gotten out of sync with generated code, which led to some unnecessary diffs in some changes I was working on. Mostly just copyright headers and diffs from controller-gen `v0.4.1` -> `v0.5.0`.
Should we have a CI check that tries to check that codegen is up-to-date?
Also git-ignore binaries generated by `go build ./cmd/...`.
/kind cleanup …

Re-run make generate and generate-crds

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
docs/build.md
pkg/apis/build/v1alpha1/build_types.go
pkg/reconciler/buildrun/resources/runtime_image.go
pkg/reconciler/buildrun/resources/runtime_image_test.go
pkg/validate/runtime.go

Marks the `runtime` field as `Deprecated` in docs and Go doc comments
First step of [SHIP-0002](https://github.com/shipwright-io/community/blob/main/ships/0002-deprecate-runtime.md)
/kind cleanup
- [y] Includes docs if changes are user-facing
```release-note
Mark the runtime feature as deprecated
```

Add deprecation warnings for .spec.runtime

---

.github/workflows/verify.yaml

Inclusive naming guidelines [recommend against the term "sanity checks"](https://inclusivenaming.org/language/evaluation-framework/#is-the-term-overtly-ableist-or-pejorative-to-neurodiverse-or-disabled-people)
Runs that don't have a name will be shown as, for example, `run make govet` in failure emails, which is just about as descriptive as you can get, and shorter to write.
edit: Also add a new check that `make generate-crds` is up-to-date.
Fixes #798 
/kind cleanup
See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRI …

Rename basic static checks to "Verify"

---

.github/workflows/release.yaml

The variable `${{ github.events.input.release }}` is invalid, it should be `inputs.release` 🙄 
/kind cleanup
```release-note
NONE
```

Fix typo in release.yaml

---

.github/workflows/release.yaml

🤦 
/kind cleanup
```release-note
NONE
```

Fix another typo in release.yaml

---

.github/workflows/release.yaml
.gitignore

This will open a new PR based on README updates.
The PR will contain updates that point to the latest tag created when shipping a new release. This should avoid people committing manual Readme updates, see examples:
- https://github.com/shipwright-io/build/commit/33175e4a1eeccf23239676ae54a46533ee0e58be
- https://github.com/shipwright-io/build/commit/d34799619ae22294189c138fd064c27279c681ce
- https://github.com/shipwright-io/build/pull/802
Example of PR generated with changes: https://github.com/qu1queee/build/pull/24
```release-note
Enhance CI with automated README updates
```

Extend CI with README updates

---

.github/workflows/ci.yml
deploy/200-role.yaml
test/data/build_buildpacks-v3_golang_delete_cr.yaml
test/e2e/e2e_test.go
test/kind/config.yaml

- Update the admission controllers enabled for KinD so that it more
closely aligns with enterprise Kubernetes distributions.
- Add RBAC needed for the `OwnerReferencesPermissionEnforcement` admission controller.
With this admission controller enabled, service accounts need to have
explicit permission to delete objects that they set owner references on.
When `blockOwnerDeletion` is set on an owner ref, the controller must
also have explicit permission to update the finalizer subresource of the
parent object.
/kind bug
Fixes #806 
See also https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
for details on coding conventions, github and …

Fix RBAC so Shipwright Build works with the OwnerReferencesPermissionEnforcement admission controller

---

images/git/Dockerfile

Add `--nodocs` to reduce the image size.
```release-note
NONE
```

Tweak Git image size

---

cmd/git/main.go

Add `--depth` flag to be able to configure the shallow depth setting.
Add depth setting to Git submodule command to improve loading times.
Fixes #785
```release-note
Fixed issue in source retrieval code that led to slow loading times compared to the previous implementation.
```

Improve submodule loading

---

pkg/reconciler/buildrun/resources/conditions.go
test/integration/buildruns_to_taskruns_test.go

For our downstream service, we provide troubleshooting documentation for the user to determine the root cause of a failure. We there separate failures by step name. Since we rewrote the BuildRun message to not anymore contain the TaskRun reason, the step name is only shown at the end of the message in the `kubectl logs` command while we include the pod name earlier as well. I am slightly making a message change to also include the name of the step at the beginning of the message and not just in the `kubectl logs` example which makes it easier to understand and extract the relevant data.
```release-note
The message field of the Succeeded condition of a failed BuildRun now includes the name of the step that has failed
```

Add step name to message

---

hack/install-controller-gen.sh

In order to avoid using a different version than defined, the `controller-gen`
version should be checked. Add simple check whether the versions match.
```release-note
NONE
```

Add check for controller gen version

---

hack/install-kubectl.sh

Kubectl binary download script modification has been done to accommodate all Linux distributions.
```release-note
NONE
```

Add Kubectl binary download script for all Linux distributions

---

hack/install-kubectl.sh

The script was recently modified to use `curl` for the download which is nice as it is package manager independent. Making it supporting arm64.
```release-note
NONE
```

Enable script for arm64

---

cmd/git/main.go
images/git/Dockerfile

We received end user feedback on some Git step output messages being misleading, which might take the focus away from the actual error message:
- Omit warnings in Git+SSH use cases.
- Add Tekton related `.docker` directory to base image to avoid warning.
- Avoid misleading `.ssh` directory message by putting it into the base image.
```release-note
Updated Git download step to avoid misleading warnings and messages.
```

Declutter Git step log output

---

cmd/git/main.go
cmd/git/main_test.go

The current output of the Git step was using the log style of the controller,
which is configured to be machine consumable. However, the output should be
more aligned with the output that is created by other steps. Tools like Kaniko
or Buildpacks produce more human style output. This is also feedback that we
received from users, especially in the case when the source retrieval failed for
some reason, for example TYPO of the branch name or similar.
Replace `ctxlog` with `log` and simplify log output to be human friendly.
Add new end message that contains all relevant details, including HEAD info.
For reference:
- Before:
```json
{"level":"info","ts":1626871924.300413,"logger":"git","msg":"ssh","path":"/usr/bin/ssh","version":"OpenSSH_8.1p1, LibreSSL 2.7.3"} …
```

Increase log output readability

---

docs/build.md
docs/buildrun.md
pkg/apis/build/v1alpha1/build_types.go
pkg/reconciler/build/build.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/resources/conditions.go
pkg/validate/buildname.go
pkg/validate/validate.go
test/integration/build_to_buildruns_test.go
test/integration/buildruns_to_taskruns_test.go

We got user feedback that build and buildrun names can be specified lead to controller error.
This is caused by the fact that the names used in the label they are strict in their length.
Add validation to enforce specific length for build and buildrun names.
```release-note
Added validation to make sure that Build and BuildRun names follow the required character limits
```

Enforce label name limits in resource names

---

docs/build.md
docs/buildrun.md

Just stumbled over our docs link there which is going to Kubernetes' limitations for a label key. But, relevant are the limitations of label values. Updating the link.
```release-note
NONE
```

Update links to point to restrictions for a label value

---

.github/workflows/mirror-images.yaml

In order to be independent of DockerHub images in the samples, we should aim
for having equivalent images available in `quay.io`.
Add daily mirror job for required images.
```release-note
NONE
```

Add shipwright sample pre-req image mirroring

---

test/e2e/common_suite_test.go
test/e2e/e2e_bundle_test.go

The bundle end to end test fails for setups where the output image target
requires credentials to allow the push operation.
Add code to use `TEST_IMAGE_REPO_SECRET` to specify an output secret.
```release-note
NONE
```

Fix output image credentials for bundle E2E

---

docs/buildrun.md

Add newline to avoid this. Introduced in https://github.com/shipwright-io/build/pull/858, I wanted to block that PR but it was merged already.
See current [table](https://github.com/shipwright-io/build/blob/main/docs/buildrun.md#understanding-the-state-of-a-buildrun) with the issue.
```release-note
NONE
```

Ensure Note msg doesn't belong to the conditions Table

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml

If not set, the Go version in GitHub Actions seems to default to `1.15` at the moment. With recent changes, Shipwright requires Go version `1.16` to compile.
Set Go version to `1.16` in GitHub Actions.
```release-note
NONE
```

Use Go `1.16` in GitHub Actions

---

.github/workflows/mirror-images.yaml

The newly introduced mirror GitHub Action does not work. It looks like the authentication is not working even though the output looks as expected. In order to rule out unexpected side effects, change the login style to the one in the other GitHub Actions that log into `quay.io`.
```release-note
NONE
```

Update mirror action config

---

.github/workflows/ci.yml

All CI tests run on `ubuntu-latest` using (currently) Go 1.16.x -- there's no need to specify these in matrix variables.
/kind cleanup
```release-note
NONE
```

[ci] Remove unnecessary matrix values

---

docs/configuration.md
pkg/config/config.go
pkg/config/config_test.go

We recently removed the runtime image feature. It had a configuration option that we forgot to remove, the Kaniko image that was used to build the runtime image. Cleaning this up.
```release-note
NONE
```

Remove Kaniko image configuration of runtime image feature

---

.gitignore
HACK.md

Add the `-z`  flag for `oc policy add-role-to-user` otherwise, the command complains about user not found. 
```release-note
NONE
```

Fixing oc policy command in HACK.md

---

.github/workflows/verify.yaml
Makefile
hack/generate-fakes.sh
hack/verify-generate.sh

Introduce `verify-generate.sh` script to check for uncommitted changes.
Now, with Go `1.16`, switch to `go install` for tools in preparation of the `go get` install deprecation.
Change `counterfeiter` location from needing to be under `GOPATH` to be anywhere as long as it is in the `PATH`.
Fixes #453
```release-note
NONE
```

Add `verify-generate.sh` script

---

cmd/bundle/main.go
cmd/bundle/main_test.go
cmd/git/main.go
cmd/git/main_test.go
cmd/mutate-image/main.go
cmd/mutate-image/main_test.go

To allow to pre-pull the BuildRun supporting images in a DaemonSet and run the command they use there to verify that the binary works, we need a way to run them without performing real work but to still return exitCode 0. Adding a `--help` flag for this purpose.
```release-note
NONE
```

Add help flag to supporting binaries

---

docs/build.md

Since a while already, all our strategies support the contextDir. Buildah was the last one. Fixing this in the docs.
```release-note
Correcting the statement about the contextDir which is supported in all sample build strategies
```

Remove incorrect statement about contextDir limitation

---

cmd/mutate-image/main.go

We were not specifying the minimum TLS version that is acceptable in mutate image code.
Update TLS client configuration with TLS 1.2.
```release-note
NONE
```

Fix the gosec finding TLS MinVersion too low

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml
hack/release.sh

Fixes #801
Fixes #877
Some pipeline changes:
* Create a sample-strategies.yaml in the release.sh script containing all cluster build strategies
* Publish the sample-strategies.yaml in a release and nightly release
* Using `crane copy` to create the latest tag for our images during the nightly build
```release-note
Nightly and normal releases now incluse a sample-strategies.yaml
```

Publish latest tag during nightly release / publish sample strategies

---

cmd/bundle/main.go
cmd/bundle/main_test.go
cmd/git/main.go
cmd/git/main_test.go
cmd/mutate-image/main.go
cmd/mutate-image/main_test.go
deploy/crds/shipwright.io_buildruns.yaml
docs/buildrun.md
docs/buildstrategies.md
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/bundle/bundle.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/resources/mutate.go
pkg/reconciler/buildrun/resources/results.go
pkg/reconciler/buildrun/resources/results_test.go
pkg/reconciler/buildrun/resources/sources.go
pkg/reconciler/buildrun/resources/sources/bundle.go
pkg/reconciler/buildrun/resources/sources/git.go
pkg/reconciler/buildrun/resources/sources/git_test.go
pkg/reconciler/buildrun/resources/sources/utils.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
test/e2e/e2e_bundle_test.go
test/e2e/e2e_image_mutate_test.go
test/e2e/e2e_test.go
test/e2e/validators_test.go

Reference  https://github.com/shipwright-io/community/pull/13
Add git commit author result for git source step
Add bundle image digest result for local source code step
Add a function to surface TaksRun results to BuildRun
This PR only includes a subset of the [enhancements](https://github.com/shipwright-io/community/blob/main/ships/0023-surface-results-in-buildruns.md#strategy-results-api-proposal) called for, those are:
- [Build Results Sources API Proposal](https://github.com/shipwright-io/community/blob/main/ships/0023-surface-results-in-buildruns.md#build-results-sources-api-proposal) (excluded surfacing the http source type results since it is an MVP implementation)
- [Build Results Output API Proposal](https://github.com/shipwright-io/community/blob/main/ships/0023-surface-results-i …

Surface Step Results in BuildRun Status

---

test/e2e/validators_test.go

Check Tekton objects can be accessed in the validateBuildRunResultsFromBundleSource function.
Check Tekton objects can be accessed in the validateBuildRunResultsFromGitSource function.
```release-note
NONE
```

Only run the TaskRun checks if Tekton objects can be accessed

---

hack/install-kind.sh

Making two changes:
1. Check the existence of kind somewhere on the path and not just in GOPATH.
2. Make sure the installation does not run inside the build directory as this would update the go.mod there.
```release-note
NONE
```

Fix kind installation

---

cmd/git/main.go

There are some cases where the Git step binary is used in an environment
with a Git CLI that does not support the `--no-tags` flag since this was only
introduced in newer versions of Git. This only occurred in unit tests so far as
we are in control of the base image used for the Git step.
Add check to verify whether the `--no-tags` flag can be used.
```release-note
NONE
```

Use `--no-tags` only when available

---

go.sum

The `k8s.io/kubernetes` seems to be added by mistake as it is used nowhere
based on `go mod why k8s.io/kubernetes` and the fact that removing it does
not lead to any changes when running a build.
Remove `k8s.io/kubernetes` from `go.sum`.
```release-note
NONE
```

Remove stale `go.sum` `k8s.io/kubernetes` entry

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
docs/build.md
docs/buildrun.md
go.sum
pkg/apis/build/v1alpha1/build_types.go
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
pkg/bundle/bundle_suite_test.go
pkg/env/env.go
pkg/env/env_test.go
pkg/reconciler/build/build.go
pkg/reconciler/build/build_test.go
pkg/reconciler/buildrun/buildrun_test.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
pkg/validate/envvars.go
pkg/validate/envvars_test.go
pkg/validate/validate.go
test/build_samples.go
test/buildrun_samples.go
test/buildstrategy_samples.go
test/bundle/README.md

This pull request will give developers the abilty to add environment variables to build strategy steps. Conversely, this proposal will also give build strategy authors the ability to fix the values of environment variables in build steps or provide non-empty default values.
```release-note
Developers can now add Environment Variables to the Spec section of their Builds and BuildRuns.
The Environment Variables will be added to all Steps of the chosen BuildStrategy, though any conflicts
will result in a failed TaskRun.
```

SHIP-0004: Build Environment Variables

---

HACK.md
README.md
docs/buildrun.md
docs/buildstrategies.md
docs/development/testing.md
docs/metrics.md
docs/tutorials/README.md
docs/tutorials/building_with_buildkit.md
docs/tutorials/building_with_buildpacks.md
docs/tutorials/building_with_kaniko.md

Stumbled over some broken link while writing the 0.6 blog post. Some updates simply change from absolute to relative links because linters prefer this.
```release-note
NONE
```

Fix documentation links

---

samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
test/data/build_buildpacks-v3_golang_cr+env.yaml
test/data/build_buildpacks-v3_golang_cr_env.yaml
test/e2e/e2e_test.go

We noticed a shortcoming of the `Buildpacks` build strategy: as we bypass pack, the environment variables are not working.
Extend the `buildstrategy_buildpacks-v3_cr.yaml` with the script to process environment variables.
Add a test case to verify the environment variables working with the `Buildpack` build strategy.
**Note: This PR has a dependency with https://github.com/shipwright-io/sample-go/pull/6. The test cases will only pass after merging the https://github.com/shipwright-io/sample-go/pull/6**.
```release-note
The Buildpacks sample build strategies now pass environment variables to the the …
```

Extend the Buildpack strategy to work with the environment variables

---

cmd/bundle/main_test.go
cmd/git/main_test.go

Add temporary redirect so that the output of the `--help` flag is omitted.
```release-note
NONE
```

Omit output during unit test

---

.github/workflows/mirror-images.yaml

Signed-off-by: Jason Hall <jasonhall@redhat.com>
Well this is embarrassing. 🤦 
It turns out it's much more reliable to mirror images using `crane cp` than it is just `echo`ing the `crane cp` command to stdout.
Progress toward #913
/kind bug
```release-note
NONE
```

Actually mirror images using crane

---

cmd/git/main.go
cmd/git/main_test.go
deploy/crds/shipwright.io_buildruns.yaml
docs/buildrun.md
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/reconciler/buildrun/resources/sources/git.go
pkg/reconciler/buildrun/resources/sources/git_test.go
pkg/reconciler/buildrun/resources/taskrun_test.go
test/e2e/validators_test.go

If user doesn't specify revision in Build object, then default
branch is used.
This patch adds support for adding the branch name in BuildRun results
if revision is not specified in Build Object.
Fixes #923
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
```release-note
Adds branchName in buildrun results if revision is not specified in Build
```

Adds branchName in buildrun results if revision is not specified

---

.github/workflows/nightly.yaml

Progress toward #907 
Now that nightly released images are pushed to ghcr.io, we can sign them using `cosign`. This also annotates the signature with the commit SHA and GitHub run ID and attempt number (in case there are multiple attempts), so consumers can trace back to the workflow run that produced the image and signature.
```release-note
NONE
```
/kind feature

Sign nightly released images

---

.github/workflows/verify.yaml
Makefile

Downstream, we got a new tool we need to use for complience checks: [gosec](https://github.com/securego/gosec). Shipwright Build is looking fine. Adding it to our verification so that it stays green.
```release-note
NONE
```

Run gosec as part of the verify action

---

.github/workflows/ci.yml

In this PR, the use of paths-ignore is introduced to reduce time check on the files that don't play any role with controller code space! Since Github actions allow to have a paths-ignore while running the actions, here the changes have been made to the `ci.yml` file, which deals with Unit, Integration, and E2E Tests.
Being a newbie at this and the project, there must be more files that need to be added that's why leaving this as a WIP for more discussion on this issue!
Fixes #921 
```release-note
NONE
```

Usage of paths-ignore in github actions to reduce time check in e2e tests

---

cmd/git/main.go
cmd/git/main_test.go
deploy/500-controller.yaml
docs/configuration.md
pkg/config/config.go
pkg/reconciler/buildrun/resources/sources/git.go

There is use case that pops up more often than others and this is that a user wants to build a private repository that contains a submodule, which itself is also a private repository. Sometimes, the submodule is configured using a HTTPS URL while the main repository uses Git+SSH. This leads to errors in the Git step, because the private submodule cannot be loaded due to missing access credentials. Obviously, the HTTPS URL does not accept the Git private key that is configured. The typical local solution is to setup an `insteadOf` URL rewrite rule in the Git config to dynamically translate the URL types. This PR brings the same feature to the Git step. It is disabled by default.
- Add Git wrapper command line flag to enable setting up Git config URL rewrite.
- Add environment variable …

Introduce Git config URL rewrite option

---

cmd/git/main.go
cmd/git/main_test.go

Using `git config` has the disadvantage that it also changes the Git config
in the development system when running the test cases.
Rename `addtlCredArgs` to `addtlGitArgs` to be more generic.
Use `-c` Git flag to supply specific configuration instead of using Git config.
The Git URL rewrite logic was located outside of the credentials section of the
code, which means it was used in any case. However, it does not make sense to
be used in combination with a HTTPS URL and basic auth.
Move section as-is into the private key section and setup.
Fix credentials checks to allow for the combination of:
- HTTPS URL,
- private SSH key, and
- Git URL rewrite enabled.
for details on coding conventions, github …

Fix Git URL rewrite issue for HTTPS URLs

---

pkg/reconciler/buildrun/resources/sources/git.go

The flag name was changed during the initial commit, but not updated in the
controller code.
Fix name to be `"--git-url-rewrite"`.
```release-note
Fixed incorrect flag name for Git step in controller code.
```

Fix incorrect flag name

---

docs/buildrun.md
pkg/reconciler/buildrun/resources/service_accounts.go
pkg/reconciler/buildrun/resources/service_accounts_test.go

Fixes #892 
This removes the compatibility code that removes a generated service account with the `-sa` suffix on BuildRun completion created by old releases. Should a user have a running old BuildRun or make a large version jump, then the owner reference will make sure the service account gets deleted on BuildRun deletion.
```release-note
Removing compatibility code that deleted generated service accounts with the naming pattern from before v0.6
```

Remove compatability code to remove service account with -sa suffix

---

.github/workflows/release.yaml

Progress toward #907 
This also annotates the signature with the commit SHA and GitHub run ID and attempt number (in case there are multiple attempts), so consumers can trace back to the workflow run that produced the image and signature.
/kind feature
```release-note
Released images are signed with an ephemeral key using cosign
```

Sign released images

---

.github/workflows/ci.yml
test/integration/buildruns_to_taskruns_test.go

Investigated why integration tests failed in GitHub action. As discussed below, changed some test cases to use polling instead.
```release-note
NONE
```

Fail in case there is an error event

---

.github/workflows/verify.yaml
.golangci.yaml
Makefile

Use [golangci-lint](https://golangci-lint.run/) in [verify.yaml](https://github.com/shipwright-io/build/blob/main/.github/workflows/verify.yaml)
Fixes #948 
```release-note
NONE
```

Use golangci-lint in CI

---

.github/workflows/ci.yml
pkg/reconciler/buildrun/resources/conditions.go
test/integration/build_to_buildruns_test.go
test/integration/buildruns_to_taskruns_test.go
test/integration/integration_suite_test.go
test/utils/taskruns.go

Adjusted ignore messages for staticcheck to also work for golangci-lint. Refactored tests to no longer use the deprecated API and deal with the errors in decoding watch events.
```release-note
NONE
```

Adjust ignore statements for golangci-lint and fix failing tests

---

samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

The creation of a file named PATH (corresponding to `PATH` system environment) inside `/platform/env` caused failure for [python source with requirements.txt](https://github.com/Azure-Samples/python-docs-hello-world) when building with the Buildpack strategy.
Update scripts in the Buildpack strategies samples with an array of blocklist system environments.
```release-note
Fix the Buildpack build strategies failing for python source with a requirements.txt that failed during pip install
```

Add the list of environments to be blocked on the creation of files inside /platform/env

---

pkg/reconciler/buildrun/resources/failure_details.go
pkg/reconciler/buildrun/resources/failure_details_test.go
test/buildstrategy_samples.go
test/integration/buildstrategy_to_taskruns_test.go

Currently the failure extraction is faulty. It triggers on containers with exit code 0. However, a failed container has a non-zero exit code. It adds integration test with custom strategy that guarantees failure and error results to further strengthen confidence in the feature.
```release-note
NONE
```
/kind bug

Add integration test for failure reasons

---

test/integration/buildstrategy_to_taskruns_test.go

Removes unintended [shadowing](https://github.com/shipwright-io/build/blob/517165e62f4b1deba49c02af590ab047fb69dcb1/test/integration/buildstrategy_to_taskruns_test.go#L404) of global variable that lead to nil pointer dereferencing in the [cleanup](https://github.com/shipwright-io/build/blob/main/test/integration/buildstrategy_to_taskruns_test.go#L37) call in of the integration tests.
Observed in CI pipeline: https://github.com/shipwright-io/build/runs/4738311179?check_suite_focus=true#step:9:98.
```release-note
NONE
```

Fix failing integration test

---

.github/workflows/base-images.yaml
images/waiter/Dockerfile

A #934 spinoff pull-request, to introduce the Waiter's base-image. The changes here are part of [SHIP-0021 Local Source Upload](https://github.com/shipwright-io/community/blob/95ee6e53caa489a8db2e979bafba9d1ae2020bb6/ships/0021-local-source-upload.md).
```release-note
NONE
```

[BUILD-372] SHIP-0021: Waiter's Base Image

---

cmd/git/main.go
cmd/git/main_test.go
docs/buildrun.md
pkg/git/error_parser.go
pkg/git/error_parser_test.go
pkg/reconciler/buildrun/resources/sources/git.go
pkg/reconciler/buildrun/resources/sources/git_test.go
pkg/reconciler/buildrun/resources/taskrun_test.go
test/data/build_non_existing_repo.yaml
test/data/buildrun_non_existing_repo.yaml
test/e2e/e2e_test.go

This PR implements a parser and interpreter for git errors in stdout and surfaces them as error results.
```release-note
NONE
```

Add git error parser and surfacing of git errors

---

README.md

During our last release, the GitHub action failed to update the pull request for the readme updates. We somehow forgot to do it manually ...
```release-note
NONE
```

Add v0.7.0 release to README

---

pkg/config/config.go
pkg/config/config_test.go

Minimal example to reproduce: 
```go
package config
import (
"os"
"testing"
)
func TestOverrideBug(t *testing.T) {
cfg := NewDefaultConfig()
os.Setenv("GIT_CONTAINER_IMAGE", "git-image")
cfg.SetConfigFromEnv()
if cfg.GitContainerTemplate.Image != "git-image" {
t.Fatal("override did not set git image")
}
os.Setenv("MUTATE_IMAGE_CONTAINER_TEMPLATE", `{"image":"mutate-image"`)
cfg.SetConfigFromEnv()
if cfg.GitContainerTemplate.Image != "git-image" {
t.Fatalf("mutate image overrides git-template")
}
}
```
Fixes bug by overriding the right entry of `config` instead of the `GitContainerTemplate`.
It additionally adds previously missing unit tests to make sure that override for `mutate-image` is sound. …

Fix image override bug for mutate-image in config

---

HACK.md

When I recently updated the Kubernetes dependency and with it controller-gen and controller-runtime, I by mistake put the controller-runtime version into HACK.md where we mention the controller-gen version. :-( Correcting this.
```release-note
NONE
```

Correct controller-gen version in HACK.md

---

samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml

I cherry-picked the changes from [update buildah image to v1.23.1 #951](https://github.com/shipwright-io/build/pull/951). In my local tries, the BuildAh build was hanging as well like in the GitHub action runs. No indication for me why. Low resources was my guess, and with more resources it succeeded.
fyi @wanjunlei
```release-note
Update Buildah to 1.23.1, introduce parameters to setup registry configuration
```

Update BuildAh to v1.23.1

---

Makefile

The [Waiter test cases](https://github.com/shipwright-io/build/blob/main/cmd/waiter/main_test.go) cannot run in parallel because they use a lock file with a hard-coded name. Because of this I am turning off parallel runs in `make test-unit-ginkgo`. We should undo this again with Ginkgo 2. See https://github.com/shipwright-io/build/issues/874#issuecomment-1017531311
```release-note
NONE
```

Turn of parallel tests in test-unit-ginkgo

---

Makefile

Stop running `go mod vendor` before `build` and `local` targets.
```release-note
NONE
```

Avoid Unnecessary `go mod vendor`

---

samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml

Updating our outdated sample build strategy tools to recent versions before our upcoming release.
```release-note
Update build strategy tool: Trivy to 0.22.0, go-containerregistry/crane to 0.8.0
```

Update Trivy to 0.22.0, update go-containerregistry/crane to 0.8.0

---

.github/draft_release_notes.sh

During v0.8.0 release generation, the community decided we wanted to break away from Tekton's practice and add action required release notes to the release notes.
/kind cleanup
- [n/a ] Includes tests if functionality changed/was added
- [ n/a ] Includes docs if changes are user-facing
- [ /] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [/ ] Release notes block has been filled in, or marked NONE
```release-note
NONE
```

allow action required release notes

---

hack/release.sh

In the release process, we delete namespaced build strategies to exclude them from the sample-strategies.yaml. This deletion caused the readme pr creation to pick up those deletions. I am changing the release script to restore those files.
```release-note
NONE
```

Restore files that were temporarily deleted

---

deploy/100-namespace.yaml
deploy/200-role.yaml
deploy/300-rolebinding.yaml
deploy/400-serviceaccount.yaml
deploy/500-controller.yaml

Nit: Use YAML document separator `---` in all deploy YAMLs consistently.
```release-note
NONE
```

Use YAML document separator in all deploy YAMLs

---

docs/build.md
docs/buildrun.md
docs/buildstrategies.md
docs/tutorials/building_with_buildkit.md
docs/tutorials/building_with_buildpacks.md
docs/tutorials/building_with_kaniko.md

This is coming from me reviewing latest features that belong to the v0.8.0 blog post.
Adding minor docs improvements:
- Fix typo from `spec.parameteres` to `spec.parameters`
- Sync the usage of `.Status.Something` or `.status.something` into lower-cases only.
- Fix other typos
```release-note
NONE
```

Improve docs

---

samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
test/e2e/e2e_bundle_test.go
test/e2e/e2e_image_mutate_test.go
test/e2e/e2e_test.go
test/e2e/validators_test.go

I am changing the recently added registry configuration related parameters to arrays. I am adding build-arg support. I am using registries-insecure to also define whether tlsVerify on push should be set to false. And I am writing error details when the context dir or the Dockerfile do not exist.
Fixes #988
```release-note
action required: The Buildah sample build strategy now supports build-args. The registry related parameters were changed to arrays in favor of comma-separated strings. You need to update your builds accordingly.
```

Modernize Buildah sample build strategy

---

samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

Buildpacks defines versioned api specification that allows them to bridge the knowledge gap between the [lifecycle](https://buildpacks.io/docs/concepts/components/lifecycle/) and the independent buildpack implementations. More specifically it allows the lifecycle utility to enable features based on the known api version and thus staying backward-compatible.
The lifecycle utility receives the api version from the environment variable `CNB_PLATFORM_API`. Whenever this variable is not present, it assumes per default that the version is `0.3`. Consequently, the lifecycle&rsquo;s exporter ignores the default process determined in the build step and sets the entrypoint of the resulting image to the lifecycle&rsquo;s launcher executable ([code …

Add parameterized CNB_PLATFORM_API to buildpacks strategy

---

cmd/bundle/main_test.go
pkg/reconciler/buildrun/resources/results_test.go
test/e2e/e2e_bundle_test.go

With https://github.com/shipwright-io/sample-go/pull/9 merged and the image available, the `quay.io` based image can be discontinued.
Use `ghcr.io/shipwright-io/sample-go/source-bundle:latest` as the default source bundle example image.
Fixes #991
```release-note
NONE
```

Replace `quay.io` source-bundle with `ghcr.io`

---

docs/buildstrategies.md
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
test/data/build_buildkit_cr_insecure_registry.yaml
test/e2e/e2e_test.go
test/e2e/validators_test.go

Adding the platforms parameter to the BuildKit sample build strategy to support multi-platform builds.
```release-note
The BuildKit sample build strategy now supports a `platforms` parameter to enable multi-platform builds
```

Enable multi-platform builds for BuildKit sample build strategy

---

README.md
docs/buildstrategies.md

Two small documentation updates:
1. Our README containes a link to the meeting minutes. I am removing the is:open condition from the query because otherwise one only sees an empty list most of the time.
2. [BuildAh is supported on all platforms that we also support](https://quay.io/repository/buildah/stable?tab=tags), I also ran it on arm64 at some point in the past. Therefore adjusting the supported platforms.
```release-note
NONE
```

Documentation updates

---

Makefile

Allows a user/automation to set the path to the ginkgo cli in any make task using the `GINKGO` variable.
Adjusts the `ginkgo` task to not install the ginkgo cli whenever the `GINKGO` is set externally. 
```release-note
NONE
```

Allow setting ginkgo cli path for Makefile tasks

---

.github/workflows/mirror-images.yaml

In order to seamlessly update for example the Go version in the samples, we have to make sure that old and newer versions are mirrored.
Add Go version `1.17` and `1.18`.
Add Node.js version `14` and `16`.
Add Python version `3.9`.
```release-note
NONE
```

Add additional versions to image mirror list

---

Makefile

Remove `GO111MODULE` variables as this is the default now.
Add annotation to omit command print for `rm` and `mkdir`.
```release-note
NONE
```

Tweak `Makefile`

---

samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
test/e2e/e2e_bundle_test.go
test/e2e/e2e_image_mutate_test.go
test/e2e/e2e_params_test.go
test/e2e/e2e_test.go
test/e2e/validators_test.go
test/utils/image.go

[There was a change recently in BuildKit: its exported metadata file was changed to be formatted.](https://github.com/moby/buildkit/pull/2621) Previously it was a single line JSON. Now, it is a formatted JSON. That required a change to the logic to extract the digest.
I am also changing the e2e test to verify that a successful BuildRun contains a valid image digest. This would have captured this problem earlier.
And that revealed that the digest we stored for BuildAh has always been incorrect. I basically observe the same as here: [Digests on local buildah different from registry, unclear how to 'correct' #3866](https://github.com/containers/buildah/issues/3866). I am putting in some workaround.
```release-note
The BuildKit and BuildAh sample build strategies were fixed to correctly set …
```

Fix BuildKit and BuildAh image digest extraction

---

.github/workflows/verify.yaml

We need this check to verify if a PR is missing updates on
CRDs, pkg/apis and pkg/clients. Somehow this got removed on
a previous PR.
```release-note
NONE
```

Re-add verify-generate target

---

deploy/crds/shipwright.io_buildruns.yaml

Not sure where the mistake happened, but somehow the `prune` flag seems to have disappeared from the BuildRun OpenAPI.
```release-note
NONE
```

Run make generate to make files consistent

---

deploy/clusterrole-aggregate-edit.yaml
deploy/clusterrole-aggregate-view.yaml
docs/configuration.md
test/e2e/e2e_rbac_test.go

- Add view aggregate role for inspecting Shipwright Build objects
- Add edit aggregate role for managing Builds, BuildRuns, and BuildStrategies.
- Ensure aggregated user roles are installed in e2e testing
Fixes #1023 
/kind feature
```release-note
Add default RBAC controls for "view" and "edit" users.
```

Add Default RBAC for Non-Admins

---

docs/buildstrategies.md
samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go

Updating build strategy tools
```release-note
The sample build strategies now use Kaniko v1.8.1 and Trivy v0.25.3
```

Update Kaniko to 1.8.1, update Trivy to 0.25.3

---

Makefile

Retrying the `kubectl wait` three times, and adding `TIMEOUT` on the `Makefile`.
```bash
make install-apis TIMEOUT=60s
``` 
Fixes #983
```release-note
NONE
```

Retrying Wait for Condition

---

cmd/bundle/main.go
cmd/bundle/main_test.go

The IBM Container Registry (ICR) does not support the standard registry delete
call, similar to DockerHub. Instead, a custom API call needs to be used.
Add ICR login and ICR delete functions analog to the DockerHub functions.
Use the same error message for both custom delete functions.
Fix missing `--secret-path` in pull and unpack from private registry test case.
In order to (unit) test this locally, set the following environment variables before running Ginkgo:
```bash
$ export TEST_BUNDLE_REGISTRY_TARGET=us.icr.io/somenamespace  # or docker.io/somenamespace
$ export TEST_BUNDLE_DOCKERCONFIGFILE=$HOME/.docker/config.json
$ ginkgo run cmd/bundle
```
for details on coding conventions, github and …

Introduce IBM Container Registry delete

---

.github/dependabot.yml
.github/workflows/release-notes-linter.yaml

Enabling dependabot alerts based on decision in the [community meeting from April 11th](https://github.com/shipwright-io/community/issues/78).
Settings are explained in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
We explicitely add the release note none label and skip the Release Note Linter action because it is not possible to configure the pull request to contain our required section.
```release-note
NONE
```

Enable dependabot updates

---

.github/dependabot.yml

Dependabot checks are currently failing when merging PR's, this should fix it. `time` needs to be quote as it is taken as a string.
```release-note
NONE
```

Quote the schedule.time for dependabot config

---

docs/buildstrategies.md
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml

There is finally a new BuildAh version on quay, https://quay.io/repository/containers/buildah?tab=tags&tag=latest. Picking that and hoping that it resolves the problem with our hanging BuildRuns in the e2e test in GitHub actions.
```release-note
The sample build strategies have been updated to use the most recent BuildAh image, v1.23.3
```

Update BuildAh to 1.23.3

---

Makefile
pkg/env/env_suite_test.go
pkg/env/env_test.go
pkg/volumes/volumes_suite_test.go
pkg/volumes/volumes_test.go

While implementing shipwright-managed push, I wanted to check my code coverage in unit tests. As usual, I was using Ginkgo. Some missing suites caused Ginkgo to fail once I enabled the coverage measurement. Fixing this here.
```release-note
NONE
```

Fix unit test suite when using Ginkgo

---

docs/buildstrategies.md
samples/build/build_ko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

Extending the ko build strategy with volume support for GOCACHE. This speeds up rebuilds dramatically when a Build user enables it. The build strategy by default uses an emptyDir which means that no caching happens. A Build user can assign any writable volume type to enable caching.
```release-note
The ko sample build strategy now supports a gocache volume that you can assign a writable volume in your Build to speed up rebuilds
```

Expose GOCACHE as volume in ko build strategy

---

pkg/reconciler/buildrun/resources/sources/utils.go
pkg/reconciler/buildrun/resources/sources/utils_test.go

In certain use cases, for example for a bundle source, we need to turn a secret name into a volume name to mount its data in the container. For this we have a translation function. But that had a problem.
Assuming the secret name is `abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcd-efgh`.
It prefixed `shp-` -> `shp-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcd-efgh`.
It trimmed to at most 63 characters -> `shp-abcdefghijklmnopqrstuvwxyz-abcdefghijklmnopqrstuvwxyz-abcd-`.
And that was it.
But now the volume name ended with a dash which is not allowed. Adding code to trim trailing dashes.
```release-note
Secret names which had a dash at the 59th characters could not be used for a bundle source because of an error in the translation of secret into volume names
```

Ensure volume name does not end with a trailing dash

---

.ko.yaml
images/git/Dockerfile
images/waiter/Dockerfile

Not too much to add to the title. I am running locally with ubi9 already and have not observed any issues.
Fixes #1076
```release-note
The base image of our released images are now based on UBI 9
```

Update base images to UBI 9

---

.github/workflows/base-images.yaml
.github/workflows/ci.yml
.github/workflows/mirror-images.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml

Updating GitHub actions in our workflows.
Notably is the oob cache support for Go that I am enabling. Maybe it speeds up builds. For this, I had to move the checkout step to before the Go setup step as it was looking for our go.mod.
The base image build I changed to guarantee a lower-case repository name as I wanted to try it out in my fork. And then quickly changed it to a matrix to run the two image builds in parallel. Can be seen here: https://github.com/SaschaSchwarze0/build/actions/runs/2804547984 (I had temporarily commented the `if` clause).
```release-note
NONE
```

Update GitHub actions

---

.github/workflows/verify.yaml
cmd/bundle/main.go
cmd/bundle/main_test.go
cmd/git/main.go
cmd/git/main_test.go
cmd/mutate-image/main.go
cmd/mutate-image/main_test.go
cmd/shipwright-build-controller/main.go
hack/install-counterfeiter.sh
pkg/bundle/bundle_test.go
test/e2e/validators_test.go

Staticcheck started to mark the usage of io/ioutil as findings. Such as in https://github.com/shipwright-io/build/runs/7740689867?check_suite_focus=true. Fixing this to get back to green PRs.
Some small changes regarding counterfeiter installation are included as that made trouble because the wrong Go version (1.19) was getting installed (fixed by #1085) and then I hunted things there and noticed inconsistent installations in the action vs the hack script.
```release-note
NONE
```

Remove usage of deprecated io/ioutil package

---

OWNERS

- Add @coreydaley as a reviewer and approver
- Add @sbose78 and @gabemontero to emeritus_approvers
- Remove @shahulsonhal from reviewers
Signed-off-by: Adam Kaplan <adam.kaplan@redhat.com>
/kind cleanup
```release-note
NONE
```

Add coreydaley to OWNERS

---

README.md
docs/buildstrategies.md
samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go
test/e2e/e2e_params_test.go

Regular build strategy updates before we release v0.11.
```release-note
Sample build strategies updated to use BuildAh v1.27, Kaniko v1.9, Crane v0.11, Trivy v0.31.3, and UBI9
```

Update BuildAh, Kaniko, Trivy, Crane, UBI in sample build strategies

---

.github/workflows/ci.yml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
DEVELOPMENT.md
docs/buildstrategies.md
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

The ko project moved from the google to the ko-build organization. Adopting Shipwright.
The current ko build strategy is broken because `curl --silent "https://api.github.com/repos/google/ko/releases/latest"` now causes a redirect to happen and therefore using `latest` does not work anymore with our build strategy. Specifying the release still worked because the download curl command always included `-L` (follow redirects) because GitHub imo always redirects them.
```release-note
The ko sample build strategy was fixed to download from the ko-build organization.
```

Move ko-related artifacts to ko-build

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
docs/build.md
docs/buildrun.md
pkg/apis/build/v1alpha1/build_source.go
pkg/apis/build/v1alpha1/build_types.go
pkg/apis/build/v1alpha1/buildrun_types.go

Deprecate the following features from Shipwright Build:
- `spec.sources` in `Build` (multiple sources and HTTP artifact downloads)
- `status` in `Build` (controller validations for Build objects)
- `spec.dockerfile` in `Build` (provide path to Dockerfile)
- `spec.builder` in `Build` (provide builder image for s2i builds)
- `spec.serviceaccount.generate` in `BuildRun` (generated service accounts)
/kind cleanup
```release-note
The following features are deprecated: 1) Multiple sources for builds, 2) HTTP artifact downloads, 3) Status validations for `Builds`, 4) Providing a builder image in a `Build`, 5) …
```

Deprecate alpha features

---

docs/development/authentication.md

Hacktoberfest PR!
Since GitHub dropped support for passwords last year and encouraged the use of personal access tokens (PATs) instead, the shipwright [doc needs to be updated](https://github.com/shipwright-io/build/blob/main/docs/development/authentication.md#basic-authentication) for the same. The "Basic authentication" method to authenticate with Git currently specifies putting `<password>` under the `stringData.password` field. This PR updates the doc to suggest using tokens instead.
Fixes #968 
```release-note
Deprecated support for passwords. Use Personal Access Tokens instead.
```

[Hacktoberfest]: Update Doc to mention support for tokens

---

.golangci.yaml
pkg/reconciler/buildrun/resources/params.go
pkg/validate/ownerreferences.go
pkg/volumes/volumes.go

Use explicit variable in for loops that can safely be used for references.
Remove `G601` ignore in global configuration.
```release-note
NONE
```

Fix `G601` findings

---

docs/configuration.md
pkg/config/config.go
pkg/config/config_test.go

Use same `HOME` variable stanza in all steps defined in the configuration:
- GitContainerTemplate
- BundleContainerTemplate
- MutateImageContainerTemplate (already defined)
- MutateImageContainerTemplate
Reorder fields to have simple settings at the beginning.
Add empty lines between sections for readability.
```release-note
NONE
```

Use `/tekton/home` as `HOME` in strategy steps

---

.github/workflows/check-latest-images.yaml
hack/check-latest-images.sh

Execute `hack/check-latest-images.sh` and update Kaniko, Trivy, Buildah and Crane container images used in the [sample build strategies](https://github.com/shipwright-io/build/tree/main/samples/buildstrategy) to their latest versions via GitHub actions.
Fixes #1039 
```release-note
NONE
```

Auto-update of tools versions in the sample build strategies

---

.github/workflows/check-latest-images.yaml
hack/check-latest-images.sh

Improve PR body in auto update tools version [workflow]((https://github.com/shipwright-io/build/blob/main/.github/workflows/check-latest-images.yaml)) as per [this](https://github.com/shipwright-io/build/pull/1140#issuecomment-1294581457). Addition for [1039](https://github.com/shipwright-io/build/issues/1039).
```release-note
NONE
```

Improve PR body in auto-update tools version workflow

---

pkg/reconciler/buildrun/controller.go
test/buildrun_samples.go
test/catalog.go
test/integration/buildruns_to_taskruns_test.go

The bug is that updates to an one-off build are not considered for reconcilation because they do not reference a build in their labels. Therefore, the label validation should only be considered for brs that have a build reference.
Fixes #1155.
```release-note
Fixes cancelation of buildruns without a build reference.
```
/kind bug

Fixes cancelation of buildruns without a build reference

---

Makefile
test/e2e/e2e_one_off_builds_test.go

Replace the deprecated `CurrentGinkgoTestDescription().Failed` by `CurrentSpecReport().Failed()`.
Remove the deprecated `--slow-spec-threshold` argument usage.
Fixes #1056
```release-note
NONE
```

Remove usage of deprecated Ginkgo capabilities

---

.github/workflows/base-images.yaml
images/image-processing/Dockerfile

Adding a base image that runs as user 1000 and contains the trivy command. This is needed for the image-processing command once we add vulnerability scanning.
This is part of the implementation of [Build Output Vulnerability Scanning](https://github.com/shipwright-io/community/blob/main/ships/0033-build-output-vulnerability-scanning.md).
```release-note
NONE
```

Add base image for image processing command

---

.github/workflows/base-images.yaml
.github/workflows/mirror-images.yaml
.github/workflows/release-notes-linter.yaml

It doesn't hurt technically speaking, but it is better that the job names are unique across all GitHub Actions.
```release-note
NONE
```

Fix job name duplication

---

.github/workflows/check-latest-images.yaml
.github/workflows/ci.yml
.github/workflows/mirror-images.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml
HACK.md
docs/buildstrategies.md
go.mod
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go
samples/build/build_ko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

Fixes: https://github.com/shipwright-io/build/issues/1157
Use Go `1.19` in all CI configurations.
Update Go module Go version.
Change Go version in README and samples.
```release-note
NONE
```

Bump to Go `1.19`

---

cmd/git/main.go
cmd/git/main_suite_test.go
cmd/git/main_test.go
go.sum
pkg/git/error_parser.go

Fixes https://github.com/shipwright-io/build/issues/1131
Fixes https://github.com/shipwright-io/build/issues/1133
Ref: https://github.com/shipwright-io/build/issues/1116
Check that basic auth is not used in combination with a HTTP endpoint.
Redact log output in case basic auth is used with inline user fields, i.e. `https://user:pass@url.com`.
```release-note
The Git source step of a build strategy now returns a more elaborate error in case basic authentication (username and password) are used in combination with a HTTP URI. Instead of a generic error, an error message with an explanation is presented to …
```

Add custom error for basic auth with HTTP

---

.github/workflows/ci.yml

We are on a very old version of the azure/setup-kubectl action which is leading to this deprecation warning in our action run:
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/setup-kubectl@v1`
I am updating the action to v3.
```release-note
NONE
```

Update setup-kubectl action from v1 to v3

---

.github/workflows/nightly.yaml

We have this deprecation:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Based on the instructions, I rewrote the set-output command.
```release-note
NONE
```

Replace deprecated set-output by GITHUB_OUTPUT

---

.github/workflows/check-latest-images.yaml

There is a unit test case which is testing on the buildah image and currently fails in https://github.com/shipwright-io/build/pull/1145 with this error:
```
/home/runner/work/build/build/pkg/reconciler/buildrun/resources/taskrun_test.go:112
[FAILED] Expected
<string>: quay.io/containers/buildah:v1.28.0
to equal
<string>: quay.io/containers/buildah:v1.20.1
In [It] at: /home/runner/work/build/build/pkg/reconciler/buildrun/resources/taskrun_test.go:113
```
```release-note
NONE
```

Include pkg directory

---

hack/generate-copyright.sh

The build/ dir was removed via https://github.com/shipwright-io/build/pull/1171 but the generate-copyright.sh script was not updated accordingly. This fix it.
```release-note
NONE
```

Remove unneeded find path

---

samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

Go is running some Git commands to determine version control information of the directory that it builds to attach them as metadata to the binary. This leads to BuildRun failures when the directory is not owned by the current user:
```txt
go version go1.19.6 linux/arm64
ko version 0.12.0
2023/02/25 11:42:10 Using base [registry.access.redhat.com/ubi9/ubi-minimal@sha256:085c5049f5bd0b3cb33c322306a528373f79dc6f1098ff8f5a5b28f2685c53f8](http://registry.access.redhat.com/ubi9/ubi-minimal@sha256:085c5049f5bd0b3cb33c322306a528373f79dc6f1098ff8f5a5b28f2685c53f8) for [github.com/shipwright-io/build/cmd/shipwright-build-controller](http://github.com/shipwright-io/build/cmd/shipwright-build-controller)
2023/02/25 11:42:10 Building [github.com/shipwright-io/build/cmd/shipwright-build-controller](http …
```

Allow non-current user to own the directory which is built by ko

---

.github/workflows/nightly.yaml

I think, I mis-interpreted the documentation of https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter.
The curly brackets there are not to be included as it can later be seen in the example.
I am removing them. This should help fixing the nightly release build issues that we have.
```release-note
NONE
```

Remove incorrect curly brackets

---

samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml

https://github.com/moby/buildkit/commit/7bd72856ad4d403260a6f68c31977c72c2d1d8ce
Fix buildkit cluster build strategy's cache import from insecure registry.
```release-note
Fix buildkit cluster build strategy's cache import from insecure registry.
```

fix: buildkit insecure registry image caching

---

.github/workflows/ci.yml
.github/workflows/nightly.yaml
.github/workflows/release.yaml

Updated solution for https://github.com/shipwright-io/build/pull/1230#issue-1615912566
Updating ko to v0.13 to pick up the fix [fix: handle docker's unknown/unknown platform in index manifests #975](https://github.com/ko-build/ko/pull/975) to resolve the problems in our nightly builds.
```release-note
NONE
```

Update ko to v0.13

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml

The nightly build is still failing. https://github.com/shipwright-io/build/actions/runs/4508014260/jobs/7936340125
Not completely sure why. I am updating to the latest action that installs cosign, and ~I am changing the env var value from `true` to `1` based on the documentation~ I am removing the env var based on https://blog.sigstore.dev/cosign-2-0-released/.
```release-note
NONE
```

Update cosign action

---

.github/workflows/nightly.yaml
.github/workflows/release.yaml

Ensure interactive prompt is disabled by adding the requires --yes flag. Fixes current issues with the nightly releases.
```release-note
NONE
```

Ensure transparency logs confirmation is not interactive

---

Makefile

On M1/M2 macOS machines, it can happen that the KinD setup uses `arm64` node images and `ko` wants to match the system OS and architecture. However, the base images Shipwright relies on do not support a platform like `darwin/arm64`.
Add `--platform=linux/$(GO_ARCH)` to enforce that `ko` build Linux images with the respective current system architecture.
```release-note
NONE
```

Add `platform` to `install-controller-kind` target

---

pkg/config/config_test.go
pkg/reconciler/buildrun/resources/image_processing.go
pkg/reconciler/buildrun/resources/taskrun_test.go
test/integration/build_to_taskruns_test.go

Rename remaining mutate image reference to image processing.
Fix TYPO in variable name.
FIX TYPO in comment.
```release-note
NONE
```

Fix remaining reference to `mutate-image`

---

pkg/bundle/bundle.go
pkg/bundle/bundle_test.go

Add test case to test the push and pull flow in the package.
Change `Pack` signature to return `io.ReadCloser` to then use `os.Pipe` instead of bytes buffer to have the `ReadCloser` available. Use `LayerFromOpener` with a custom opener based on `Pack` to get rid of the deprecation warning.
```release-note
NONE
```

Replace `LayerFromReader` with `LayerFromOpener` in bundle package

---

pkg/reconciler/buildrun/resources/conditions.go
pkg/reconciler/buildrun/resources/failure_details.go

During an investigation of a failed build run, we ran into the issue that the error message could be obtained from the TaskRun, but the pod look-up failed for an unclear reason. Since there is no logging of the error, there is nothing to see.
Add log line in case the pod cannot be looked-up.
Add namespace to another error logging to be more clear in the logs.
Rename `v1` import to `corev1` to be more aligned with other sources.
Sort imports by have Kubernetes imports separately.
```release-note
NONE
```

Improve logging in error case for pod retrieval

---

samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

When I rewrote the `ko` commands to export an OCI image, I removed the `platform` argument. That was not correct. Adding it back. Also two more small changes:
1. I rename the step from `build-and-push` to just `build` as it does not push anymore.
2. I am calling `ko build` instead of `ko publish`. The commands do the same, but `ko --help` does not anymore document `publish`.
```release-note
The platform support for the ko build strategy is functional again
```

Pass platform to ko build

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
deploy/crds/shipwright.io_buildstrategies.yaml
deploy/crds/shipwright.io_clusterbuildstrategies.yaml
pkg/apis/build/v1beta1/build_types.go
pkg/apis/build/v1beta1/buildrun_types.go
pkg/apis/build/v1beta1/buildstrategy_types.go
pkg/apis/build/v1beta1/clusterbuildstrategy_types.go

Do not serve the v1beta1 yet. Otherwise, creating v1alpha1 custom resources are modified to v1beta1, and the conversion webhook is not there yet.
```release-note
NONE
```

Do not serve the v1beta1 yet

---

cmd/git/main.go
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml

We are currently facing two issues that are causing all pull requests to be red which is why I am putting them together although they are unrelated:
(1) UBI update
The recent UBI changes seems to have bumped to a Git version that requires the use of `safe.directory` also for the Git step like we did in [Allow non-current user to own the directory which is built by ko #1219](https://github.com/shipwright-io/build/pull/1219) for the ko build strategy.
This fix is necessary to get back to green pull requests as it is failing like in [here](https://github.com/shipwright-io/build/actions/runs/4936301520/jobs/8823661767?pr=1291):
```
2023-05-10T11:17:10Z 1 Logs of container step-source-default: 2023/05/10 11:17:06 Info: ssh (/usr/bin/ssh): OpenSSH_8.7p1, OpenSSL 3.0.7 1 Nov 2022
2023/05/10 …
```

Add safe.directory to git commands / Tolerate old Heroku stack

---

Makefile

As per [Makefile#L127](https://github.com/shipwright-io/build/blob/main/Makefile#L127), `go install` installs the latest version of ginkgo. I was trying to perform `make install` when new ginkgo version (2.10.0) was released ~6 hours ago, and dependabot was yet to update the version in `go.mod`. Due to this a version mismatch is reported & led to failures.
--> Eliminating the `@latest`, so that `go install` installs the package version as that of specified in the `go.mod`.
Could also observe some warnings w.r.t deprecation of `--progress`. Hence removed the flag and added extra `v` for increased verbosity.
For pull requests that don't need to be mentioned at release time, use the `/release-note-none` Prow command to add the `release-note-none` label to the PR. You can also write the …

Pulls ginkgo version as per go.mod instead of latest

---

Makefile

Fixes #1314 
--> As 'ko apply' feeds the yamls recursively to 'kubectl apply', adding `--server-side` flag to be sent directly to 'kubectl apply'.
```release-note
NONE
```

Adds `--server-side` to `ko apply` as well

---

hack/check-latest-images.sh

Kaniko has changed their release name to include ` Release` as suffix. This breaks our update pipeline: https://github.com/shipwright-io/build/pull/1319/files
Changing our script to use the tag name instead of the release name.
```release-note
NONE
```

Use tag name instead of release name

---

.github/workflows/base-images.yaml
.github/workflows/ci.yml
images/base/Dockerfile
images/docker-bake.hcl
images/git/Dockerfile
images/image-processing/Dockerfile
images/waiter/Dockerfile

This is part one of the implementation of [SHIP-0036: RunAs user and group for supporting steps](https://github.com/shipwright-io/community/pull/131).
This pull request changes the base images for the supporting steps:
* A common base image is introduced which ensures that the base packages are all up-to-date, which contains a world-writable `/shared-home` directory and an `/etc/passwd` and `/etc/group` file that is setup for user/group 1000/1000 to match our default configuration for supporting steps.
* git, image-processing, and waiter are adjusted to consume the common base image
The tests for this pull request cannot succeed. The reason is that we build here the images, but the Dockerfiles now require a common base image that will only be pushed AFTER this PR is merged. We will have …

SHIP-0036: Part 1: Update base images to allow an arbitrary user to run it

---

samples/build/build_buildpacks-v3-heroku_cr.yaml
samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml

This pull request updates several things in the Buildpacks strategy samples:
* Heroku is updated to Ubuntu Bionic (22). This required a change in the sample as Heroku does now require a Procfile to define the entrypoint. The e2e can therefore only succeed after https://github.com/shipwright-io/sample-nodejs/pull/7 is merged.
* The platform API is updated to 0.7. This includes the change to have [analyze before detect ](https://buildpacks.io/docs/reference/spec/migration/platform-api-0.6-0.7/#run-the-analyzer-before-the-detector)
* The layers and cache directories are changed to include a .shp directory in the path under /tmp. The reason is that /tmp/cache can be overlapping with a directory used by build tools.
Fixes #1280
Fixes #1295
```release-note
Buildpacks sample build strategies are …
```

Update Buildpacks strategy

---

.github/workflows/ci.yml
deploy/100-namespace.yaml
deploy/500-controller.yaml
docs/build.md
hack/install-kind.sh
test/kind/config.yaml

This pull request configures the security of the controller deployment to fulfill the restricted PodSecurity profile. The namespace is configured to enforce this. The KinD configuration is updated to enable PodSecurity admission. I also update the KinD version to be current. I had to change the e2e that we run here in GitHub to use its own namespace because build strategies like Kaniko require elevated permissions beyond privileged. And in general, we should have never used this namespace imo. I also updated the documentation in that regard.
Fixes #1331 
```release-note
The shipwright-build namespace is now configured to enforce restricted PodSecurity. The shipwright-build-controller deployment was updated to fulfil all requirements.
```

Setup security context of controller deployment, enforce restricted PodSecurity in namespace

---

.github/workflows/ci.yml
.github/workflows/mirror-images.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml
HACK.md
docs/buildstrategies.md
go.mod
samples/build/build_ko_cr.yaml
samples/buildstrategy/ko/buildstrategy_ko_cr.yaml

Golang 1.21 is expected to be released this month. Then, 1.19 is out of support. Therefore, it is time to move up to 1.20.
```release-note
Golang 1.20 is used to compile
```

Update to Golang 1.20

---

docs/buildstrategies.md
samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
test/clusterbuildstrategy_samples.go

Already last year, [Kaniko cleaned up command line flags to make naming consistent](https://github.com/GoogleContainerTools/kaniko/pull/2084). The `snapshotMode` and `tarPath` are deprecated and cause a warning. Adopting our strategy example to use `snapshot-mode` and `tar-path`.
```release-note
The Kaniko sample build strategy now uses the --snapshot-mode and --tar-path command line flags instead of the deprecated --snapshotMode and --tarPath
```

Use --snapshot-mode instead of --snapshotMode and --tar-path instead --tarPath in sample build strategies that use Kaniko

---

Makefile

Use the `-p` flag with `mkdir` to fix the following error when running `make test`:
```
$ make test-unit
mkdir: cannot create directory ‘build/coverage’: No such file or directory
make: *** [Makefile:167: test-unit] Error 1
```
```release-note
NONE
```

Use -p flag with mkdir

---

samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml

This updates the BuildKit sample build strategy to use the recently introduced `tar=false` option on the output. This causes the files directly getting written to a directory that I pass in as `dest`. This saves us the extraction that we so far did.
I am also removing the metadata-file creation. We needed that before shipwright-managed push because we grabbed the digest from it. Now, Shipwright sets it now as part of the push.
```release-note
The BuildKit sample build strategy now does not cause BuildKit to tar the image to then untar it
```

Use BuildKit's option to not tar the output image as OCI layout as we need it as a directory anyway

---

hack/check-latest-images.sh

In response to https://github.com/shipwright-io/build/pull/1368
The BuildAh team seamingly rebuild all images in the last two days:
This lead to our automation to pickup "latest" yesterday, and v1.23.0 today.
I am changing the query to sort by name and take the last item. This should be what we want as long as BuildAh tags images the way it does today.
```release-note
NONE
```

Improve BuildAh query

---

.github/workflows/cleanup-nightly-assets.yaml

Fixes https://github.com/shipwright-io/build/issues/1070#issuecomment-1697637603
```release-note
Add action to cleanup nightly assets regularly
```

Add action to clean nightly assets

---

.github/workflows/cleanup-nightly-assets.yaml

Fix typo in run command, that lead to a failure.
```release-note
NONE
```

For nightly-cleanup, only preserve last two months

---

pkg/apis/build/v1beta1/build_conversion.go
pkg/apis/build/v1beta1/build_types.go
pkg/apis/build/v1beta1/zz_generated.deepcopy.go
pkg/webhook/conversion/converter_test.go

Adding conversion logic for the automatic "BuildRun deletion when Build is deleted" capability which is an annotation in alpha and a first class attribute in beta.
```release-note
NONE
```

Add conversion code for buildrun deletion capability

---

hack/generate-cert.sh
hack/patch-crds-with-conversion.sh
pkg/apis/build/v1beta1/build_conversion.go
pkg/apis/build/v1beta1/buildrun_conversion.go
pkg/apis/build/v1beta1/buildstrategy_conversion.go
pkg/apis/build/v1beta1/clusterbuildstrategy_conversion.go
pkg/webhook/conversion/converter.go
pkg/webhook/conversion/converter_test.go

This change completes the handling of Dockerfiles:
* When a Beta build contains a Dockerfile parameter, then this is converted to .spec.dockerfile in Alpha without adding the parameter
* An Alpha build strategy that uses `$(build.dockerfile)` or `$(params.DOCKERFILE)` gets their usage migrated to `$(params.dockerfile)` and the dockerfile parameter is declared
* A Beta build strategy that declares a dockerfile parameter as string with Dockerfile as default value gets this parameter removed and all referenced changed to `$(params.DOCKERFILE)
`
I am also adding a commit that fixes the conversion of the retention from alpha to beta. The old code worked find in unit tests but not in reality. We must create a copy of the Map so that the annotation addition works.
```release-note
NONE
```

Handle dockerfile in build strategy conversion

---

pkg/reconciler/buildrun/resources/taskrun_test.go
samples/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
test/buildstrategy_samples.go
test/clusterbuildstrategy_samples.go

The current Shipwright strategy examples use privileged containers to run buildah.
With the current PR these have been updated to use more limited permissions/capabilities and align with Tekton task for OpenShift pipelines.
```release-note
The BuildAh sample build strategies now do not anymore run privileged containers
```

Run buildah steps without privileged containers

---

.github/workflows/cleanup-nightly-assets.yaml

Introduce a sleep time when deleting assets from nightly release, recommended by github when hitting the secondary rate limits.
```release-note
NONE
```

Ensure assets deletion use a sleep time

---

pkg/validate/volumes.go

chore: import packages only once

---

.github/workflows/ci.yml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml
Makefile
README.md
deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
deploy/crds/shipwright.io_buildstrategies.yaml
deploy/crds/shipwright.io_clusterbuildstrategies.yaml
hack/customization/conversion_webhook_block.yaml
hack/patch-crds-with-conversion.sh
hack/release.sh
hack/setup-webhook-cert-integration-test.sh
hack/setup-webhook-cert.sh
test/integration/integration_suite_test.go
test/utils/environment.go
test/utils/namespaces.go
test/utils/webhook.go

Part of https://github.com/shipwright-io/build/issues/1344
I am changing `make generate` to also run the hack/patch-crds-with-conversion.sh script so that the conversion block is now part of the CRDs that are committed.
With that, we are producing an incomplete release yaml where two things are missing: the shipwright-build-webhook-cert secret and the caBundle in the CRDs.
I am introducing hack/setup-webhook-cert.sh which can run against a cluster to create or update the webhook cert and configure the caBundle.
I am changing `make install-controller-kind` to call this script so that it can be used again as single make target to setup Shipwright Build. That is also required for the setup GitHub action which calls this make target and nothing else. The prepare-conversion target is therefore …

Update release process for webhook certificate

---

pkg/reconciler/buildrun/resources/conditions.go

When a BuildRun pod is failing it is not necessary to check for failedContainer first.
We can directly check if the pod is evicted and reflect that in the BuildRun condition
Depending on how the system is evicting the pod, `extractFailedPodAndContainer` might return a non-nil value for `failedContainer`.
In such scenarios we were not detecting if the pod was evicted.
This is now fixed as we first check the Reason
```release-note
The logic to detect whether a BuildRun failed due to an evicted Pod was improved
```

Reliably detect evicted pods for failing BuildRuns

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
pkg/apis/build/v1beta1/build_conversion.go
pkg/apis/build/v1beta1/buildstrategy.go
pkg/apis/build/v1beta1/zz_generated.deepcopy.go

Fixes #1363 
-->
```release-note
The Strategy struct does not have an APIVersion field anymore.
```

Removing Strategy.APIversion

---

pkg/bundle/bundle.go

In order to reduce risk of directory traversal attack
```release-note
NONE
```

Sanitize file target paths

---

docs/build.md
docs/buildrun.md
samples/v1beta1/build/build_buildah_shipwright_managed_push_cr.yaml
samples/v1beta1/build/build_buildah_strategy_managed_push_cr.yaml
samples/v1beta1/build/build_buildkit_cr.yaml
samples/v1beta1/build/build_buildpacks-v3-heroku_cr.yaml
samples/v1beta1/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
samples/v1beta1/build/build_buildpacks-v3_cr.yaml
samples/v1beta1/build/build_buildpacks-v3_namespaced_cr.yaml
samples/v1beta1/build/build_kaniko-trivy-bad_cr.yaml
samples/v1beta1/build/build_kaniko-trivy-good_cr.yaml
samples/v1beta1/build/build_kaniko_cr.yaml
samples/v1beta1/build/build_ko_cr.yaml
samples/v1beta1/build/build_source-to-image_cr.yaml
test/v1beta1_samples/build_samples.go

Add proper source type to Builds
The type was missing, which should be Git
```release-note
NONE
```

Add missing type to CRs

---

pkg/apis/build/v1beta1/buildrun_conversion.go
pkg/webhook/conversion/converter_test.go
test/utils/v1beta1/image.go

When a BuildRun without an output is converted to Beta, then this looks like this:
```yaml
apiVersion: shipwright.io/v1beta1
kind: BuildRun
spec:
build:
name: build-name
output:
image: ""
serviceAccount: sa-name
```
The empty output section is not desired, especially as it has a mandatory image field which is then rendered as an empty string.
```release-note
NONE
```

Omit empty output object in BuildRun spec

---

pkg/image/options.go
test/utils/v1alpha1/webhook.go
test/utils/v1beta1/webhook.go
test/utils/webhook.go

Ref: https://github.com/securego/gosec/issues/1044#issuecomment-1764948001
Break up transport setup so that the `InsecureSkipVerify` is a single line, so that their latest changes can find the ignore statement at the exact statement level to be properly ignored.
Refactor test code to only have the test client setup once.
```release-note
NONE
```

Fix `G402` reports with latest `gosec` version

---

docs/build.md
test/data/v1beta1/buildrun_buildah_cr_local_source_upload.yaml
test/e2e/v1beta1/e2e_local_source_upload_test.go

Fixes #1414 
```release-note
NONE
```

Add e2e test for v1beta1-localsource

---

pkg/bundle/bundle.go

When we prevent path traversal when extracting a source bundle, we were too strict. We only need to prevent `/../` because this means to go one directory up. We still must allow `..` because a directory or file can contain two subsequent dots in its name.
```release-note
You can now use files and directories with two subsequent dots in its name when using an OCI artifact as source
```

Allow a file or directory having a name with two subsequent dots while still preventing path traversal

---

.github/workflows/ci.yml
cmd/bundle/main.go
cmd/bundle/main_test.go
cmd/git/main.go
cmd/git/main_test.go
deploy/crds/shipwright.io_buildruns.yaml
pkg/apis/build/v1alpha1/buildrun_types.go
pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
pkg/apis/build/v1beta1/buildrun_conversion.go
pkg/apis/build/v1beta1/buildrun_types.go
pkg/apis/build/v1beta1/zz_generated.deepcopy.go
pkg/bundle/bundle.go
pkg/bundle/bundle_test.go
pkg/reconciler/buildrun/resources/sources.go
pkg/reconciler/buildrun/resources/sources/bundle.go
pkg/reconciler/buildrun/resources/sources/git.go
pkg/reconciler/buildrun/resources/sources/git_test.go
pkg/reconciler/buildrun/resources/sources/http.go
pkg/reconciler/buildrun/resources/sources/utils.go
pkg/reconciler/buildrun/resources/taskrun_test.go
test/e2e/v1alpha1/validators_test.go
test/e2e/v1beta1/validators_test.go
test/integration/build_to_buildruns_test.go
test/integration/build_to_git_test.go
test/integration/build_to_taskruns_test.go
test/integration/buildrun_status_test.go
test/v1alpha1_samples/catalog.go

Extend the API fields and CRD files to include the source timestamp in the source result.
Update Git step code to write commit timestamp result file.
Update Bundle step code to write source timestamp, which is the the most recent source file timestamp.
Extend task run setup logic to include respective command line flags for the Git and Bundle step CLIs to write the result files, which then can be used to extend the status sources fields of the BuildRun.
Fix timestamp issue in Bundle pack and push code so that only the image gets a neutral timestamp, but the packaged source files retain their respective filesystem modification timestamps.
Add integration test cases to verify the new status sources fields.
Fixes #1446
See [the contributor …

Add source timestamp field for source result

---

pkg/apis/build/v1beta1/buildrun_conversion.go
pkg/webhook/conversion/converter_test.go

This fixes the conversion from v1alpha1 to v1beta1 of a BuildRun when the BuildRun uses a generated service account.
```release-note
A BuildRun object in v1alpha1 version is now correctly converted to v1beta1 when it has .spec.serviceAccount.generate set to true
```

Fix the BuildRun conversion from alpha to beta when .spec.serviceAccount.generate=true

---

pkg/reconciler/build/controller.go
pkg/reconciler/buildlimitcleanup/controller.go
pkg/reconciler/buildrun/controller.go
pkg/reconciler/buildrunttlcleanup/controller.go

Rename unused parameter
```release-note
NONE
```

Fix golangci-lint findings

---

.github/workflows/ci.yml
.github/workflows/mirror-images.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml
HACK.md
docs/buildstrategies.md
go.mod
go.sum
hack/install-kind.sh
samples/v1alpha1/build/build_ko_cr.yaml
samples/v1alpha1/buildstrategy/ko/buildstrategy_ko_cr.yaml
samples/v1beta1/build/build_ko_cr.yaml
samples/v1beta1/buildstrategy/ko/buildstrategy_ko_cr.yaml

This updates dependencies: Go, ko, and KinD.
Fixes #1493
```release-note
Shipwright Build is now compiled with Go 1.21
```

Update Go to 1.21, ko to 1.15.1, KinD to 0.21

---

pkg/validate/secrets.go

This Pull Request Fixes #1501  by improving the naming of the buildCredentialserences function in secrets.go. The current function name is misleading and grammatically incorrect. The function has been renamed to buildCredentialReferences to better reflect its purpose and adhere to proper naming conventions.
- Renamed the function buildCredentialserences to buildCredentialReferences in secrets.go.
- Updated all references to the function throughout the codebase to use the new name.
```release-note
NONE
```

Fixed buildCredentialserences function name

---

samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
samples/v1beta1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
samples/v1beta1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml

Add `CNB_TARGET_OS` and `CNB_TARGET_ARCH` to fix error during the detect phase, where the target system cannot be detected:
```
[Error: Internal Buildpack Error]
Couldn't determine target os: environment variable not found
err:  heroku/procfile@3.0.0 (1)
======== Output: heroku/procfile@3.0.0 ========
```
There seems to be a changed behavior that was introduced in the common buildpacks library that is in use that expects these environment variables to be present to detect the target system OS and architecture.
Ref: https://github.com/heroku/procfile-cnb/issues/214
Ref: https://github.com/heroku/libcnb.rs/commit/033f6128c647b7bc6effc8b80fae8b96a4373169
for details on coding conventions, github and …

Fix Heruko buildpacks samples that failed to determine the target OS

---

pkg/reconciler/buildrun/resources/sources.go

This Pull Request fixes shipwright-io#1500 by improving the "isLocalCopyBuildSource" function. Here's a summary of the changes made:
- The check for the local source in the BuildRun is moved to the top of the function. This adjustment ensures that if a local source is defined in the BuildRun, it will be returned without further checks.
- If no local source is found in the BuildRun, the function then checks if the Build has a local source defined and returns it if found.
- If neither the BuildRun nor the Build has a local source defined, the function returns nil.
Removed redundant condition:
With the first conditional handling the case where a local source is defined in the BuildRun, there's no need to check if the Build has a local source if the BuildRun already has one.
See [the …

[fixed] : Order of Local Source between Builds and BuildRuns

---

README.md

- Fixed the Broken invite link of the Public calender
- Fixes #1491 
```release-note
NONE
```

[fixed] : broken invite link of public calender

---

docs/build.md
docs/buildrun.md
pkg/apis/build/v1beta1/source.go

Mainly for build sources and usage of OCIArtifact.
```release-note
NONE
```

Minor fixes on docs and types

---

.github/dependabot.yml

Extend Dependabot setup to also bump GitHub actions.
```release-note
NONE
```

Include GitHub action version in Dependabot setup

---

README.md

Ensure curl cmd follows redirection.
The current state gives no value, when using curl, therefore installing something will fail.
```release-note
NONE
```

Ensure curl cmd follows redirection

---

pkg/apis/build/v1beta1/build_types.go
pkg/reconciler/build/build_test.go
pkg/reconciler/buildrun/buildrun_test.go
pkg/validate/strategies.go
pkg/validate/strategies_test.go
pkg/validate/validate.go
test/integration/build_to_buildruns_test.go
test/integration/buildruns_to_taskruns_test.go

Set status when strategy kind is not one of the supported ones.
Add test cases to strategy validation.
Refactor strategy validation code to be more compact and readable.
Fixes #1531
```release-note
NONE
```

Fix unknown strategy kind reconcile issue

---

.github/workflows/check-latest-images.yaml
.github/workflows/release.yaml

Switch to using the major version for the `peter-evans/create-pull-request` GitHub action.
Bump to latest available `v6`.
This supersedes #1525.
```release-note
NONE
```

Use major version for `peter-evans/create-pull-request` action

---

README.md

Move README to v1beta1
Move CRs to use v1beta1 as the apiVersion and adjust the objects definition.
Fixes #1502 
-->
```release-note
NONE
```

Move README to v1beta1

---

.github/workflows/ci.yml
.github/workflows/release-notes-linter.yaml
.github/workflows/verify.yaml

Update our CI-oriented GitHub actions to run when commits merge in a `release-v*` branch, or a pull request is opened against a `release-v*` branch. With this change, future release branches will automatically have CI checks enabled. This commit should be backported to enable CI in a prior release branch.
This implements a portion of SHIP-0038.
See also https://github.com/shipwright-io/community/issues/85
```release-note
NONE
```

SHIP-0038: Run CI on Release Branches

---

pkg/image/options.go
pkg/reconciler/build/controller.go
pkg/reconciler/buildlimitcleanup/controller.go
pkg/reconciler/buildrun/controller.go
pkg/reconciler/buildrunttlcleanup/controller.go
test/utils/v1alpha1/webhook.go
test/utils/v1beta1/webhook.go
test/utils/webhook.go

Fixes golangci-lint errors for CI and skips error gosec G402.
```release-note
NONE
```

Fix golangci-lint errors for CI

---

.github/workflows/ci.yml
.github/workflows/release-notes-linter.yaml
.github/workflows/verify.yaml

Update our CI-oriented GitHub actions to run when commits merge in a `release-v*` branch, or a pull request is opened against a `release-v*` branch. With this change, future release branches will automatically have CI checks enabled. This commit should be backported to enable CI in a prior release branch.
This implements a portion of SHIP-0038.
See also https://github.com/shipwright-io/community/issues/85
```release-note
NONE
```
/kind cleanup

[release-v0.12] SHIP-0038: Run CI on Release Branches

---

pkg/apis/build/v1beta1/build_conversion.go
pkg/apis/build/v1beta1/buildrun_conversion.go
pkg/apis/build/v1beta1/buildstrategy_conversion.go
pkg/apis/build/v1beta1/clusterbuildstrategy_conversion.go
pkg/webhook/conversion/conversion.go
pkg/webhook/conversion/converter.go

Ensure Info log is kept to a minimal
Ensure log content is valuable:
- provide conversion request UID
- provide conversion response UID and status
Upon conversion of an object, this is how the webhook will log:
```sh
{"level":"debug","ts":"2024-03-20T12:31:01Z","logger":"shp-build-webhook","msg":"handling request"}
{"level":"info","ts":"2024-03-20T12:31:01Z","logger":"shp-build-webhook","msg":"conversion request","uid":"0fea4dac-0a67-4c2f-b01c-4798ae7de382"}
{"level":"debug","ts":"2024-03-20T12:31:01Z","logger":"shp-build-webhook","msg":"converting custom resource"}
{"level":"info","ts":"2024-03-20T12:31:01Z","logger":"shp-build-webhook","msg":"converting Build from beta to alpha","namespace":"default","name":"buildkit-build"}
{"level":"info","ts":"2024-03-20T12:31:01Z","logger":"shp-build …
```

Improve conversion webhook logging

---

.github/workflows/release.yaml

Update the release workflow to accept a git reference as a parameter. This will be used to check out the appropriate release branch when generating artifacts and release notes.
The action was also updated to use the (new?) `inputs` context, instead of relying on the inputs key existing in the `github.events` payload.
Part of #1555 
```release-note
NONE
```

SHIP-0038: Add Git Ref to Release Workflow

---

README.md

Fix additional underscore that show up between the badges in the README header.
> <img width="201" alt="image" src="https://github.com/shipwright-io/build/assets/1979133/0b72cedc-9834-425c-b2f5-83d1703fc904">
```release-note
NONE
```

Fix underscore showing up between badges

---

.gitignore
pkg/reconciler/buildrun/resources/params.go
pkg/reconciler/buildrun/resources/params_test.go

There is a bug when defining the following Build:
```yaml
spec:
paramValues:
name: param-name
values:
- secretValue:
name: secret-name
key: key-1
format: ARG_NAME1=${SECRET_VALUE}
- secretValue:
name: secret-name
key: key-2
format: ARG_NAME2=${SECRET_VALUE}
```
Due to the way we iterate over the values, we caused the TaskRun to only have references to `key-2`. Unfortunatly, our existing unit test did not capture that. Also extending those.
```release-note
The usage of different secrets or secret keys as values inside one array parameter is now possible
```

Correct multiple secret values in one array parameter that references different secret variables

---

.github/workflows/release.yaml

Fixes for the release workflow to support release branches:
- Print input parameters at the start of the workflow.
- Use input git reference for release.
- Sign image using sha of the tag's git commit.
/kind cleanup
```release-note
NONE
```

Release Workflow Fixes

---

pkg/apis/build/v1beta1/build_conversion.go

When the Build controller still reconciled the Alpha version of Builds, it handled `spec.dockerfile` here: https://github.com/shipwright-io/build/blob/v0.12.0/pkg/reconciler/buildrun/resources/taskrun.go#L361-L369.
Basically if the value was nil, the parameter value was not added. With that, its default value, `"Dockerfile"` was used. https://github.com/shipwright-io/build/blob/v0.12.0/pkg/reconciler/buildrun/resources/taskrun.go#L74-L81
Suddenly, this was also happening when the `spec.dockerfile` was set to an empty string.
To mimic the same behavior with the conversion to Beta, I am changing our conversion code to behave the same = not adding the parameter value to be an empty string.
```release-note
An Alpha Build where `spec.dockerfile` is set to `""`, is now transformed to a Beta …
```

Do not set dockerfile parameter to an empty string to align with behavior of alpha controller

---

docs/buildrun.md
pkg/apis/build/v1beta1/buildrun_types.go
pkg/reconciler/buildrun/resources/conditions.go
pkg/reconciler/buildrun/resources/conditions_test.go
pkg/reconciler/buildrun/resources/failure_details.go
test/integration/buildruns_to_taskruns_test.go

When a BuildRun Pod fails because of too much ephemeral storage usage and is therefore evicted, then we expose this nicely in the BuildRun status as the condition reason is set to PodEvicted. In case a container went out of memory, we did not expose that at all in the BuildRun status while it is quite obvious in the TaskRun and Pod status who print the step/container status.
I am therefore proposing here to introduce the BuildRun failure reason StepOutOfMemory.
```release-note
You can now easily determine that your BuildRun failed because a step went out of memory as the reason is now set to StepOutOfMemory
```

Add StepOutOfMemory as reason for BuildRun failure

---

hack/check-latest-images.sh
samples/v1alpha1/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
samples/v1alpha1/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
samples/v1alpha1/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
samples/v1beta1/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml

BuildAh image tags are based on the BuildAh version (e. g. v1.35.3) and are mutable, meaning the tag that you consume gets rebuilt by the BuildAh team regularly to address vulnerabilities.
Recently, the BuildAh team also added immutable tags which are never rebuilt, but may be removed. https://lists.podman.io/archives/list/podman@lists.podman.io/thread/FP6I3OAHRYXDV5S7NFZHNJBV7AQQZHPD/
Especially the fact that those might get removed is imo meaning that we should not use them in our sample build strategies.
I therefore adjust our update script to filter out those tags to make sure we won't get PRs like https://github.com/shipwright-io/build/pull/1599/files again.
I am also changing the BuildAh step of our build strategies to use imagePullPolicy=Always to ensure the latest available image …

Revisit image tags in BuildAh sample build strategy

---

OWNERS

Move out @otaviof  to Emeritus
Add @apoorvajagtap  to approvers and reviewers.
Add @karanibm6 to approvers
Congrats @apoorvajagtap and @karanibm6 !
```release-note
NONE
```

Updates to Owners

---

cmd/image-processing/main_test.go

Mitigation for #1621
Enforce ordered execution since the introduction of the latest test context in `cmd/image-processing` led to failures when using Ginkgo CLI to drive the tests. Since the PR status checks are driven by `go test` this regression was not obvious.
```
$ go run github.com/onsi/ginkgo/v2/ginkgo run --coverprofile=unit.coverprofile --output-dir=build/coverage --randomize-all --trace ./cmd/image-processing
Running Suite: Image Processing Command Suite - /Users/mdiester/go/src/github.com/shipwright-io/build/cmd/image-processing
==========================================================================================================================
Random Seed: 1718369287 - will randomize all specs
Will run 23 of 23 specs
•••••••••••••••
------------------------------
• …
```

Enforce ordered execution of tests

---

pkg/reconciler/buildrun/resources/results.go
pkg/reconciler/buildrun/resources/results_test.go

When running with image vulnerability scanning enabled, and there is not vulnerability, the controller panics:
```txt
{"level":"info","ts":"2024-06-15T20:40:20Z","msg":"surfacing taskRun results to BuildRun status","controller":"buildrun-controller","object":{"name":"ubi-nonroot-9-minimal-fw69g-ndngd","namespace":"container-images-build"},"namespace":"container-images-build","name":"ubi-nonroot-9-minimal-fw69g-ndngd","reconcileID":"a72dd0d7-5697-4ef9-9f36-275ebb758466","namespace":"container-images-build","name":"ubi-nonroot-9-minimal-fw69g-ndngd"}
{"level":"info","ts":"2024-06-15T20:40:20Z","msg":"Observed a panic in reconciler: runtime error: index out of range [1] with length 1","controller":"buildrun-controller","object":{"name":"ubi-nonroot-9-minimal-fw69g-ndngd","namespace":"containe …
```

Do not panic if there are no vulnerabilities / Fix severity parsing

---

.github/workflows/release.yaml

Fix the `release.yml` workflow file to also bump new release version in the missing spot
Fixes #1601
```release-note
NONE
```

Fix release.yml workflow file

---

cmd/image-processing/main_test.go

Simplify the look-up for the test asset directory. No need for path cleaning function since it is a test case and the look-up is relative by default, so there is no need to look-up the current working directory.
```release-note
NONE
```

Refactor/simplify test asset directory look-up

---

pkg/image/delete.go

Add the respective legacy/old registry endpoints to the list of endpoints of the registry detection to allow users to potentially still use the old registry endpoints.
```release-note
The bundle prune option now also supports the legacy registry endpoints for both DockerHub and IBM Container Registry in its registry detection routine.
```

Add legacy endpoints to registry detection

---

test/e2e/v1alpha1/common_suite_test.go
test/e2e/v1alpha1/e2e_image_mutate_test.go
test/e2e/v1beta1/common_suite_test.go
test/e2e/v1beta1/e2e_image_mutate_test.go

https://github.com/shipwright-io/sample-nodejs/pull/12 updated the node version in our sample to 18 because Paketo removed support for Node 16. Though, the e2e test case for image mutation is using a specific commit of that repository to be able to test that the source timestamp is correct.
To fix this, I am changing the configuration of the Build to use an environment variable that tells Paketo to use Node 20.
```release-note
NONE
```

Pin to newer Node version that is still supported by Paketo

---

.github/workflows/ci.yml

As [discussed in the last community meeting](https://github.com/shipwright-io/community/issues/227#issuecomment-2228523745), this PR changes the e2e and integration to test two different Tekton versions.
We could actually think about automation that automatically updates the newest LTS version.
We will need to red-merge this one to then change the branch configuration to the changed check names that this change introduces.
Part of https://github.com/shipwright-io/build/issues/1640
```release-note
Shipwright Build is now validated on the oldest supported and the newest available Tekton LTS releases
```

Test two different Tekton versions in e2e and integration tests

---

deploy/700-deployment-webhook.yaml

- Fixed container name for shipwright-webhook from `shp-build-webhook ` to `shipwright-build-webhook `
- Fixes #1648 
```release-note
NONE
```

fixed container name for shipwright-webhook

---

README.md
deploy/200-role.yaml
hack/storage-version-migration.sh

Add script for storage version migartion of crds
Fixes https://github.com/shipwright-io/build/issues/1603
```release-note
You can now run a post-installation step to migrate the storage version of the custom resources
```

Add script for storage version migartion of crds

---

Makefile
samples/v1beta1/buildstrategy/multiarch-native-buildah/buildstrategy_multiarch_native_buildah_cr.yaml
samples/v1beta1/buildstrategy/multiarch-native-buildah/role_multiarch_native_buildah_cr.yaml
samples/v1beta1/buildstrategy/multiarch-native-buildah/rolebinding_multiarch_native_buildah_cr.yaml
samples/v1beta1/buildstrategy/multiarch-native-buildah/rolebinding_multiarch_native_buildah_scc_okd_cr.yaml
test/data/v1beta1/build_multiarch_native_buildah_cr.yaml
test/data/v1beta1/buildrun_multiarch_native_buildah_cr.yaml
test/e2e/v1alpha1/e2e_test.go
test/e2e/v1alpha1/validators_test.go
test/e2e/v1beta1/e2e_test.go
test/e2e/v1beta1/validators_test.go

This PR proposes a sample multi-arch native ClusterBuildStrategy. The ClusterBuildStrategy runs as a main orchestrator pod. It creates one "agent" job for each architecture requested by the Build. The agent jobs are responsible for building the container image and coordinate with the orchestrator pod via messages in FIFO pipes sent through the kubectl client.
The agent jobs run through the following coordination barriers:
1. Wait for the assets to be uploaded (source code, pull secrets, etc...)
2. Waiting for the image download to start
3. Waiting for the image download to finish
The orchestrator pod:
1. Create the agent jobs
2. Upload the assets and signal the completion of the assets upload through a write to the FIFO pipe in each agent job
3. Start the download of the oci archive
4. …

Native multi-arch ClusterBuildStrategy

---

.github/bump-tekton-lts.sh
.github/workflows/ci.yml
.github/workflows/update-tekton-version.yaml
README.md

This PR adds automation to bump to the latest Tekton LTS release. The first PR it will open will have an inconsistent from/to message because we have different from Tekton versions at various places. From then onwards, the messages will be consistent.
```release-note
NONE
```

Add automation to bump Tekton automatically

---

.github/workflows/update-tekton-version.yaml

The action that I recently introduced fails. Took me some time to figure out why. The reason is that the workflow tries to update a file insight .github/workflows. This requires a permission (workflows:write) that one cannot grant through a GitHub action permission itself. Instead one must use a personal access token. Reference: https://github.com/orgs/community/discussions/35410#discussioncomment-7645702
I created a personal access token for it and stored it as secret.
```release-note
NONE
```

Use dedicated token for the workflow that bumps the Tekton version

---

pkg/image/delete.go

Currently, all our PRs are red due to this finding:
```txt
run golangci-lint
Running [/home/runner/golangci-lint-1.60.1-linux-amd64/golangci-lint run --path-prefix=go/src/github.com/shipwright-io/build --timeout=10m] in [/home/runner/work/build/build/go/src/github.com/shipwright-io/build] ...
Received 1105143 of 1105143 (100.0%), 1.1 MBs/sec
Error: go/src/github.com/shipwright-io/build/pkg/image/delete.go:176:25: printf: non-constant format string in call to fmt.Errorf (govet)
return "", fmt.Errorf(string(bodyData))
```
I am changing our code accordingly.
```release-note
NONE
```

Change to errors.New because strings passed to fmt.Errorf should be constants according to govet

---

docs/buildstrategies.md

This PR proposes a new paragraph to document the Multiarch Native Buildah strategy proposed in https://github.com/shipwright-io/build/pull/1634.
I see the other strategies leverage a relative path to link to the strategy in the document; however, those links are dead, AFAICU. 
Therefore, I used GitHub permalinks. Are they okay with landing in the doc?
Relates to https://github.com/shipwright-io/build/issues/1119
```release-note
NONE
```
/kind documentation

Documentation for the multiarch-native-buildah ClusterStrategy

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
pkg/apis/build/v1beta1/build_types.go
pkg/bundle/bundle.go
pkg/reconciler/buildlimitcleanup/build_limit_cleanup.go
pkg/reconciler/buildlimitcleanup/controller.go

We have new gosec findings in https://github.com/shipwright-io/build/actions/runs/10484927930/job/29040118261?pr=1668 for the new G115 rule. Interestingly, gosec has not even released that while golangci-lint already validates it.
We actually had one real though unrealistic finding for the limits that we allow users to define for number of buildruns in a build. We have a uint there and casted it to int which theoretically can fail if a user would use an unreasonably high value that goes beyond math.MaxInt. I therefore declared a reasnably high maximum in the type and nosec'ed it.
In the bundle package, the finding is imo unrealistic but suddenly Go's tar Header type uses an int64 where it should be better using maybe directly os.FileMode.
```release-note
NONE
```

Address G115 findings

---

cmd/git/main_test.go

Replace website as the example repository, since it changed and its structure doesn't work for the unit test anymore. Switch to purely synthetic sample.
/kind bug
```release-note
NONE
```

Fix broken submodule unit test

---

.github/workflows/ci.yml

Ref: https://github.com/shipwright-io/build/issues/1689
Log into GitHub Container Registry for unit test so that Trivy database download can be done in an authenticated context.
Potentially mitigates (parts of) #1689
/kind bug
```release-note
NONE
```

Log into GitHub Container Registry for unit test

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
docs/build.md
docs/buildrun.md
pkg/apis/build/v1beta1/build_types.go
pkg/apis/build/v1beta1/buildrun_types.go
pkg/apis/build/v1beta1/zz_generated.deepcopy.go
pkg/reconciler/build/build.go
pkg/reconciler/build/build_test.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/buildrun_test.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
pkg/validate/nodeselector.go
pkg/validate/validate.go
test/integration/build_to_taskruns_test.go
test/integration/buildruns_to_taskruns_test.go
test/v1beta1_samples/build_samples.go
test/v1beta1_samples/buildrun_samples.go

Allows NodeSelector to be set on Build and BuildRun objects. 
Fixes #1635 
```release-note
Added NodeSelector on Build and BuildRun objects, which enables specifying the scheduling behavior of TaskRuns.
```

Add NodeSelectors to Build and BuildRun objects

---

pkg/image/vulnerability_scan.go

Part of https://github.com/shipwright-io/build/issues/1689
This changes the image processing step to perform a simple retry in case of Trivy failures due to rate limiting.
```release-note
The image-processing step now retries the vulnerability scan using Trivy if that failed to download the vulnerability database due to rate-limiting
```

Retry trivy when it fails to download the vulnerability database due to rate-limiting

---

pkg/bundle/bundle.go
pkg/bundle/bundle_test.go

There are file system setups where there is a file in a directory, but the directory does not have the write bit set (anymore). This kind of setup is perfect fine, however, the bundle logic is unable to unpack it.
Fix unpack logic so that it is not setting the file permissions of directories in the moment it creates the directory, but later when all other files are unpacked already and no more write operations are required.
/kind bug
```release-note
Fixed an issue when unpacking a code bundle that contains a non-writable sub-directory.
```

Fix issue with non-writable sub-directories

---

test/integration/build_to_buildruns_test.go

Fixing a flaxy test case here.
The two tests basically set up a a Build with retention atBuildDeletion=true. They then created a BuildRun. Then they either changed the flag to false or removed the whole retention section. And now a race started because they immediatly deleted the Build. At that point in time, it is unclear if the owner reference had already been removed from the buildrun or not. When the test failed, it was not yet removed so that the BuildRun was unexpectetly deleted.
I am changing the test case to first check that the owner reference is removed before deleting the build.
```release-note
NONE
```

Fix flaky test case

---

.github/workflows/check-latest-images.yaml

The GitHub action we are using to create a pull request is distinguishing author and committer of the commit it creates. See https://github.com/peter-evans/create-pull-request/tree/v7/?tab=readme-ov-file#action-inputs
In https://github.com/shipwright-io/build/pull/1692, the author is somehow the openshift-merge-robot.
Based on the action documentation, the author is taken from github.actor.
Based on https://github.com/orgs/community/discussions/25067, github.actor for a workflow run triggered by a schedule is the latest user that modified the schedule trigger. In our case that is the openshift-merge-robot because it merges our PRs including the PR that introduced or modified the GitHub action.
I am hereby changing the action configuration to use the GitHub Actions Bot also as author.
In …

Configure commit author, signing and signoff in GitHub action for image updates

---

.github/report-release-vulnerabilities.sh
.github/workflows/report-release-vulnerabilities.yaml

For a better management of our maintained release, I am here adding a GitHub action that downloads the latest release, extracts the images and checks those for OS and Go vulnerabilities. If any are found an issue is opened/edited that looks like this: https://github.com/SaschaSchwarze0/build/issues/35
```release-note
NONE
```

Add GitHub action that checks the latest release for vulnerabilities and reports them in an issue

---

Makefile

Based on the documentation, increase verbosity to improve the ability to debug issues based on the Ginkgo output:
```
--vv
If set, emits with maximal verbosity - includes skipped and pending tests.
--trace
If set, default reporter prints out the full stack trace when a failure
occurs
```
This should help us to address the panic in the AfterEach for example here that blocks us to determine why the test case actually faliled:
```
2024-10-30T12:09:48Z 1 Still waiting for build run 'timestamp-lm5jx' to succeed.
2024-10-30T12:10:48Z 1 Still waiting for build run 'timestamp-lm5jx' to succeed.
[FAILED] in [It] - /home/runner/work/build/build/test/e2e/v1beta1/validators_test.go:134 @ 10/30/24 12:11:08.558
2024-10-30T12:11:08Z 1 Print failed BuildRun's log
[PANICKED] in [AfterEach] - …
```

Use `--vv` and `--trace` in E2E

---

test/e2e/v1beta1/common_test.go

This fixes the following panic we see in `AfterEach` hooks of the e2e tests that actually prevent us to identify the root cause.
```
[PANICKED] Test Panicked
In [AfterEach] at: /opt/hostedtoolcache/go/1.22.8/x64/src/runtime/panic.go:261 @ 10/30/24 14:53:26.63
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
github.com/shipwright-io/build/pkg/reconciler/buildrun/resources.GetBuildObject({0x2358398?, 0xc00076aaa0?}, {0x2368620?, 0xc00076d5f0?}, 0xedeb43f66?, 0x0?)
/home/runner/work/build/build/pkg/reconciler/buildrun/resources/build.go:39 +0x28b
github.com/shipwright-io/build/test/e2e/v1beta1_test.retrieveBuildAndBuildRun(0xc000102b60, {0xc00005c1d7?, 0x0?}, {0xc000429e75, 0xb})
/home/runner/work/build/build/test/e2e/v1beta1/common_test.go:147 +0x105
```
See …

Set Build to empty object because GetBuildObject will fill but not initialize it

---

pkg/util/filelisting.go

Follow-up from https://github.com/shipwright-io/build/pull/1702 to add the total size in bytes of all files and the total number of files to the file listing so that its immediately visible.
```
$ bundle --image ghcr.io/shipwright-io/sample-go/source-bundle:latest --target /tmp/workspace/source --show-listing
2024/11/04 11:58:04 Pulling image "ghcr.io/shipwright-io/sample-go/source-bundle:latest"
2024/11/04 11:58:05 Image content was extracted to /tmp/workspace/source
-rw-r--r--  1  501  0  11.1K  LICENSE
-rw-r--r--  1  501  0   249B  OWNERS
-rw-r--r--  1  501  0   1.3K  README.md
drwxr-xr-x  4  501  0   128B  docker-build
-rw-r--r--  1  501  0   381B  docker-build/Dockerfile
-rw-r--r--  1  501  0   972B  docker-build/main.go
drwxr-xr-x  4  501  0   128B  docker-build-with-args
-rw-r--r-- …
```

Add total size and total file count to file listing

---

test/e2e/v1alpha1/common_test.go
test/e2e/v1beta1/common_test.go

Fixing the following panic in e2e AfterEach:
```
[PANICKED] Test Panicked
In [AfterEach] at: /opt/hostedtoolcache/go/1.22.8/x64/src/runtime/panic.go:261 @ 11/04/24 10:12:22.241
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
github.com/shipwright-io/build/test/e2e/v1alpha1_test.GetBuildObject({0x23570d8?, 0xc000598410?}, {0x2367360?, 0xc0001573b0?}, 0xe31de5d?, 0xedeba9506?)
/home/runner/work/build/build/test/e2e/v1alpha1/common_test.go:258 +0x41
github.com/shipwright-io/build/test/e2e/v1alpha1_test.retrieveBuildAndBuildRun(0xc00027e3f0, {0xc00005c1bf?, 0x0?}, {0xc000940960, 0xf})
/home/runner/work/build/build/test/e2e/v1alpha1/common_test.go:150 +0x11a
github.com/shipwright-io/build/test/e2e/v1alpha1_test.printTestFailureDebugInfo(0xc00027e3f0, …
```

Fix nil pointer access in AfterEach of failed e2e test cases

---

.github/workflows/report-release-vulnerabilities.yaml

The new action to check for vulnerabilities was failing due to the unavailability of the `crane` command. https://github.com/shipwright-io/build/actions/runs/11655851486/job/32451121704
Adding it (and irritated why it succeeded in my fork).
```release-note
NONE
```

Install crane binary

---

.github/workflows/ci.yml
README.md

See https://github.com/tektoncd/pipeline/blob/main/releases.md
Tekton v0.53 has an end of support in 10/2024. I am therefore changing the minimum required Tekton version to v0.56.
```release-note
The new minimum Tekton version is v0.56
```

Update minimum Tekton LTS to v0.56

---

docs/buildstrategies.md
samples/v1alpha1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/v1beta1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml

In our sample build strategies for BuildKit, we never used a specific version as tag. Instead, we used nightly which is the main branch. This finally broke us as our e2e are failing:
```
#9 ERROR: process "/bin/sh -c pwd &&     ls -l &&     npm install &&     npm run print-http-server-version" did not complete successfully: buildkit-runc did not terminate successfully: exit status 1: unable to destroy container: unable to remove container's cgroup: open /sys/fs/cgroup/5aqt7rzovvis0vrkm6iuwynpu: no such file or directory
```
I am hereby changing the strategy to use the images of the latest BuildKit release instead. This is inline with everything comparable that we have (kaniko, buildah).
[A separate PR will be needed to add automatic bumping of the image tag on a new …

Use specific tag for BuildKit

---

pkg/util/filelisting.go

In almost all cases, the `.git` directory content is not directly helpful in the file listing and it leads to a lot of noise in the output.
Do not show `.git` files in file listing, but show a summary of size and file count at the end in the footer section.
```
$ git-step --url https://github.com/shipwright-io/sample-go --target /tmp/workspace/source --show-listing
2024/11/05 12:11:34 Info: ssh (/usr/bin/ssh): OpenSSH_9.7p1, LibreSSL 3.3.6
2024/11/05 12:11:34 Info: git (/opt/homebrew/bin/git): git version 2.46.0
2024/11/05 12:11:34 Info: git-lfs (/opt/homebrew/bin/git-lfs): git-lfs/3.5.1 (GitHub; darwin arm64; go 1.23.1)
2024/11/05 12:11:34 /opt/homebrew/bin/git -c safe.directory=/tmp/workspace/source clone -h
2024/11/05 12:11:34 /opt/homebrew/bin/git -c …
```

Tweak file listing to omit `.git` directory

---

pkg/env/env.go
pkg/volumes/volumes.go

Golangci-lint started to complain the usage of `new` as variable name: https://github.com/shipwright-io/build/actions/runs/11785633189/job/32827274452?pr=1730
```txt
Running [/home/runner/golangci-lint-1.62.0-linux-amd64/golangci-lint run --path-prefix=go/src/github.com/shipwright-io/build --timeout=10m] in [/home/runner/work/build/build/go/src/github.com/shipwright-io/build] ...
Error: go/src/github.com/shipwright-io/build/pkg/env/env.go:17:19: redefines-builtin-id: redefinition of the built-in function new (revive)
func MergeEnvVars(new []corev1.EnvVar, into []corev1.EnvVar, overwriteValues bool) ([]corev1.EnvVar, error) {
^
Error: go/src/github.com/shipwright-io/build/pkg/volumes/volumes.go:72:65: redefines-builtin-id: redefinition of the built-in function new (revive)
func …
```

Remove usages of "new" as variable name

---

samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
samples/v1beta1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/v1beta1/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
test/data/v1beta1/build_buildah_cr_target_stage.yaml
test/data/v1beta1/build_buildkit_cr_target_stage.yaml
test/data/v1beta1/build_kaniko_cr_target_stage.yaml
test/data/v1beta1/buildrun_buildah_cr_target_stage.yaml
test/data/v1beta1/buildrun_buildkit_cr_target_stage.yaml
test/data/v1beta1/buildrun_kaniko_cr_target_stage.yaml
test/e2e/v1beta1/e2e_test.go

I recently stumbled over a single Dockerfile that combined multiple output images and one had to run `docker build --target STAGE` to select which one should actually be built. And that was not possible with our sample build strategies because we had no parameter for the target stage. Adding this. Related Dockerfile feature: https://docs.docker.com/build/building/multi-stage/#stop-at-a-specific-build-stage
```release-note
The Dockerfile-based sample build strategies for BuildAh, BuildKit and Kaniko now have a target parameter to define the stage to be built
```

Extend Dockerfile based build strategies with target build stage

---

.github/workflows/check-latest-images.yaml
hack/check-latest-images.sh

As we recently changed the BuildKit image to be based on the latest release instead of nightly, I am hereby adding the automation to automatically bump it.
Fixes #1724
```release-note
NONE
```

Add automation to trigger automatic updates of the BuildKit image in our sample build strategies

---

.github/workflows/check-latest-images.yaml

PR https://github.com/shipwright-io/build/pull/1745 is opened without version information in the title because the regular expression only selected `git diff` lines with image names with at least two `/` characters, but `moby/buildkit` has only one. Using just `.*` is good enough there because it selects the full image name.
```release-note
NONE
```

Correct regex that selects the lines with image changes

---

pkg/git/git.go

Ref: https://github.com/shipwright-io/build/pull/1765
Change the way to check for the error so that it finds the error in an error chain.
```release-note
NONE
```

Change error check in `pkg/git`

---

go.mod
go.sum
vendor/golang.org/x/net/html/doc.go
vendor/golang.org/x/net/html/doctype.go
vendor/golang.org/x/net/html/foreign.go
vendor/golang.org/x/net/html/iter.go
vendor/golang.org/x/net/html/node.go
vendor/golang.org/x/net/html/parse.go
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/unencrypted.go
vendor/modules.txt

Fixes CVE-2024-45338 in v0.14 branch.
```release-note
Update golang.org/x/net from v0.30.0 to v0.33.0 to address CVE-2024-45338
```

[release-v0.14] Update golang.org/x/net from v0.30.0 to v0.33.0

---

cmd/bundle/main.go
cmd/git/main.go
pkg/git/git.go
pkg/git/git_test.go
pkg/image/endpoint.go
pkg/image/endpoint_test.go
pkg/util/tcp.go
pkg/util/tcp_test.go
pkg/util/util_suite_test.go

This aims to mitigate rare failures where a BuildRun pod runs in a namespace with NetworkPolicies present. Kubernetes defines that isolation rules are guaranteed to be applied before any container of the Pod is started, but allow rules are eventually applied. See https://kubernetes.io/docs/concepts/services-networking/network-policies/#pod-lifecycle: *Therefore, pods must be resilient against being started up with different network connectivity than expected*
I am therefore extending the logic of the Git and OCI artifact source steps to test connectivity as these are the first containers in a BuildRun pod that actually require network connectivity. And given we own them, we should be resilient.
```release-note
The source steps for sources of type Git and OCIArtifact now check the …
```

Test connectivity to the Git or Registry host before accessing the source

---

.github/download-latest-release.sh
.github/report-release-vulnerabilities.sh
.github/workflows/report-release-vulnerabilities.yaml

In this PR, I ...
* split the action which so far only ran a single script into two scripts: the first script downloads the latest release and determines details (tag, branch, go-version), the second script scans for vulnerabilities, checks if a rebuild fixes them and if that is the case triggers a release
* extend the action so that after the first script it clones the release branch and also calls setup-go again to use the Go version from the release branch
* reschedule the action to start 15 minutes after the base image build (which usually takes between four and five minutes to complete)
* assign the created issue to the users listed as approvers in the OWNERS file
I tested the scripts and their commands, but I cannot test the overall action anywhere as I don't have the necessary …

Improve Report release vulnerabilities action

---

.github/report-release-vulnerabilities.sh
.github/workflows/report-release-vulnerabilities.yaml

Fixing various things. Worked here: https://github.com/shipwright-io/build/actions/runs/12668225863/job/35303199697. Output is https://github.com/shipwright-io/build/issues/1742. It did not trigger the release workflow because there is [one vulnerability that is not yet fixed in v0.14](https://github.com/shipwright-io/build/pull/1768).
```release-note
NONE
```

Fix action on release vulnerabilities

---

.github/report-release-vulnerabilities.sh

The report vulnerabilities action today correctly determined that everything is fixed and triggered a new release automatically. Though, the comment in https://github.com/shipwright-io/build/issues/1742#issuecomment-2579141929 was not accurate as it stated the wrong tag. Correcting this.
Also, the action (https://github.com/shipwright-io/build/actions/runs/12683451116) ran with the workflow definition from the main branch. It should have been the release branch. This did not matter this time because the release workflow was not changed. But it can matter in the future. I am also correcting this. …

Corrections in vulnerability action triggering new release

---

.github/report-release-vulnerabilities.sh
.github/workflows/report-release-vulnerabilities.yaml

The [scheduled workflow run this morning](https://github.com/shipwright-io/build/actions/runs/12703058506/job/35410244246) failed to close the issue because the `gh` command was not correct.
I corrected this, tried it out [here](https://github.com/shipwright-io/build/actions/runs/12705564792/job/35416821868) and [the issue was closed successfully](https://github.com/shipwright-io/build/issues/1742#issuecomment-2582007841).
I have also added an event trigger to the workflow so that it runs when a release is published or edited (which potentially means that it was marked latest). Therefore the action will close the vulnerabilities issues earlier and not (only) in the nightly run that comes next.
```release-note
NONE
```

Fix gh command that closes the issue when all vulnerabilities are fixed

---

.github/workflows/ci.yml

In e2e we had disk space issues and therefore used the maximize-build-space action. We still sometimes had failures and with the more complex cluster setup needed in #1711, we need again more disk space.
Switching to the larger custom runners that we get from CNCF for e2e tests. They have more than 500 G disk space, that will be enough for us.
With the additional compute power, e2e completes in ≈ 21 minutes instead of ≈ 35 minutes. (We run ginkgo with `-p` without any explicit parallism. It automatically used 15. See "Running in parallel across 15 processes" in logs, the default workers had just 4).
```release-note
NONE
```

Use ubuntu-latest-16-cores from CNCF for e2e

---

.github/report-release-vulnerabilities.sh

Action run https://github.com/shipwright-io/build/actions/runs/12961644962/job/36157172795 failed to retrieve the number of the issue that was just created using a search. My assumption is that it failed because of eventual consistency.
Changing the logic to instead use the issue URL which is printed by the `gh issue create` command. The `gh issue comment` command where it is used support both a number as well as a URL.
```release-note
NONE
```

Do not use issue search to determine number of issue that was just created

---

README.md

The release automation PR'ed to the release-v0.14 branch. Cherry-picking the readme updates into main.
Also added a commit to automatically update the tag of the link pointing to the storage migration script.
```release-note
NONE
```

Update Readme with new Tags v0.14.1 + v0.14.2

---

ROADMAP.md

Update the roadmap to include the tentative release schedule for 2025. This schedule includes the expected versions of Kubernetes and Tekton used for development and CI testing. The dates lead the overall project release schedule by two weeks to encourage updates/rebases in downstream projects, such as the CLI and operator.
/kind documentation
```release-note
NONE
```

doc: 2025 Release Schedule

---

.github/workflows/ci.yml
deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
docs/build.md
docs/buildrun.md
pkg/apis/build/v1beta1/build_types.go
pkg/apis/build/v1beta1/buildrun_types.go
pkg/reconciler/build/build.go
pkg/reconciler/build/build_test.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/buildrun_test.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
pkg/validate/nodeselector.go
pkg/validate/tolerations.go
pkg/validate/validate.go
test/data/v1beta1/build_buildah_tolerations_cr.yaml
test/data/v1beta1/buildrun_buildah_tolerations_cr.yaml
test/e2e/v1beta1/e2e_test.go
test/integration/build_to_taskruns_test.go
test/integration/buildruns_to_taskruns_test.go
test/kind/config_three_node.yaml
test/utils/v1beta1/nodes.go
test/v1beta1_samples/build_samples.go
test/v1beta1_samples/buildrun_samples.go

Fixes #1636 
```release-note
Add Tolerations to Build and BuildRun objects
```

Add Tolerations to Build and BuildRun objects

---

.github/workflows/release.yaml

- Modify the "Draft release" task to use the gh command line tool instead of the actions/create-release action
Fixes #1567 
```release-note
Fixed deprecated release-actions in favor of gh command line.
```

[1567] Release Workflow Action No Longer Maintained

---

pkg/apis/build/v1beta1/build_types.go
pkg/apis/build/v1beta1/buildrun_types.go
pkg/apis/build/v1beta1/buildstrategy_types.go
pkg/apis/build/v1beta1/clusterbuildstrategy_types.go
pkg/apis/build/v1beta1/register.go
pkg/apis/build/v1beta1/trigger.go
pkg/apis/build/v1beta1/trigger_types.go
pkg/apis/build/v1beta1/trigger_when.go

Update our code comment markers and copyright notice placement so that the elastic/crd-ref-docs tool can generate API reference docs:
- Add `kubebuilder:object:root=true` marker for root CRD types. The crd-ref-docs tool looks for these to identify new `Kind` APIs.
- Move copyright comments so they are not mistaken for package-level docs.
Note - this only applies to the `v1beta1` API.
Needed for https://github.com/shipwright-io/website/pull/147
/kind cleanup
```release-note
NONE
```

fix: Add Markers and Move Comments for API Docs

---

.github/workflows/release.yaml
README.md

Cherry-picked the three updates from the v0.14 branch to main. Also updated the release logic to bump the version of the storage-version-migration script (I had manually added that so far).
```release-note
NONE
```

Add v0.14.2 and v0.14.3 and v0.14.4 to readme

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
docs/build.md
docs/buildrun.md
pkg/apis/build/v1beta1/build_types.go
pkg/apis/build/v1beta1/buildrun_types.go
pkg/reconciler/build/build.go
pkg/reconciler/build/build_test.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrun/buildrun_test.go
pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go
pkg/validate/nodeselector.go
pkg/validate/nodeselector_test.go
pkg/validate/scheduler_name.go
pkg/validate/scheduler_name_test.go
pkg/validate/tolerations.go
pkg/validate/tolerations_test.go
pkg/validate/validate.go
test/e2e/v1beta1/e2e_test.go
test/integration/build_to_taskruns_test.go
test/integration/buildruns_to_taskruns_test.go
test/v1beta1_samples/build_samples.go
test/v1beta1_samples/buildrun_samples.go
test/v1beta1_samples/catalog.go

Fixes #1637 
```release-note
Add Custom Scheduler Name to Build and BuildRun objects
```

Add Custom Scheduler Name to Build and BuildRun objects

---

samples/v1alpha1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
samples/v1beta1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml

Since Kubernetes 1.31, seccomp annotations are ignored. Therefore finally moving them to the container security context.
```release-note
The BuildKit sample build strategy defines the seccomp profile now in the security context instead of the - since k8s 1.31 - unsupported annotation
```

Move seccomp profile definition to container securityContext

---

go.mod
go.sum
vendor/golang.org/x/crypto/ssh/handshake.go
vendor/golang.org/x/crypto/ssh/server.go
vendor/golang.org/x/oauth2/pkce.go
vendor/modules.txt

Fix security vulnerabilities in main found by #1810 
```release-note
NONE
```

Update golang.org/x/crypto to v0.35.0 to address GO-2025-3487; update golang.org/x/oauth2 to v0.27.0 to address GO-2025-3488

---

OWNERS

Promote Dylan Orzel (@dorzel) to `reviewer` in the shipwright-io/build repo, in recognition of his contributions related to scheduling builds on Kubernetes clusters. Many of these implement the API-level features described in SHIP-0039 [1].
Thank you Dylan for your efforts!
[1] https://github.com/shipwright-io/community/blob/main/ships/0039-build-scheduler-opts.md
/kind cleanup
```release-note
NONE
```

Add dorzel to OWNERS as Reviewer

---

docs/buildstrategies.md
samples/v1beta1/buildstrategy/multiarch-native-buildah/clusterrole_multiarch_native_buildah_cr.yaml
samples/v1beta1/buildstrategy/multiarch-native-buildah/rolebinding_multiarch_native_buildah_cr.yaml

This PR includes following changes:
- Replaces the Role references to ClusterRole references. Updates the doc to create the roleBindings accordingly.
- In kind cluster, there doesn't seem to have `pipeline` SA in all the namesapces, so, another commit makes SERVICE_ACCOUNT configurable while applying the roleBinding.
Fixes #1756 
```release-note
NONE
```

Updates Multi-Arch resources to be ClusterScoped

---

hack/release.sh

For the multiarch buildstrategy, https://github.com/shipwright-io/build/tree/main/samples/v1beta1/buildstrategy/multiarch-native-buildah, we are delivering also a ClusterRole and RoleBindings so that the running build has the necessary permissions to manage Jobs and Pods in the cluster.
As described in https://github.com/shipwright-io/build/blob/main/docs/buildstrategies.md#installing-multi-arch-native-buildah-strategy, the RoleBinding must be installed in the namespace(s) where the build strategy will be used. As we cannot know which namespaces those are, we should not include this file in our sample-strategies.yaml.
This PR excludes it like we already also exclude our sample namespaces build strategies.
```release-note
The role bindings related to the multiarch-native-buildah cluster …
```

Exclude RoleBinding from sample-strategies.yaml

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
pkg/apis/build/v1beta1/buildrun_types.go
pkg/apis/build/v1beta1/source.go

Adding clearer descriptions of the source code spec options for `Build` and `BuildRun` objects. This is particularly relevant for the `OCIArtifact` source type, which extracts the contents of a "scratch" container image to a local directory.
These updated godoc comments should then get synced to the docs repository and published at https://shipwright.io/docs/ref/api/build/.
/kind documentation
```release-note
NONE
```

doc: Improve godoc for Source Code Spec

---

docs/build.md
pkg/validate/sources.go
pkg/validate/sources_test.go

While reviewing #1846, I noticed that the value we use for `.spec.source.type` is just [`OCI`](https://github.com/shipwright-io/build/blob/v0.15.0/pkg/apis/build/v1beta1/source.go#L24). I always assumed it is `OCIArtifact` - and that's also what the documentation had.
And while looking around in that context, I noticed that the validation code did not use the constants defined in the API package.
```release-note
NONE
```

Correct expected value for source.type

---

deploy/200-role.yaml
hack/storage-version-migration.sh

`hack/storage-version-migration.sh script` is using permissions to patch CustomResourceDefinitions.
The needed permissions were added to the script and then deleted after the script is done executing.
Fixes #1789
```release-note
NONE
```

remove get,patch of CustomResourceDefinitions.

---

cmd/git/main.go

Fixes #1874
When providing a commit sha as revision of a Git source, then we always performed a `git clone --no-checkout` followed by a `git checkout COMMIT_SHA`. By doing that, we performed a full history clone and therefore ignored the `depth` provided by the user.
In case the commit sha is a full commit sha, we can actually provide it with `git clone --revision COMMIT_SHA` and then also honor the deptch. For a short commit sha, this is not working, there we must still clone the full history to be able to checkout the short sha afterwards.
However, our ubi9-based images do not contain a Git binary that is new enough to support the `--revision` flag:
```txt
2025/05/11 09:34:31 /usr/bin/git -c safe.directory=/workspace/source clone --quiet --no-tags --revision …
```

When a full commit SHA is provided as revision, provide it with the git clone command and honor the depth

---

pkg/controller/controller.go

When we create a TaskRun for a BuildRun, then we always add the `buildrun.shipwright.io/name` label. Tekton also applies this to the pod it creates.
This change configures the cache of our manager to only cache TaskRuns and Pods that have this label. This should bring down the memory usage of our controller a lot, especially when it runs in a cluster that is used for not just Shipwright and has many pods and maybe also taskruns which are not applicable. It may also improve startup time. In my local home cluster, "just" 391 pods and 258 taskruns in total where for each only 25 are BuildRun-related, the memory usage after startup went down from 33 MB to 20 MB.
I had to move up the scheme registration to before initializing the manager to pass it in as the manager needs it for the cache …

Only cache pods and taskruns with the buildrun label

---

images/git/Dockerfile

Fixes issue where tar command was not found when git base image was being build for ubi10
```release-note
NONE
```

Update git Dockerfile to download git-lfs in own layer

---

pkg/reconciler/build/build.go
pkg/reconciler/buildrun/buildrun.go
pkg/reconciler/buildrunttlcleanup/buildrun_ttl_cleanup.go
test/integration/build_to_taskruns_test.go
test/integration/buildruns_to_taskruns_test.go

Set field ownership for the Build and BuildRun controllers so that we avoid collisions when making API create/update calls (and future server-side apply calls).
/kind feature
```release-note
Build and BuildRun controllers will use an explicit field owner when creating and updating their respective resources.
```

feat: Set Field Owners for Build/BuildRun Controllers

---

.github/bump-tekton-lts.sh
.github/workflows/ci.yml

Replaced separate Kubernetes and Tekton version matrices with a single compatibility matrix in the CI configuration. This change reduces our test matrix from 4 runs to 2 for the integration and e2e test suites, skipping configurations that are less likely to be run by end users.
/kind cleanup
```release-note
NONE
```

feat: Reduce CI Test Matrix Cardinality

---

.ko.yaml

[`.ko.yaml`](diffhunk://#diff-a4f2ae2e878c4ea5e68c38199b536fac0de1b097db8c23a887d0d0fb65028a7bL1-R7): Changed `defaultBaseImage` from `ubi9/ubi-minimal` to `ubi10/ubi-minimal`, and updated `baseImageOverrides` to use `ubi10` tags for all components (`bundle`, `git`, `image-processing`, and `waiter`).
Fixes #1903 
```release-note
All Shipwright container images are now built with Redhat Universal Base Image 10 as a base, was version 9 before
```

feat: Update controller image to ubi10

---

.github/workflows/check-latest-images.yaml
hack/check-latest-images.sh

Fix `validate` call to fail if no args are given.
Add check to verify that the release isn't `null`.
Add conditional authenticated call to GitHub API.
Fix indentation in script to match common style.
"Fixes" #1942
```release-note
NONE
```

Tweak `check-latest-images.yaml` to use authenticated call

---

deploy/crds/shipwright.io_buildruns.yaml
deploy/crds/shipwright.io_builds.yaml
pkg/apis/build/v1alpha1/build_types.go
pkg/apis/build/v1beta1/build_types.go

Seems v0.16 of added ""  as a required value by mistake to some objects in the buildrun and build crd. This wasnt in v0.15 which created volume creating issues.
Fixes: #1947 
```release-note
NONE
```

Remove `""` from required fields

---

test/e2e/v1alpha1/e2e_bundle_test.go
test/e2e/v1alpha1/e2e_image_mutate_test.go
test/e2e/v1alpha1/e2e_local_source_upload_test.go
test/e2e/v1alpha1/e2e_one_off_builds_test.go
test/e2e/v1alpha1/e2e_params_test.go
test/e2e/v1alpha1/e2e_rbac_test.go
test/e2e/v1alpha1/e2e_test.go
test/e2e/v1beta1/e2e_image_mutate_test.go
test/e2e/v1beta1/e2e_local_source_upload_test.go
test/e2e/v1beta1/e2e_ociartifact_test.go
test/e2e/v1beta1/e2e_one_off_builds_test.go
test/e2e/v1beta1/e2e_params_test.go
test/e2e/v1beta1/e2e_rbac_test.go
test/e2e/v1beta1/e2e_test.go
test/e2e/v1beta1/e2e_vulnerability_scanning_test.go

Added Ginkgo labels to isolate features in e2e tests
*   The tests labeled `CORE` cover a wide range of functionalities, including different build strategies (Buildah, Kaniko, etc.), source types (Git, local bundle), image mutation, and interactions with repository types.
*  The tests labeled `SAMPLE` cover the samples (illustrative manifest files (YAML) designed to help users understand how to define `Build`, `BuildRun`, `BuildStrategy`, resources) we have in the /samples directory 
Fixes #1451 
```release-note
NONE
```

add labels to isolate features in e2e tests

---

pkg/reconciler/buildrun/resources/image_processing.go
pkg/reconciler/buildrun/resources/sources/utils.go
pkg/reconciler/buildrun/resources/taskrun_test.go

Breaking the changes of https://github.com/shipwright-io/build/pull/1885 into smaller prs to make review easier in the effort of better security practices for the containers that are used for the build process. 
Added env variables for trivy to configure writing to volumes instead of the root filesystem.
Added a utility function `AppendWriteableVolumes` to be used for appending volumes to steps.
Volumes introduced to trivy:
- volume for trivy cache
- volume for tmp data
Set env variables:
- TRIVY_CACHE_DIR
- TMPDIR
```release-note
Added volumes and config for trivy to enable its cache and tmp data to be …
```

Add volume for trivy

---

pkg/reconciler/buildrun/resources/taskrun.go
pkg/reconciler/buildrun/resources/taskrun_test.go

The existing TaskRun generation logic was concentrated in a single monolithic
GenerateTaskRun function, making it difficult to maintain, test, and debug
individual configuration aspects. This created tight coupling and poor separation
of concerns.
Decomposed the monolithic GenerateTaskRun into a comprehensive function.
orchestrated by smaller, single-responsibility helper functions. Each
configuration aspect now has its own dedicated applyXFeature* function.
This approach enables better error isolation, easier unit testing of individual
components, and clearer code organization. Enhanced error messages now provide
specific context about which BuildRun and strategy caused failures, improving
debugging experience for operators.
Key architectural changes:
- Made GenerateTaskRun as the main …

chore: Refactor GenerateTaskRun with improved modularity and naming consistency
